### ISSUE TITLE
Mesh.numVertices() incorrect

### ISSUE THREAD

**Issue by SolarLune** [GoranM/bdx#1000]
Hello. 

I think there's some misunderstanding regarding Mesh.numVertices() - it's returning not the number of vertices, but the number of elements in the vertex array for the mesh.

As an example, the number of vertices for a simple plane is 4. The number of indices would be 6, with 4 of them pointing to the same 2 vertices. However, `Mesh.numVertices()` returns 48 for a plane -
 that's the number of values in the vertex array for the mesh part indicated, not the number of vertices.

Basically, my problem stems from the fact that you can't loop through 0...Mesh.numVertices() to access all of the vertices, because the number of vertices isn't what `Mesh.numVertices()` refers to. I think we should change the name to something else, and update the API description. I think we also might do well to add an iterator to simplify the vertex looping process (since you usually want to loop through them all).

I'm fine with doing it myself, I just wanted to see what @rafcolson has to say.

**Comment by rafcolson** [comment]
>Basically, my problem stems from the fact that you can't loop through 0...Mesh.numVertices() to access all of the vertices, because the number of vertices isn't what Mesh.numVertices() refers to.

`Mesh.vertices()` is "the complete vertex array" as documented in the [API](https://github.com/GoranM/bdx/wiki/API-Mesh#vertices-ms-getter). Only logical that `Mesh.numVertices()` would be the length of the complete vertex array. This also resembles [LibGdx's `Mesh.getNumVertices()`](https://libgdx.badlogicgames.com/nightlies/docs/api/com/badlogic/gdx/graphics/Mesh.html#getNumVertices--) which equals [`Mesh.vertices.getNumVertices()`](https://github.com/libgdx/libgdx/blob/master/gdx/src/com/badlogic/gdx/graphics/Mesh.java#L348), with `vertices` being the [`VertexData`](https://github.com/libgdx/libgdx/blob/master/gdx/src/com/badlogic/gdx/graphics/glutils/VertexData.java).

So, you should loop through the indices of the vertex array instead, using `Mesh.numIndices()` as is documented [here](https://github.com/GoranM/bdx/wiki/API-Mesh#numIndices).

Hope that this clears things up.

>I think we should change the name to something else, and update the API description.

If `Mesh.numVertices()` would be equivalent to `Mesh.numIndices()`, what would be the names of the functions to get and set the vertex array and the length of the vertex array?

It's well documented in the API and not confusing to me at all, especially considering the fact that LigGdx uses a similar naming convention because of the way OpenGL works. One vert is an array of coordinates for position, the normal and uv, so generally speaking, the plural would be the collection of those coordinates, right?

>I think we also might do well to add an iterator to simplify the vertex looping process (since you usually want to loop through them all).

I'm not sure what you mean particularly. Could you explain a bit?

**Comment by SolarLune** [comment]
> If Mesh.numVertices() would be equivalent to Mesh.numIndices(), what would be the names of the functions to get and set the vertex array and the length of the vertex array?

I guess I'd just rather have `numVertices()` be renamed to something like `numElements()` or `numValues()`, since it's not the number of vertices, but the size of the vertex array. Getting and setting the vertex array with `vertices()` is fine.

> I'm not sure what you mean particularly. Could you explain a bit?

Just that we could add a function to abstract things away a bit. We could have a function that returns an iterator to easily loop through the vertices in a mesh, like so:

```java
for (int i : mesh().vertIter(1)) {
    ...
}

// Equivalent to

for (int i = 0; i < mesh().numIndices(1); i++) {
    ...
}
```

**Comment by rafcolson** [comment]
>I guess I'd just rather have `numVertices()` be renamed to something like `numElements()` or `numValues()`, since it's not the number of vertices, but the size of the vertex array. Getting and setting the vertex array with `vertices()` is fine.

@GoranM What do you think?

>Just that we could add a function to abstract things away a bit. We could have a function that returns an iterator to easily loop through the vertices in a mesh, like so:

I think what you are looking for are these methods:
```java
	public float[] indices(){
		return model.meshes.first().getIndices(new float[numIndices()]);
	}
	
	public float[] indices(int ms){
		MeshPart mp = model.meshParts.get(ms);
		int offset = mp.offset;
		int numIndices = mp.size;
		return mp.mesh.getIndices(offset, numIndices, new float[numIndices]);
	}	
```

**Comment by SolarLune** [comment]
> I think what you are looking for are these methods:

Ah, that is what I'm looking for! Thanks, I'll add an example to the wiki.

**Comment by rafcolson** [comment]
Oh, right, my mistake.

**Comment by rafcolson** [comment]
I'll submit another PR for adding `Mesh.indices(..)` after some of the currently open PR's are merged.

**Comment by rafcolson** [comment]
PR submitted.

**Comment by GoranM** [comment]
> @GoranM What do you think?

"vertexArraySize" would be the logically fitting name, and then "vertexCount" could be the name of the function that returns "vertexArraySize() / VERT_SIZE".

As far as iteration goes, I know that the following is very fast:

```java
for (int i = 0; i < vertex_count; ++i){
    vertex_array[i * vertex_size + x] = whatever;
}
```

I'm not so sure about iterators, and related java objects, or data copies that may need to be created by the VM to support that.

When you're dealing with a lot of data (as you would with a sizable mesh), the difference between direct memory access, and anything else, tends to be significant.

... Also, I don't know how "indices" are relevant here, because indices are not vertex data. Actually, unless you guys changed something that I failed to notice, we don't even leverage index data in any real sense: For a plane, we have vertex data for 6 vertices, forming 2 triangles. The index buffer is just a straight range from 0 to vertex_count, and we only bother to provide it because libgdx expects to get it.

**Comment by rafcolson** [comment]
>"vertexArraySize" would be the logically fitting name, and then "vertexCount" could be the name of the function that returns "vertexArraySize() / VERT_SIZE"

Okay. I'll replace those names then.

**Comment by rafcolson** [comment]
>... Also, I don't know how "indices" are relevant here, because indices are not vertex data.

I'm not sure how to go forward here. Would you rather not prefer methods such as `Mesh.indices()` or ? I'm also not sure how to name this method now, since `Mesh.numIndices()` is renamed to `Mesh.vertexCount()`.

**Comment by GoranM** [comment]
I don't know why we're conflating the vertex array with the index array. These are two different data sources, in both opengl, and in the libgdx api that abstracts opengl. I don't see a reason to change anything relating to indices, as the goal here (if I understood it correctly) is to modify vertex data, not index data.

I think `numVertices()` returning a number of floats in the vertex array is confusing, but also, at this point, I'm not really sure if `vertexArraySize()` would make more sense, as that typically implies a size in bytes, not floats. Maybe `vertexArrayFloatCount` would be a more sensible name, and then `numVertices()` would return `vertexArrayFloatCount() / VERT_FLOAT_COUNT`.

**Comment by rafcolson** [comment]
How about `Mesh.vertexArrayLength()`? Sounds a bit less extensive.

**Comment by GoranM** [comment]
Yeah, I guess that would be fine, since "vertexArray" is common opengl terminology that would imply floats.

**Comment by rafcolson** [comment]
Ok. Then the PR is ready to be merged. Thanks.

**Comment by rafcolson** [comment]
@SolarLune Just reminding that this can be closed now.

**Comment by SolarLune** [comment]
Oh, OK, cool. Thanks!
