### ISSUE TITLE
JSONValues are shared across instance properties

### ISSUE THREAD

**Issue by SolarLune** [GoranM/bdx#1008]
Hey, there. So I found a bug - basically, the actual JSONValues holding property values are shared amongst instances. Not sure quite how to proceed - one approach might be to take out JSONValues altogether and just have a HashMap of String to Object, perhaps with something to convert between formats, like JSONValue works. Or, maybe we just create new JSONValues for each GameObject.

Here's a blend that shows the issue. You press space to change a property on one cube, and the properties on all cubes get changed.

https://www.dropbox.com/s/zkparw5jztnar3n/InstancePropIssues.blend?dl=0

**Comment by SolarLune** [comment]
PR submitted for a fix.

**Comment by rafcolson** [comment]
Haha, to be honest I had hoped to have done more on my end.

First, I should point out that we're not supposed to modify props. There was a discussion about this [here](https://github.com/GoranM/bdx/issues/62#issuecomment-70395422).

About the actual issue, I remember that which you are describing as a bug, actually is intended behavior, which you were looking for [here](https://github.com/GoranM/bdx/issues/100#issuecomment-71796936).

Also notice that only the properties of the "original" object are shared. Properties of the instances themselves are not, except when one of those properties has the same name as one of the properties of the "original".

Why would you need to set GameObject properties? Is it so you could utilize properties instead of variables in a class, in order not to have a class for instances?

**Comment by SolarLune** [comment]
> Is it so you could utilize properties instead of variables in a class, in order not to have a class for instances?

Yeah, basically.

> So the question here is, do we want to be able to modify GameObject.props at runtime?

I don't know - my current use case is with an enemy that has an `enemy` property, that indicates that it kills the player on touch. If the enemy is stunned, then that property can be set to false - otherwise, it's true. So this is boiled down to, if the player touches anything with a `true` enemy property, then it dies. This only works, though, if enemies don't share properties.

We've already changed properties once before to ensure that copies of objects don't all have the same references to their properties hashmap. You can see this in Goran's comment [here](https://github.com/GoranM/bdx/pull/113#issuecomment-71738003 ). It seems like following this line of reasoning to extend to not copying JSONValue references would be logical.

**Comment by rafcolson** [comment]
I don't mind of course. I also would find it useful to be able to edit properties.

**Comment by GoranM** [comment]
The need for this seems to be driven by a programming approach that's at odds with Java's fundamental constructs, and its core methodology for building sensible systems.

As far as I can tell, it's not a better approach:

Beyond resource matters, like wasting memory, and wasting cycles, there are also overall understandability issues, where, apparently, an enemy stops being an enemy because it's stunned ... Or where cramming all behavior in a single class, and dispatching based on properties, is somehow better than having a class for each logical object.

If you guys really want this, then I'm ok with merging whatever you deem necessary (in this context), but I just want to make it clear that my willingness to do so is not an endorsement of the underlying programming approach used to justify such changes.

**Comment by SolarLune** [comment]
My use case is easy to change to better accommodate how BDX can and does work, so I wouldn't look at it as an indication of how to proceed. However, there is some utility in being able to examine the properties of the other object - of asking "does this other object have this ability / property". That's something that can be done using casting with classes or interfaces, or with BDX Components. It's also something that could be done by examining properties of GameObjects.

> where, apparently, an enemy stops being an enemy because it's stunned

One could say that an enemy is always an enemy because of the presence of the `enemy` property, and the boolean value designates whether it's dangerous or not. Or, you could give it a constant `true` for its `enemy` property and add a `dangerous` property that has an on or off boolean value depending on whether the enemy is stunned or not. You could also just add or remove the `dangerous` property depending on whether the enemy's stunned or not (which is how I've done this sort of thing before), but that's a waste of memory.

> Or where cramming all behavior in a single class, and dispatching based on properties, is somehow better than having a class for each logical object.

I'm going to have multiple kinds of enemies, so having multiple classes would be wasteful, since that'd mean multiple class casting checks. Having them all inherit from a basic Enemy class would work, but that could also be wasteful if there's objects that aren't "living" that could still be dangerous, like spikes, bottomless pits, etc. Similarly so if I use interfaces, since now anything that's dangerous would need to implement very basic code that basically says that it is, indeed, dangerous. 

Also, on cramming behavior in a single class, sometimes the difference between two distinct game objects is indeed just a single property - whether you can jump on this object or not, whether it explodes after death or not, etc.

> at odds with Java's fundamental constructs

How so? We're not adding anything that Java doesn't fundamentally support, or trying to bypass existing Java mechanics - I'm just examining objects to see if a string exists in their hashmaps, basically.

_____

I'm on the fence about this entire thing as it is. For my project, it's very easy to change around how things work, so it's not a huge deal. But, if we're going to have properties, I feel like we should probably make them "entirely usable", and not weaken their usage by default. Or, we could just document to remove and re-add a property if you plan to edit it in-place.

**Comment by rafcolson** [comment]
>If you guys really want this, then I'm ok with merging whatever you deem necessary (in this context), but I just want to make it clear that my willingness to do so is not an endorsement of the underlying programming approach used to justify such changes.

I agree that editing `GameObject.props` while using new classes, would be a bad programming approach. I was seeing some benefits with class-less objects, for the reason that I'm preferring not to write a class just for the sake of adding variables to an object. But thinking about it some more, I can't think of any cases where all enemies wouldn't be having basic variables to indicate damage or health (or life for that matter).

For example, the conventional method to attack the cactus would be:
```java
	if (Cactus.class.isInstance(g)){
		Cactus c = (Cactus)g;
		c.health -= damage;
		if (c.health <= 0){
			c.end();
		}	
	}
```
This would require `Cactus.java`:
```java
package yourPackage;

import com.nilunder.bdx.*;

public class Cactus extends GameObject{
	public int health;
	public int damage;
	
	public void init(){
		health = props.get("health").asInt();
		damage = props.get("damage").asInt();
	}
}
```
This wouldn't be necessary with the unconventional method:
```java
	JsonValue health = g.props.get("health");
	if (health != null){
		int h = health.asInt() - damage;
		if (h > 0){
			g.props.put("health", new JsonValue(h));
		}else{
			g.end();
		}
	}
```
However, the `Cactus.java` class could be `Enemy.java` for cacti, as well as the base class for more advanced enemies. So, I'd probably never use the unconventional method.

>Or, we could just document to remove and re-add a property if you plan to edit it in-place.

I wouldn't do that, because as far as I understand, that would be endorsing a programming approach which @GoranM doesn't want to endorse.

**Comment by GoranM** [comment]
> One could say that an enemy is always an enemy because of the presence of the enemy property, and the boolean value designates whether it's dangerous or not.

The fact that one would have to say that, in order to clear up the confusing notion that "enemy=false" does not actually mean "not an enemy" ... I think that kinda reinforces my original point.

> How so? We're not adding anything that Java doesn't fundamentally support, or trying to bypass existing Java mechanics - I'm just examining objects to see if a string exists in their hashmaps, basically.

In Java, and most other OOP languages, classes are the core construct used to define different kinds of objects, with their own set of associated behaviors. The whole language was designed with that methodology in mind. So, if you're essentially trying to replace the existing utility of the constructs already in the language, with some ad-hoc type system encoded in properties (which seems to be the case), I think that would support my previous claim.

Fundamentally, I don't think that "not having to write a class" is a clear benefit, especially when you're replacing the utility of a class with systems that are ultimately more convoluted.

----

> I wouldn't do that, because as far as I understand, that would be endorsing a programming approach which @GoranM doesn't want to endorse.

As with code, the documentation doesn't need to be a reflection of what I would personally endorse. If that's what you guys want to do, that's fine - It's your decision, and it can stand independent from my opinion in this thread.

Relating to your example: note that "Cactus" is very specific, so, unless there was some data and/or behavior that's really specific to a cactus, there would probably be no need to write a "Cactus" class, because it could just be an instance of something more generic.

**Comment by rafcolson** [comment]
>Relating to your example: note that "Cactus" is very specific, so, unless there  was some data and/or behavior that's really specific to a cactus, there would probably be no need to write a "Cactus" class, because it could just be an instance of something more generic.

Yes, indeed. As I was saying the `Enemy.java` would replace `Cactus.java` an be the base class for more advanced enemies.

**Comment by SolarLune** [comment]
> The fact that one would have to say that, in order to clear up the confusing notion that "enemy=false" does not actually mean "not an enemy" ... I think that kinda reinforces my original point.

That seems natural, though - why would things that aren't enemies have an enemy property at all? I'm not saying you're wrong, just that it's an alternate way of thinking about things. If the presence of a variable can mean something, then the state of that variable could then serve yet another purpose. It saves memory, and is just fundamentally about reuse where possible.

But again, it's not really a huge deal to me. I'll just document not to directly set properties present in the GameObject, since these are shared between instances by default to save on memory.

Thanks.

**Comment by GoranM** [comment]
> As I was saying the Enemy.java would replace Cactus.java an be the base class for more advanced enemies.

Oh, I missed that somehow ... Sorry about that.

---

> That seems natural, though - why would things that aren't enemies have an enemy property at all?

As far as I understood your use case, you were talking about things that are enemies, but that are just temporarily unable to attack the player.

A stunned enemy is still an enemy.

**Comment by SolarLune** [comment]
> As far as I understood your use case, you were talking about things that are enemies, but that are just temporarily unable to attack the player.
> A stunned enemy is still an enemy.

Yeah, that's why it would still have an enemy property, haha.

**Comment by rafcolson** [comment]
>But again, it's not really a huge deal to me. I'll just document not to directly set properties loaded into the GameObject from Blender, since these are shared between instances by default to save on memory.

Except for those properties which are on the instances themselves. So the "original" would have the "Enemy" property. And some of the instances could have properties such as "Health" and "Damage" and "Active", which can be modified locally.

**Comment by SolarLune** [comment]
That's true, but the developer can just use the properties present on the instance as a jumping-off point, and store the values in local variables present in the class itself.

**Comment by GoranM** [comment]
> Yeah, that's why it would still have an enemy property, haha.

As I said before: The fact that the enemy property can be set to false, but doesn't actually mean "not an enemy", is confusing.

However, that wasn't really the core of my argument. The core of my argument was/is:

> Fundamentally, I don't think that "not having to write a class" is a clear benefit, especially when you're replacing the utility of a class with systems that are ultimately more convoluted.

**Comment by SolarLune** [comment]
> As I said before: The fact that the enemy property can be set to false, but doesn't actually mean "not an enemy", is confusing.

OK, but you're not making the game, haha. What you and I find confusing can be different things. This is basically just a matter of personal preference. Regardless, I'm not using an alterable `enemy` property anymore in the project, so it's no big deal.

> Fundamentally, I don't think that "not having to write a class" is a clear benefit, especially when you're replacing the utility of a class with systems that are ultimately more convoluted.

I think it's a benefit when you're talking about objects that have no merit in being a class. If something can do damage, but doesn't need to be directly interacted with, animated, or altered at all (like spikes or a bottomless pit), then there's no reason to waste effort on creating and casting classes, as those objects don't need them. 

As to their name, properties can be used to purely give a certain property to a GameObject.
