### ISSUE TITLE
Suggestion: LinkedListGameObject & move Scene group methods

### ISSUE THREAD

**Issue by rafcolson** [GoranM/bdx#1026]
Thinking about #1023 and #1024 some more, it seems that the "group" methods in `Scene` are more or less similar to the `getObjectsByProperty` and `getObjectsByComponent` methods of `ArrayListGameObject`. So I was thinking to move those to `ArrayListGameObject`. That's to say, if `Scene.objects` would be an `ArrayListGameObject` instead of a `LinkedListNamed<GameObject>`. Was there a particular reason to make `Scene.objects` a linked list?

If so, why not have a `LinkedListGameObject`, as a "linked" variant of `ArrayListGameObject`? Maybe this would be the best thing to do either way, so current projects wouldn't brake. (See for example [getFirst()](https://docs.oracle.com/javase/7/docs/api/java/util/LinkedList.html)).

**Comment by GoranM** [comment]
> Was there a particular reason to make Scene.objects a linked list?

Removing an object from a linked list is basically a constant time operation, because it's just a matter of setting the "next" reference of the preceding object to the one that immediately follows the object to be removed:

```java
// A -> B -> C -> ...
A.next = B.next
// A -> C -> ...
```

Contiguous arrays, on the other hand, require "copying down" all the objects after the target:

```java
// arr = [A, B, C, ...]
for (int i = 1; i < arr.length - 1; ++i){
    arr[i] = arr[i+1];
}
// [A, C, ...]
```

So, since the objects list could get quite long, and people would want to frequently add and remove game objects, a linked list seemed like the better choice.

> If so, why not have a LinkedListGameObject, as a "linked" variant of ArrayListGameObject? 

Yeah, that would be fine.

**Comment by rafcolson** [comment]
>Contiguous arrays, on the other hand, require "copying down" all the objects after the target

Oh, okay, that's why. Thanks for explaining.

A PR is submitted.

**Comment by rafcolson** [comment]
PR merged. Thanks.
