### ISSUE TITLE
Optimization: preserving linked duplicates

### ISSUE THREAD

**Issue by rafcolson** [GoranM/bdx#109]
Hi,

When looking at [```Scene.init()```](https://github.com/rafcolson/bdx/blob/master/src/com/nilunder/bdx/Scene.java#L91) I noticed that a new ```modelInstance``` is made for each template, regardless whether the template itself is a linked duplicate.

So suppose in Blender I have two Cubes in my scene, both sharing the same mesh, they will have unique meshes in BDX whatsoever. A simple test showed that they have.

This somehow renders the ability to have linked duplicates useless. So I think it would be better to give  linked duplicates the same ```modelInstance```.

What do you guys think?

**Comment by SolarLune** [comment]
I think that makes sense, and seems like a good optimization (considering how many objects can be linked duplicates in a practical situation).

**Comment by GoranM** [comment]
> So suppose in Blender I have two Cubes in my scene, both sharing the same mesh, they will have unique meshes in BDX whatsoever. A simple test showed that they have.

How did you test?

A blender mesh corresponds to a libgdx Model, so objects that have the same mesh will have modelInstances that reference the same Model, meaning that all those instances will use the same mesh data (the modelInstance needs to be different, because different objects can have a different transform - position/orientation - even when they have the same mesh).

Even if all instance templates used different mesh data, it probably wouldn't matter, because they're never actually spawned into the BDX game-space; they simply serve as placeholders for real objects that are ultimately spawned into the scene.

**Comment by rafcolson** [comment]
A ModelInstance is more then just a mesh, so it seems. It also handles the visual representation of the mesh. So I think this is a dead end.

**Comment by GoranM** [comment]
> A ModelInstance is more then just a mesh

It's not a mesh - It just references a mesh.

**Comment by rafcolson** [comment]
But doesn't it also make the mesh unique? Transforming the ModelInstance will not transform the mesh, will it?

**Comment by GoranM** [comment]
> But doesn't it also make the mesh unique?

As far as I know, it doesn't.

> Transforming the ModelInstance will not transform the mesh, will it?

I don't know what you mean by "transform the mesh" - The transform is a not related to mesh data, so you can have multiple transforms applied to the same mesh, to produce a rendering of the same object in different places, different orientations, and at different scales.

**Comment by rafcolson** [comment]
>I don't know what you mean by "transform the mesh" - The transform is a not related to mesh data, so you can have multiple transforms applied to the same mesh, to produce a rendering of the same object in different places, different orientations, and at different scales.

Yes, that's what I meant. Thanks for confirming that.
