### ISSUE TITLE
Don't run main() for invalid objects

### ISSUE THREAD

**Issue by SolarLune** [GoranM/bdx#125]
Hey, there. So I'm trying to debug a behavior that appears every so often with my game, and I think I might have it down. It has to do with the order of execution - I end an object remotely, but it still gets its main() function run, thereby causing the problem I'm seeing. 

Anyway, it appears to be possible for a game object's main() function to be run even though it's been ended. The object remains in the objects list, and the objects in the `toBeRemoved` list only get actually removed after being updated. 

I think a possible solution would be to:

* Remove objects immediately instead of doing it in a group with the `toBeRemoved` list (probably slower), or
* Just not run main() on objects that have been invalidated (seems like a simple and easy solution).

**Comment by rafcolson** [comment]
> The object remains in the objects list

This is unwanted behavior. What I don't understand is why objects aren't removed immediately. Is this slowing down everything else so much?

**Comment by SolarLune** [comment]
I dunno. Removing an object from a list might be a performance concern, since the list has to shuffle things around depending on the object's position in the list. I guess that concern would become greater with more frequent end() calls and a larger objects list (which can, as I'm sure you know, easily grow into the hundreds or even thousands in size).

**Comment by GoranM** [comment]
> why objects aren't removed immediately

Because that would throw a ConcurrentModificationException; We iterate through scene.objects to run the logic, so we can't directly alter scene.objects during that time, because that would invalidate the iteration.

> Removing an object from a list might be a performance concern, since the list has to shuffle things around depending on the removed object's position in the list.

Scene.objects is a LinkedList, so removing any given GameObject would simply set the "next" reference on the previous node, to point at the node that should come next:

```
A -> B -> C -> ...
// remove B
A ------> C -> ...
```

No need to shuffle things around: removal is an O(1) operation.

Anyway, we could put this in the loop that runs the logic:

```java
if (g.valid())
    continue;
```

It will cost some performance (every branch does), but that should solve the problem at hand.

**Comment by SolarLune** [comment]
Ah, I see; I suppose that does make sense. 

PR submitted.

**Comment by SolarLune** [comment]
PR merged. Thanks. Issue's closed.
