### ISSUE TITLE
Moving static objects messes up collision

### ISSUE THREAD

**Issue by SolarLune** [GoranM/bdx#135]
Hey, there. So if you move static objects, it messes up their collision mesh somehow in a way that makes collision unreliable from that point on. Might be the objects going to sleep after some time... Maybe the static objects themselves go to sleep and aren't getting woken up or something, even on collision with other objects? It seems like the issue goes away if the static object moves fast enough.

If that's the case, it might be worth it to check to see if a game object is changed in position, rotation, or scale and to wake its physics body up (in the scene itself, since this could happen even on a "non-active", un-programmed game object).

Anyway, here's a test blend file. You can see the right-most "Sacky" object completely and totally fall through the static moving object, and the second "Sacky" and red cube (rigid body) completely stall in the air a few seconds in.

https://app.box.com/s/z84103m6vwmz9rq4zo3y1fv0xs4e5i5i

**Comment by rafcolson** [comment]
Yes, that's strange. I the "C" moves a bit faster, it won't stall.

**Comment by SolarLune** [comment]
Yeah, I think it's the Bullet sleep timer messing with stuff (I'm guessing we're not waking static bodies up when they move).

**Comment by GoranM** [comment]
Non-static objects start "sleeping" after some time, when resting on a static object, so unless they're kept active, they will just freeze at some point.

The fall-through seems to happen because the aabbs for a static object are not updated reliably, so it's something that has to be done manually at some interval.

I'm not exactly clear on the details here, because if you just set platform position from some distance, to be directly under falling objects, they will collide, even if the bounding box is not updated, so I assume it's some sort of compounding degradation problem, but I honestly don't know.

Anyway, for now, simply updating aabbs, and keeping all touching objects active, while the static object is moving, seems to resolve the immediately obvious issue.

**Comment by SolarLune** [comment]
That seems to fix the test case, yeah. Thanks for the fix! issue closed.
