### ISSUE TITLE
Issue with forking

### ISSUE THREAD

**Issue by rafcolson** [GoranM/bdx#138]
I'm sorry, Goran. I probably did something wrong so something has changed at your master branch. I never thought this was possible! I was experimenting with the git shell to figure out how I could sync my own master branch with yours, without having to pull a request. (If I do that, the merged commit of that pull request would be added to any pull request I did at your master). Now there's this annoying reminder "rafcolson committed 17 minutes ago" beneath your name.

Please, forgive me for my stupidity. And if there's anything I could do to fix it, let me know.

**Comment by SolarLune** [comment]
Yeah, I think we have access to commit under Goran's BDX fork here since we're contributors. I'm sure it's no big deal; don't worry about it.

For syncing your master branch with Goran's main one, check this out:

https://help.github.com/articles/merging-an-upstream-repository-into-your-fork/

I use TortoiseGit, so it boiled down to adding Goran's BDX branch here as an "upstream" branch, and then using "Pull > Upstream" in the context menu for the BDX folder. Once you do that, you can push the current, updated master branch to your own master branch of your Github BDX repo (using the Push menu option). Basing your experimental forks off of that allows you to base them off of up-to-date software and easily switch between them.

**Comment by rafcolson** [comment]
>Yeah, I think we have access to commit under Goran's BDX fork here since we're contributors.

But what did I commit? It seems that I committed something, but I can't figure out what. That's what's troubling me so much, because what if I messed something up?

Thanks for the info.

**Comment by SolarLune** [comment]
Looks like your fork is behind because you're missing your gravity() change and Goran's static movement object commit, and I'm guessing you committed that gravity function change to Goran's BDX branch.

You might want to confirm your local master branch is set to your BDX fork, and not Goran's.

**Comment by rafcolson** [comment]
And how do I confirm that?

**Comment by SolarLune** [comment]
Y'know, let's just wait for Goran, haha.

**Comment by rafcolson** [comment]
:) You can laugh, I can't (so much)

**Comment by rafcolson** [comment]
I think (I hope!) everything is alright now...

**Comment by GoranM** [comment]
I didn't know that collaborators were allowed to push to my repo, but that seems to be the case, and there's no way to change that (on a regular user account, at least), other than revoking collaborator status.

Needless to say, I'll have to be a little more discriminating in the future, about who I add to the collaborators list.

As for you guys:

@SolarLune - You seem to understand git well enough, and to be generally careful enough not to make these mistakes in the first place, so I think it's fine to leave you with this (much higher) level of access.

@rafcolson - In this case, this was easy to fix, because there's not that many developers, and I can simply force push my local master without breaking other people's work. However, in the future, that may change, and mistakes like these will have potential to cause significant problems for everyone. I'm ok with keeping you on as a collaborator, for now, but if this happens again, I will have to remove you from the collaborators list.

... Or, maybe it would be best to just remove you both from the collaborators list? I mean, it's not going to impede your ability to contribute to the project - You just won't be able to assign yourself to any given issue (I won't be able to assign you either), but that's fine, since you can just say that you want to work on something in the comments, and you can easily "summon" any user via `@UserName`.

**Comment by SolarLune** [comment]
That's fine on my end; feel free to revoke access. Being a collaborator makes me want to commit code directly to projects using PRs, haha.

**Comment by rafcolson** [comment]
@GoranM I'm very glad that you could fix it easily. And I'm so sorry this happened. I don't mind being removed from the collaborators list. You have to know that this all happened because I changed my remote origin (push) to your master. I did so unknowingly. I now know that I won't be making that mistake again, but it's up to you.

**Comment by GoranM** [comment]
> Being a collaborator makes me want to commit code directly to projects using PRs, haha.

Well, you wouldn't even need a PR, you could just push directly upstream.

It would probably be very tempting, at some point. :)

> You have to know that this all happened because I changed my remote origin (push) to your master.

That would be my guess.

Unless you make the remote explicit in the push, it uses origin, but if you redefined origin to point to my repo, it would push there.

Instead of redefining origin, it would be best to create an upstream remote:

```
git remote add upstream https://github.com/GoranM/bdx.git
```

Then to update your master (assuming you're on master):

```
git pull upstream
```

The push should still default to your origin, which should reference your github fork.

Anyway: I'm removing both you and SolarLune from the collaborators list - It's just easier that way (you won't have to worry about breaking the main repo, and I won't have to worry about fixing it), and it won't impede the development process, as I said.

> If I'm removed, I hope I could still edit the API if needed though.

Anyone with a github account can modify the wiki; they don't have to be a collaborator, so there's no problem there.

**Comment by rafcolson** [comment]
Thanks. I noticed that creating an upstream remote isn't even necessary as when I do ```git remote -v``` it shows your url for upstream both fetch and push. And this is after I just had made a fork.

@SolarLune I know you it's fine on your end, but I still want to apologize that by my doing you are removed too.

**Comment by GoranM** [comment]
You can have many remotes, but the one your branch is tracking will be the push target (I think).

To check which remote your branch is tracking, you can do `git branch -vv`.

Anyway, you don't need to apologize to anyone. Actually, now that I think about it, I would say that your error was quite fortunate: You demonstrated that collaborators have write access (which I didn't know), and you did so early enough to help me avoid more severe consequences in the future, without causing any great trouble.

So, overall, I think this was a good thing.

**Comment by rafcolson** [comment]
Maybe it was. Let me just say I'm thankful I can take part in the project.  Sheers.
