### ISSUE TITLE
Folder button

### ISSUE THREAD

**Issue by Nananas** [GoranM/bdx#146]
It would be nice to have an additional `Folder` or `Project Folder` button, that opens the folder of the project (duh).

**Comment by GoranM** [comment]
It may seem obvious to you, but you'll still need to explain why this would be necessary/useful.

**Comment by Nananas** [comment]
Right. Well, first of all, a bdx project consists of more then just the .blend file. Some people might get the impression that blender is doing all the work. It's like a "link" between blender and Java. Just a thought :baby_chick:

Also, when opening a bdx project, I mostly open the blend file through the `most recent` in Blender. To open the first asset/script/project file thingy for an IDE if you use one/... I have to navigate manually to the project folder, which is a tiny bit annoying. :sweat_smile:

This can obviously be different when you start off from the project folder in the first place. 
Or if blender already has a similar function, which I'm unaware of. In that case, you can just ignore everything.

**Comment by rafcolson** [comment]
>This can obviously be different when you start off from the project folder in the first place.

I organize everything from the explorer, because there are several folders containing relevant information about the project. So I just make shortcuts in the same folder were I put my project (assets, blend, java) and also shortcuts to the Command Prompt for exporting to Android in a mouse click.

I thought of making a tutorial about organizing a BDX project, maybe that could be useful. Anyway, I don't see any use in having a button in Blender for the simple reason that you'd still be several mouse clicks away from the folder you need. And, you can't manage anything within Blender itself, so it would be pretty much useless. The only thing you could do is add a folder. Assets and (external) Java files wouldn't normally be edited in Blender.

**Comment by GoranM** [comment]
I would agree with Raf.

**Comment by Nananas** [comment]
Okie, the only advantage would be these few clicks anyway. I'll close this then.
