### ISSUE TITLE
Error: BDX doesn't support scene names with spaces in them

### ISSUE THREAD

**Issue by SolarLune** [GoranM/bdx#155]
While I would call this a bug, I'm not sure if there's much that can be done to fix it. It would appear that BDX doesn't support scene names with spaces in them, as the instantiation process doesn't support it (each scene gets a generated class name, it would seem).

**Comment by GoranM** [comment]
> each scene gets a generated class name, it would seem

Yes, the instantiator for each scene is simply a generated java class with the same name, so, for the moment, you can't have scenes with names that don't represent a valid java class name.

We could run instantiator names through a filter, that would produce valid java class names by replacing troublesome characters (like spaces) with a marker that incorporates their ordinal value:

```
"Blah Scene" -> "Blahxx32xxScene.java"
```

It's not a perfect solution, because someone could also have a scene named "Blahxx32xxScene", in addition, but it seems highly unlikely.

**Comment by SolarLune** [comment]
It could also replace spaces with underscores, or any other character. We could also just keep it like it is and make a note that scene names can't have spaces. Up to you!

**Comment by GoranM** [comment]
> It could also replace spaces with underscores, or any other character.

There are also other problematic characters, like dot `.`, so you can't just replace everything with underscore, because then "Scene 001" and Scene.001" would both resolve to the same instantiator ("Scene_001").

**Comment by SolarLune** [comment]
^ Yeah, I was thinking of that with actual underscores as well ("Scene 2" and "Scene_2"). Just saying that special characters aren't supported for scene names might be the best route.

**Comment by GoranM** [comment]
This seems to work fine.

**Comment by SolarLune** [comment]
Cool, I'll close this then.
