### ISSUE TITLE
Scene event hooks

### ISSUE THREAD

**Issue by Nananas** [GoranM/bdx#157]
Currently, to run a script at startup, you have to put `init_` in front of the name, right?

But there is no `end` script.

A dev might want to modify some scene functionality. Because a scene is generated, afaik it is not possible to extend a scene **easily** *. Making some sort of controller object might solve some problems, but I find that method a little odd (and a bit too Unity-like :speak_no_evil:)

What I would like to see is a way to hook scripts on/in those events. Init, destroy, restart, pause ...

For example: closing a connection to a server/saving data before the game quits.

* if you know an easy way to do this, please ignore the rest of my post. :innocent:

**Comment by GoranM** [comment]
> Currently, to run a script at startup, you have to put init_ in front of the name, right?

An object whose name starts with "init_" will be initialized first, and it will also be processed first in the logic execution loop.

> Because a scene is generated

Scene data is generated, along with relevant instantiators, but there is only one Scene class that loads that data, and that class can be extended. 

Although, I think it's unlikely that you'll need to extend it, because the events you mentioned are triggered by user code, so you can just run the required code at those trigger-points.

> closing a connection to a server/saving data before the game quits

When you quit game, system resources are reclaimed by the OS, and I'm pretty sure that includes ports, so I don't think it's something that you would even need to worry about (in that case).

**Comment by Nananas** [comment]
> When you quit game, system resources are reclaimed by the OS, and I'm pretty sure that includes ports, so I don't think it's something that you would even need to worry about (in that case).

But I worry about server-side connections etc. My point is not those connections, my points is that one would like to do some cleanup when the game quits. Currently this is impossible?

**Comment by GoranM** [comment]
> But I worry about server-side connections etc.

Server should have a time-out that will automatically close inactive connections - You will need that either way, because clients can crash, and they won't be able to close those connections.

> My point is not those connections, my points is that one would like to do some cleanup when the game quits. Currently this is impossible?

What exactly do you mean by "cleanup"?

Generally, there's no need to cleanup anything for a process that's closing - the OS takes care of that.

**Comment by Nananas** [comment]
Ok, forget the example about connections :see_no_evil:.

With cleanup I mean nothing low level, handled by the OS. 
Have you never had a situation where the code had to do something right before the game quits?

Or maybe this is just bad programming from my part... :innocent:

**Comment by SolarLune** [comment]
Something that might need to be done before the game quits is auto-saving of the game state, or saving game settings, or a lot of things.

I could definitely see the use for scene hooks; sometimes you might want to do things before the scene exits. Another, similar, example would be saving information to have persistent scenes (talk to someone in scene 1, go to scene 2, go back to scene 1, they remember you). You could do this in the NPC itself at a base, but it might be simpler to do it all at once with the entire collection of characters that need saving.

A way to implement this (as passing function references just recently became possible, IIRC) would be to create a `Hooks` class and a member for it on each Scene. It would have the functions necessary, and the scene would call hooks through that class when necessary. You could subclass the `Hooks` class to create your own instance and then assign it to the Scene (either directly or through some kind of get/setHooks() function). So you could have:

`onUpdate()` - every game frame the scene updates
`onVisualUpdate()` - every game frame the scene visually updates and renders (after physics)
`onLogicUpdate()` - every game frame the scene logically updates
`onPhysicsUpdate()` - every game frame the physics in the scene updates
`onEnd()` - the game frame the scene is removed
`onGameObjectAdd()` - called when an object is added to the scene
`onInit()` - called when the scene is added to the game

... and so forth. These are just examples, of course.

**Comment by GoranM** [comment]
> Something that might need to be done before the game quits is auto-saving of the game state

You can save it when the player clicks the "QUIT" button. For a window close (clicking on the little X button in the corner), you would have to actually write a callback for libgdx (if I remember correctly), but, in either case, it's not something that would require a "hooks system".

>  you might want to do things before the scene exits

That's an action that your program would have to initiate either way, so there's already a place where that "exit code" can be called.

> Another, similar, example would be saving information to have persistent scenes (talk to someone in scene 1, go to scene 2, go back to scene 1, they remember you).

By default, all scenes retain their state. Just make sure to keep the reference to the old scene, and then add that back into Bdx.scenes, instead of creating a brand new scene.

**Comment by SolarLune** [comment]
> By default, all scenes retain their state. Just make sure to keep the reference to the old scene, and then add that back into Bdx.scenes, instead of creating a brand new scene.

Ah, that's right. That's definitely useful, though it might prove prohibitive for a lot of larger scenes. Thanks!

**Comment by SolarLune** [comment]
This was never looked into, and I think it's because we just don't really need it that much; maybe it'd be best to close it for now, and re-open if necessary in the future. Agreed, @Nananas?

**Comment by Nananas** [comment]
Sure, totally forgot this was still open.
