### ISSUE TITLE
Android Performance GL draw calls

### ISSUE THREAD

**Issue by rafcolson** [GoranM/bdx#164]
Hi,

So I thought of doing some further investigation on how to increase performance on Android.

I did some tests with ```com.badlogic.gdx.graphics.profiling.GLProfiler``` and it turns out that BDX is having one GL draw call for each modelInstance on every frame. Should we find a way to reduce the amount of draw calls drastically, because actually, with small games (which are especially the case on Android), only a little amount of draw calls would be enough to render hundreds of objects.

@GoranM Do you already know if this would be possible for BDX. There's no doubt this is a bottleneck.

Here's a [test blend](https://www.dropbox.com/s/wx9elvok1tdse81/Test_1024_cubes.blend?dl=0).

**Comment by rafcolson** [comment]
Merging dynamically should be one possible solution. Here's an interesting [article](http://www.badlogicgames.com/forum/viewtopic.php?f=11&t=10842&hilit=merge+3D&start=10) (see post at the bottom of the page).

**Comment by GoranM** [comment]
We use the libgdx rendering system, so if there are any optimizations to be made there, they need to be made in libgdx, not BDX.

**Comment by rafcolson** [comment]
The main question is: does LibGdx enable us to reduce the number of GL draw calls? And if so, should we take advantage of that? If not, should we provide some alternatives in the Wiki.

I'm sure a lot of game developers will be attracted to BDX because it ports to android too. But they will get disappointed if they'll see performance is (way) beneath their expectations.

So I started this Issue to think about solutions or alternatives. For example, if indeed "merging meshes" would be a solution, couldn't we provide that option in BDX?

**Comment by SolarLune** [comment]
@GoranM - I seem to recall your answer to this effect earlier. I haven't tried out Android yet, so I don't know myself, but are you basically saying that this is as good as performance could possibly get on Android under LibGDX? There's absolutely nothing that can be done on BDX's side to optimize rendering?

@rafcolson - Seems like a method to merge objects together to reduce draw calls would be effective and useful for both desktop and mobile platforms, if it does speed things up. The profiler should be indispensable now in helping us to identify slow portions of the engine and optimize them.

**Comment by GoranM** [comment]
> For example, if indeed "merging meshes" would be a solution, couldn't we add easy access for this in BDX? What I mean is functions that enable the user to easily merge meshes dynamically.

If that feature exists in libgdx, we could wrap it, however:

It doesn't seem like a general solution - For a racing game, it can be useful, but even then, you could just build the track out of larger pieces, instead of all those smaller elements, and then you wouldn't need to merge anything.

> are you basically saying that this is as good as performance could possibly get on Android under LibGDX? There's absolutely nothing that can be done on BDX's side to optimize rendering?

I'm saying that, if something could be done, to optimize libgdx 3D rendering, that patch would belong in the libgdx code base.

**Comment by SolarLune** [comment]
> If that feature exists in libgdx, we could wrap it, however.

That sounds like a good idea, if it exists in LibGDX.

> It doesn't seem like a general solution - For a racing game, it can be useful, but even then, you could just build the track out of larger pieces, instead of all those smaller elements, and then you wouldn't need to merge anything.

I'm not sure I understand what you mean. When constructing a level, you're probably going to use pieces of something. Merging these objects together after creation should be useful. It's not always possible to do this in the scene before the game is played, and it's not always possible to use "larger pieces".

> I'm saying that, if something could be done, to optimize libgdx 3D rendering, that patch would belong in the libgdx code base.

I'm not sure what you're talking about; it seems like Raco's question was and is essentially,  "The rendering process is too slow under Android. Can we optimize this?" 

So, what are the options? Obviously, we're not looking to do work on LibGDX, so what is able to be optimized (or expose to be optimized by the user) on the BDX side of things?

**Comment by GoranM** [comment]
> I'm not sure I understand what you mean. When constructing a level, you're probably going to use pieces of something. Merging these objects together after creation should be useful and good for reducing draw calls. It's not always possible to do this in the scene before the game is played, and it's not always possible to just use larger pieces.

I don't think it's always possible to just merge everything into one mesh. If this could be applied as a general optimization, I suspect it would already be done in libgdx.

That's what I meant by: "It doesn't seem like a general solution."

From what I understand, the referenced merging technique is basically good for scenarios where you're programmatically generating what could otherwise be simple static geometry, and since you can't make that into one object ahead of time, it helps to have a mechanism that can do that at run-time.

But it's a mechanism that you would have to guide yourself, with your own code - It's not something that can be applied as a general rendering optimization, as far as I understand.

If it could, it should be made in libgdx.

> I'm not sure what you're talking about; it seems like Raco's question was and is essentially, "The rendering process is too slow under Android. Can we optimize this?"

The actual rendering process is managed by libgdx, not BDX - We just create the model instances that are then rendered by the libgdx ModelBatch.

>So, what are the options? Obviously, we're not looking to do work on LibGDX, so what is able to be optimized (or expose to be optimized by the user) on the BDX side of things?

If there are things that could be done to optimize the libgdx rendering process, and we feel that those optimizations would be useful, why wouldn't we want to include them into libgdx?

Isn't that where they belong?

I don't know how much could be done on the BDX side, because, as I said, the actual rendering process is managed by libgdx.

**Comment by SolarLune** [comment]
OK, I think I see what you're saying. It seems like merging objects into a single mesh should be something available to the developer as an option, not automatically done (or any other rendering optimization, especially ones that destroy / alter existing meshes). If it were easy to do automatically and across-the-board for all cases, it'd probably be in LibGDX by now.

When I said "we're not looking to work on LibGDX", I meant that basically, we are BDX developers and contributors; it seems like we should focus on BDX development, not improving LibGDX. Working on LibGDX as a base seems like it should be a last resort, since it doesn't just concern us. It has its own developers, users, and goals. I'm sure it's being worked on to be as efficient as possible. 

Anyway, I apologize for getting the discussion off-track. Seems like the best course forward at the moment is to investigate mesh merging and see the effects with the profiler.

**Comment by GoranM** [comment]
> When I said "we're not looking to work on LibGDX", I meant that basically, we are BDX developers and contributors; it seems like we should focus on BDX development, not improving LibGDX. 

LibGDX is a core part of BDX; we should focus on solving problems where they actually reside.

> Working on LibGDX as a base seems like it should be a last resort, since it doesn't just concern us. It has its own developers, users, and goals. I'm sure it's being worked on to be as efficient as possible.

I don't see why it should be a last resort. I mean, if there are certain subsystem features that we want/need, but LibGDX doesn't support, our priority should be to get those features into the LibGDX code base.

If that's where they belong, architecturally, then that's probably where we can create the cleanest possible implementation.

Other options (assuming they exists) are likely to be more complex.

**Comment by rafcolson** [comment]
@GoranM On https://github.com/libgdx/libgdx/wiki/Meshes you can read:

>Especially on mobile platforms, there are significant performance gains in batching by reducing the overhead of individual draw calls.

So LibGdx batching would reduce the amount of draw calls. BDX uses only one modelBatch per scene, so then I wonder, are they talking about another kind of batching here? Since regardless of BDX having only one modelBatch per scene, the amount of draw calls still seem to be as high as can be. This is why I asked:

>Do you already know if this would be possible for BDX.

I assume there's maybe a bug with LibGdx then, since you are saying BDX is using the fastest technique possible (which turns out not being reducing any draw calls).

As an alternative I think merging meshes is a practical solution, and maybe the only one. This may not be a general solution. But at least it would enable the user to reduce draw calls with static meshes. For some game designs this could increase performance tremendously, for example, the one I was working on before.

@SolarLune 

What I meant was to have some helper functions in BDX for the user to be able to merge meshes. Of course the implementation wouldn't be to merge meshes on every frame, but to merge only one. For example with terrains with a lot of static objects (threes, bushes, flowers, houses, ...). As normally you would spawn in only sections of the terrain, you could merge every section to one object, reducing GL calls considerably. This is how I intended to use it.

I'll try to learn how to create such a function for BDX, but any help with this is appreciated. I think this will be a bit over my head, looking at the samples of code produced by people on the web. But it definitely will be something I need for my game. If this won't work, I'll have to have my own ```exporter.py``` with custom features to merge objects in Blender itself.

**Comment by GoranM** [comment]
> since you are saying BDX is using the fastest technique possible

I'm not saying that.

I said that BDX simply creates model instances that are rendered by the libgdx ModelBatch. I don't know if that's the "fastest possible" technique, but it seems to be the one that's used in virtually every libgdx example/tutorial, so that's what I used.

What ModelBatch actually does, on the lower level - I don't really know.

However, I think this is true:

For most game-types, you should be able to combine most static objects into only a few, at design time, and that would make merging at runtime unnecessary.

Therefore, I don't think this issue is as critical as the length of this thread implies.

> If this won't work, I'll have to have my own exporter.py with custom features to merge objects in Blender itself.

In Blender, you can just select objects you want to join, and then type Ctrl-J. That should give you one object.

I don't think you would need to modify the exporter.

**Comment by rafcolson** [comment]
>For most game-types, you should be able to combine most static objects into only a few, at design time, and that would make merging at runtime unnecessary.
>
>Therefore, I don't think this issue is as critical as the length of this thread implies.

I disagree. I believe this is and will be a critical issue with BDX on mobile devices for game developers.  Especially because they will always be in favor of dynamically generating scenes. This is so much more advantages: keeping apk's small in size (no huge merged objects), higher level of control over design and building structures and less time-consuming.

**Comment by SolarLune** [comment]
> For most game-types, you should be able to combine most static objects into only a few, at design time, and that would make merging at runtime unnecessary.

Yeah, that's an assumption that we can't make.

**Comment by GoranM** [comment]
> keeping apk's small in size

Anything that would require runtime mesh merging, in order to keep APK size acceptable, is not really in the category of games that BDX was designed to support -> small to medium size independent games.

> higher level of control over design and building structures and less time-consuming (essentially more freedom).

It takes considerable time to create a well tuned dynamic generation system, which can create environments that adhere to specific design principles - the ability to simply "merge meshes at runtime" doesn't do that for you.

Those kinds of games can be very complicated, technically, so I doubt that many independent developers would try to pursue those, even if BDX provided utilities to support them (performance-wise, on mobile).

That said:

If you want to work on this, I have nothing against that.

**Comment by rafcolson** [comment]
>Anything that would require runtime mesh merging, in order to keep APK size acceptable, is not really in the category of games that BDX was designed to support -> small to medium size independent games.

For my type of game, where everything consists out of ten thousands of blocks, I assure you the difference would be more than a couple of megabytes. And it's not a big game at all. Nothing fancy, no high detail, just a 2D platformer in the style of the old SEGA Genesis games.

>It takes considerable time to create a well tuned dynamic generation system, which can create environments that adhere to specific design principles - the ability to simply "merge meshes at runtime" doesn't do that for you.

I think such a well tuned dynamic generation system still requires many objects to be generated dynamically. So I don't see your point. You couldn't run it on android unless you find a way to decrease the number of draw calls.

>Those kinds of games can be very complicated, technically, so I doubt that many independent developers would try to pursue those, even if BDX provided utilities to support them (performance-wise, on mobile).

Those kinds of games can be very complicated indeed, but most of the time they wouldn't be, especially with indies. Spawning a number of blocks in order to generate levels should be straightforward most of the time. I'm sure that any independent game developer with a bit of experience would find such a technique to be very useful, if not to say indispensable.

I'll try to create a method to merge modelInstances. Thanks for letting me know that if I would succeed this could get in BDX.

Peace

**Comment by GoranM** [comment]
> where everything consists out of ten thousands of blocks

Does it really have to consist of that many blocks?

What are you trying to make?

> I think such a well tuned dynamic generation system still requires many objects to be generated dynamically. So I don't see your point.

It's not just a matter of merging meshes at runtime - you have to write a system that will do that in the right place, for the right objects, at the right time.

So as I said:

> Those kinds of games can be very complicated, technically, so I doubt that many independent developers would try to pursue those, even if BDX provided utilities to support them (performance-wise, on mobile).

In other words: I don't think that many independent developers would choose to develop games of that complexity, especially when one can make technically simpler games, with the same, if not an even higher potential for innovation.

In general, I don't want to focus on making BDX an engine for "minecraft-like" games, or anything that would require "ten thousands" of objects.

> Spawning a number of blocks in order to generate levels should be straightforward most of the time. I'm sure that any independent game developer with a bit of experience would find such a technique to be very useful, if not to say indispensable.

I think a developer, "with a bit of experience", would know about the high cost of even moderately higher complexity, and would therefore simply merge everything that should be merged at design time.

**Comment by rafcolson** [comment]
>In general, I don't want to focus on making BDX an engine for "minecraft-like" games, or anything that would require "ten thousands" of objects.

Well, I agree that my game would be more an exception to the rule. But to have more than a hundred objects is not so exceptional. Unfortunately this would already be a problem on mobile devices as was mentioned in Issue #53.

You won't say that you don't want to focus on making BDX an engine for anything that would require "more then a hundred" of objects, would you?

>I think a developer, "with a bit of experience", would know about the high cost of even moderately higher complexity, and would therefore simply merge everything that should be merged at design time.

How's to say? It all depends on what kind of project you're working on. And that would be my main point. It would be unfortunate if game developers wouldn't have the freedom to use basic techniques, such as dynamically generating scenes, with BDX for android. I'm just trying to fix that. And hopefully I can.

**Comment by GoranM** [comment]
> You won't say that you don't want to focus on making BDX an engine for anything that would require "more then a hundred" of objects, would you?

Actually, for mobile devices, I would be willing to say that.

> It would be unfortunate if game developers wouldn't have the freedom to use basic techniques, such as dynamically generating scenes, with BDX for android.

I don't think they're that "basic". As I said:

> It's not just a matter of merging meshes at runtime - you have to write a system that will do that in the right place, for the right objects, at the right time.

Games that truly require that, are games that fall into the "more technically involved" category, and supporting those kinds of games is very low on my priority list (if at all); I think that most (realistic) independent developers would focus on technically simpler projects, and proceed to innovate in different areas.

**Comment by rafcolson** [comment]
>Actually, for mobile devices, I would be willing to say that.

That surprises me. Anyway, thanks for having this conversation. If it's okay for you I'm closing this. I don't think I could add something more.

If I have finished a method for merging meshes, I'll open a new Issue. It then will up to you if you would want to merge it in or not.
