### ISSUE TITLE
Suggestion: Method to find component

### ISSUE THREAD

**Issue by SolarLune** [GoranM/bdx#168]
It might be a nice feature to add a method to find a type of component. You'd pass the class (or the class's name, I suppose) and the method would loop through the GameObject's components until it finds a component that extends that specified type, at which point it would return it. If it doesn't find anything, it would return null. I guess it would require a new type of ArrayList for components, and would be a "get()" function.

**Comment by GoranM** [comment]
Components were intended to serve as tools for internal organization, not as interface points for external access.

Internally, if one component depends on another, it would probably be best to make that dependence explicit:

```java
public ComponentA(GameObject g, ComponentB cb);
```

So, instead of having to call `g.components.get("ComponentB")`, or something like that, you can just use the reference directly.

Similarly, for external access, one could simply make the relevant references on the game object itself:

```java
public ComponentB compb;

public init(){
    compb = new ComponentB(this);
    components.add(compb);
}
```

That way, you can explicitly call `gobj.compb.whatever()`, instead of searching through components.

Although, I wouldn't really recommend exposing the component itself - If you want to define a certain behavior state for the game object, by manipulating certain components, you should have a game object method to do that.

This way, your borders between internal and external are well defined, and therefore easier to understand.

**Comment by SolarLune** [comment]
Hm, I suppose that makes sense. Thanks.

Issue closed.
