### ISSUE TITLE
Suggestion: SpriteAnim animation length function

### ISSUE THREAD

**Issue by SolarLune** [GoranM/bdx#178]
Hey, there. A function to return the length of a given animation would be nice to have.

**Comment by GoranM** [comment]
I guess, but I'm not sure if it would be wise to just continue adding SpriteAnim methods that relate to a specific animation sequence; Seems like it would be cleaner to just make active a public variable, and have users access that directly.

Since Animation inherits from ArrayList, users could just call size() to get the number of frames.

**Comment by SolarLune** [comment]
That's an OK approach, but the user might need to know the length of animations that aren't active, of course, like attacking or other timed animations. If you don't want to add additional methods (understandably), then maybe making it easier to directly store and keep track of animations (allowing use of other collections other than straight int[] arrays) would be good.

**Comment by GoranM** [comment]
We could also make the animations HashMap public, and then the user can get whichever Animation they need to inspect.

Animation inherits from ArrayList, as I said, so I don't see how a type used in SpriteAnim.add (which is just for sequence definition) relates to this.

**Comment by SolarLune** [comment]
Making the animations HashMap public sounds fine, yeah.

**Comment by GoranM** [comment]
Done.

Now that active and animations are public, I removed a few methods:

current() - Just use active.name directly.
onLastFrame() - Same for this: active.onLastFrame();
animationNames() - animations.keySet();

**Comment by SolarLune** [comment]
Cool, I'll close this. Thanks!
