### ISSUE TITLE
Suggestion: Random.random() With Argument

### ISSUE THREAD

**Issue by SolarLune** [GoranM/bdx#199]
Hey, there. In line with the Vector changes I suggested, it'd be nice if the random function took a couple of arguments (min and max, again). The default would just be like it works currently, and give 0 - 1.

**Comment by GoranM** [comment]
That sounds fine.

**Comment by SolarLune** [comment]
PR submitted.

**Comment by rafcolson** [comment]
Why would it be useful to have a method: ```direction(float min, float max)```, if I may ask? Isn't a random direction always  ```random(-1, 1)```

**Comment by SolarLune** [comment]
A random direction would be that, yes, but you can easily set the length with this to a random length between the minimum and maximum. I mean, it's a pretty self-explanatory function; the usefulness is up to the user of the function.

You could use it for placing objects in a circle in a range, or picking a random direction and speed to move in, or whatever.

**Comment by GoranM** [comment]
If you need a random direction vector with a random length between a given range, you could simply do: `Random.direction().mul(Random.random(min, max))`.

I guess one could make the argument that Random.direction(min, max) is more convenient, but I don't think that "random direction with random length between given range" is a common enough requirement to justify that addition.

Also, it's a bit confusing, because direction(min, max) doesn't really make it clear that min can't be negative, or that the method will do something sane (like clip to 0) if it is - You basically have to look at the implementation to be sure.

**Comment by SolarLune** [comment]
OK, just the random functions, then. PR updated.

**Comment by SolarLune** [comment]
Cool, this was merged. Issue closed.
