### ISSUE TITLE
Bug: Parenting Dynamic Objects

### ISSUE THREAD

**Issue by SolarLune** [GoranM/bdx#208]
Hey there. 

So if you parent a dynamic object to another object, it will start to shudder or move on its own. This will happen either from parenting in Blender or in BDX. It takes a few seconds to manifest itself; if you print out the velocity of the parented object, you can see it's still accumulating downward velocity. I take it it's because Bullet's still trying to simulate it, when it should rather be "locked" from the parenting.

A workaround seems to be to keep the parent active all of the time (parent.body.activate(true)). Any ideas for a different solution, though? I guess we could check to see if an object has a parent, and if so, set its movement and rotational speeds to 0 every frame? Should we also enforce ghosting if an object is parented, since it no longer has dynamics of its own?

**Comment by GoranM** [comment]
All collision-enabled objects are simulated by bullet, even when they have a parent.

`Scene.updateChildBodies()` is responsible for updating child transforms. Those updates only happen while the parent is active. When the parent becomes inactive (goes to sleep, in bullet terms), the transform updates stop, and there's nothing to keep the dynamic child in that specific position/orientation.

I wrote some code to make dynamic child objects static, for the duration of the parent-child relationship.

Give it a try.

> Should we also enforce ghosting if an object is parented, since it no longer has dynamics of its own?

I don't see how a lack of dynamics would automatically imply that user desires a ghost object, instead of simply a static object.

In general, I think the original user choice, made in blender (via the "Ghost" checkbox), or at runtime (via GameObject.ghost), should remain.

If objects added to a compound body need to be ghost, then it would make sense to override original user choice, for that specific circumstance, but not otherwise.

**Comment by SolarLune** [comment]
> Give it a try.

Cool, that fixed it.

> In general, I think the original user choice, made in blender (via the "Ghost" checkbox), or at runtime (via GameObject.ghost), should remain.

> If objects added to a compound body need to be ghost, then it would make sense to override original user choice, for that specific circumstance, but not otherwise.

Yeah, I suppose I agree. Setting the parented object to static is the logical choice, it seems. 

Thanks; issue solved and closed.
