### ISSUE TITLE
Bug: alignAxisToVec crashing

### ISSUE THREAD

**Issue by SolarLune** [GoranM/bdx#217]
Hey, there. So when I use alignAxisToVec with a number for the axis number, I get a crash:

```
Exception in thread "LWJGL Application" java.lang.StringIndexOutOfBoundsException: String index out of range: 89
        at java.lang.String.charAt(String.java:646)
        at com.nilunder.bdx.GameObject.alignAxisToVec(GameObject.java:528)
        at com.nilunder.bdx.GameObject.alignAxisToVec(GameObject.java:528)
        .......
```

The code itself is just this:

```java
RayHit ray = scene.ray(position(), new Vector3f(0, 0, -2));
if (ray != null) {		
	System.out.println("Aligned.");
	alignAxisToVec(1, ray.normal);
}
```

Not sure if I'm the only one who has this issue, though, so I dunno.

Also, for the string version of the axis functions (axis(), alignAxisToVect(), etc), it might be a good idea to convert the provided axis string to upper-case first before the function continues (since someone could use "y" instead of "Y", for example).

**Comment by GoranM** [comment]
@rafcolson 

I'm not sure, but I think you actually have to post in the thread for SolarLune to be notified.

Also, you should try to make your commit messages more descriptive in the future. Something like `alignAxisToVec: Convert char returned by charAt to String (#217)` would have been good.

> Also, for the string version of the axis functions (axis(), alignAxisToVect(), etc), it might be a good idea to convert the provided axis string to upper-case first before the function continues (since someone could use "y" instead of "Y", for example).

Reading code would be a bit confusing, because some people would use "Y", and others "y", and if you don't know the internals, you might think there's some significant distinction.

Users should use capitals, as documented - It would probably be a good idea to throw an exception for anything else.

**Comment by SolarLune** [comment]
I have it notify me when people make PRs or releases or issues or whatever, so I saw the fix. Thanks, @rafcolson. I can't test it now, though, because of that building issue.

**Comment by rafcolson** [comment]
>I have it notify me when people make PRs or releases or issues or whatever

Same here.

**Comment by GoranM** [comment]
Good to know.

**Comment by SolarLune** [comment]
Hey, I think that solved it, thanks.

Issue closed.
