### ISSUE TITLE
Project creation fails

### ISSUE THREAD

**Issue by milkotv** [GoranM/bdx#225]
Hi Goran.
First, thank you!
I am having the following issue with v.0.1.3: Creation of the a project complains (with a wide and distorted popup) that gdx-setup.jar returned non-zero status (2). Running gdx-setup from the command line works. The problem does not seem to be related to path with spaces as I tested it without spaces - same result.

Thanks
![bdxerror](https://cloud.githubusercontent.com/assets/11747258/6934090/2c2cc634-d7fd-11e4-95ad-c4552419d89b.png)

**Comment by GoranM** [comment]
> The problem does not seem to be related to path with spaces as I tested it without spaces - same result.

In that case, it might be a good idea to change the title of this issue - Because it has nothing to do with spaces, as you already established through testing.

I'm not really sure what the problem could be, because I can't see the complete error (things seem to cut-off a bit in your screenshot).

Does `C:\Temp` actually exist?

The screen shot of your command shell is using `D:\_Personal...` - Maybe you should try using that, since it seems to work when you create a project there.

**Comment by milkotv** [comment]
Hi Goran,
my bad about the title, should have changed it ...

The screenshot shows exactly what I am seeing - a *cut off popup with
distorted text*.
Yes, C:\Temp does exist. I did (carefully) try various paths with no luck.

Regards,
Milko

**Comment by GoranM** [comment]
> my bad about the title, should have changed it ...

You can do it now: Just click on the little Edit button next to the title, and change it to: "Project creation fails".

I've made a new release (0.1.4), so go ahead and [update](https://github.com/GoranM/bdx/wiki#updating-bdx). After you have the new version, try again - You'll probably still get an error of some-sort, but there may be additional information that will hint at the actual problem.

Don't take a screenshot of the popup - The error should be printed in the [console](http://wiki.blender.org/index.php/Doc:2.6/Manual/Interface/Window_system/Console_window), so copy that text (be sure to get all of it) and paste it here like this:

\`\`\`
text copied from console
\`\`\`

**Comment by milkotv** [comment]
Hi Goran
the problem was with the presence of JRE 1.7 together with JDK 1.8 on my machine.
All is working now.

Thank you for your support.
Milko
