### ISSUE TITLE
Physics Visualization

### ISSUE THREAD

**Issue by SolarLune** [GoranM/bdx#231]
Hey, there. Currently, I'm trying to figure out where a physics issue I'm having resides, and I'm having some trouble. I think at this point in BDX's development, a physics visualization would be really useful, both for bug tracking as well as actual game development.

**Comment by GoranM** [comment]
I had to actually muck around in gbullet, because like jbullet, it was missing a large part of the debug draw implementation: Someone basically just plopped the relevant C++ code as comments, and marked it as "TODO" (as can be seen [here](https://github.com/CasperPas/JBullet/blob/9bce4ed55c6eb19717c374cb791f3d0ce0dcdfab/src/com/bulletphysics/dynamics/DiscreteDynamicsWorld.java#L851)).

For the shapes that we currently support, it seems to work fine.

**Comment by SolarLune** [comment]
Whoa, this is great! Thanks a lot, this should prove really useful for diagnosing future physics problems.

And I saw that commented code in my traversal trying to do this myself, haha. Thanks again.
