### ISSUE TITLE
Bad Peformance with many scenes

### ISSUE THREAD

**Issue by moshme** [GoranM/bdx#262]
Hey Guys,

I just changed to the newest version of bdx. I didnt updated it for a long time, my last version was 0.8. In my code i use six different scenes for the levels. Only one is active while the others are paused. In the old version of BDX i had 60 fps. In the new my framerate dropped to 10-12 fps. A quick look at the differences of the codes, let me assume it is because in the newer version also the paused scenes  are rendered. which should not i think.

cheers mosh

**Comment by SolarLune** [comment]
Hello. A few points:

1. What OS are you developing on and using when testing?

2. This would be a bit of work, but it'd probably be advised to use the profiler (which would require that you create a new project) to profile where the slow-down is occurring. It might be something unrelated to multiple scenes.

3. Why do you have the scenes on and paused instead of just adding them in, one at a time, when you actually are going to play them? This seems like a poor design decision...?

4. As far as I know, there's nothing that changed in terms of rendering paused scenes in the code-base. In the time between version 0.08 and the current version of BDX, quite a bit has changed, including 2D filters being added. This being the case, framebuffers are used to make this possible, which might be the cause of the slow-down that you're experiencing. Again, profiling would be a way to confirm what the issue you're running into is.

Pausing scenes should have no impact on rendering them, as they're two different concepts (stopping execution of logic and physics vs. not drawing them). Games usually have an application for rendering paused scenes, as for most games when you pause, the game screen remains visible. 

As a side-note, a Scene.visible field might be nice to turn off entire scenes' visibility.

**Comment by moshme** [comment]
Hi, first of all thanks for the answer.

Here is the code of the old version (Not really sure if it was 0.8 but i think):
for (Scene s : (ArrayListNamed<Scene>)Bdx.scenes.clone()){
			s.update();
			if(!s.paused) renderScene(s);
}
I am not quite sure anymore why i choosed the pause concept, i think it was because i had trouble with adding and removing them and encountered then the possibility to pause them. I should check if i could do this with the new code base.

I think profiling is not really nessecesary because it is very obvious that rendering all six scenes at the same time will decrease the performace significantly. But when i have the time i will check the profiling option. But it wont be before saturday.

**Comment by GoranM** [comment]
As far as I can remember, we've never had an `if(!s.paused)` condition for rendering a scnee - It's possible (likely) that you added that, and then forgot about it.

If you need to remove a scene, simply remove it from the Bdx.scenes list. As long as you hold a reference to that scene, it will preserve its state, and you'll be able to add it back.

**Comment by moshme** [comment]
Yeah you are right, sounds logical. Its Strange how fast somone can forgot his own code and its meaning, at least so in my case. 

Sorry for my hasty reaction opening this issue and thanks for clearing me up.
