### ISSUE TITLE
Question: Add (proportional) BDXFont?

### ISSUE THREAD

**Issue by rafcolson** [GoranM/bdx#270]
Hello guys.

I've updated ```BDXFontMono``` which is being used for the profiler.

Now I also have the proportional variant ```BDXFont```. Is it okay to add this to the built-in fonts?

As a side-note:

The original versions of these fonts were made so they would have the correct spacing on other programs, such as Notepad++ and OpenOffice Writer. But I had to customize those in order to have the correct spacing between characters in BDX. This is also true for other fonts. You could even notice this with the built-in ```Bfont```. Some characters are a little off. Just so you would know, that if anyone would be using regular fonts, he'd probably be a little dissatisfied with the results in BDX.

Anyway, I'm not making an issue out of this, but if in the future the Text wrapper would be upgraded then you know I have those original versions waiting.

**Comment by rafcolson** [comment]
I noticed that not all the fonts of the ```hiero``` folder are accessible. ```BDXFontMono``` will only be accessible after enabling "Show Framerate and Profile" in the Blender Display options. ```BDXFont``` is not accessible whatsoever, because it isn't loaded anywhere. So how about adding this to the ```game.blend``` or ```profiler.blend```? I can't think of another way to make it accessible. Any ideas?

**Comment by GoranM** [comment]
I don't see the need to include yet another font.

For the profiler, it made sense, because a square, monospaced font makes the spacing consistent, and the text readable at various scales.

However, for all other purposes, I think it's best to leave font selection to the user: If they want to use a font other than the default (Bfont), they should simply include that in the .blend.

**Comment by rafcolson** [comment]
Okay. Thanks.
