### ISSUE TITLE
Suggestion: changes to Scene (adding & removing)

### ISSUE THREAD

**Issue by rafcolson** [GoranM/bdx#275]
>You should be able to "end" a scene by just removing it from the scenes list, right? No need for a specific function? Something to end the game sounds good, though.

Yes, it seems like it. But just for convenience sake I could add ```remove(String sceneName)```, because currently you have to get the scene or give the index: ```remove(int index)``` and ```remove(Scene scene)```.

Wouldn't it also be nice to have ```add(String sceneName)``` instead of ```add(new Scene(String sceneName))```?

In addition to that it would be really convenient to have ```add()``` return the scene itself.

Oh, right, also ```add(int index, String sceneName)```.

What do you guys think?

**Comment by GoranM** [comment]
The scenes list can have multiple scenes that share the same name, so `remove(String sceneName)` doesn't really make sense, because there's no way to specify which scene to actually remove in that case.

We discussed add(String) in #148.

I don't think the gains (in terms of convenience) are worth the additional methods, but if you really want it, I'll merge it.

It's your decision.

**Comment by rafcolson** [comment]
@GoranM 

When looking at ```add(int index, Scene scene)``` I noticed that it returns a boolean.
```java
		public boolean add(Scene scene){
			boolean ret = super.add(scene);
			if (scene.objects == null)
				scene.init();
			return ret;
		}
```
Could this return the scene instead? I tried but it really can only return a boolean. Is there no way to replace ```add```? Because returning the scene works when for example changing it to ```addScene```.

The same with ```add(int index, Scene scene)```. This can only return ```void```, so it seems.

Also ```set()``` is modified to be able to return the "old" scene. Could you maybe explain why it's like that?
```java
		public Scene set(int index, Scene scene){
			Scene old = remove(index);
			add(index, scene);
			return old;
		}
```
>because there's no way to specify which scene to actually remove in that case.

Thinking about it, wouldn't it be only the case if the same scene is added more than once? Maybe that would be useful in some cases, but it would not be regular practice. Doing this also requires to store the scene reference somewhere outside Bdx.scenes in order to have access to it.

**Comment by GoranM** [comment]
> Could this return the scene instead?

Why would you want/need that? You already have the relevant scene reference.

> The same with `add(int index, Scene scene)`. This can only return void, so it seems.

Don't you mean `boolean`? You're referring to the same method as above.

> Also `set()` is modified to be able to return the "old" scene. Could you maybe explain why it's like that?

Because that's what the List.set does, and because it makes sense: The set method replaces an element at the given index, but you might want to retain the old element, and you can't do that unless you have a reference to it.

> Thinking about it, wouldn't it be only the case if the same scene is added more than once? Maybe that would be useful in some cases, but it would not be a regular practice.

Yes, but it's still a possibility.

> Doing this also requires to store the scene reference somewhere outside Bdx.scenes in order to have access to it later.

If the user wants to retain the scene, they should retain the reference. If not, they can just leave it for the garbage collector. I think that's more elegant than `remove(String sceneName, boolean save)`, and subsequent `add(String sceneName, boolean saved)`, which would otherwise be required to make an equivalent distinction.

**Comment by rafcolson** [comment]
>Why would you want/need that? You already have the relevant scene reference.

Well, I wouldn't really need this, but it sure is more practical. With the changes I wanted to make, instead of this:
```java
Scene overlayScene = new Scene("Overlay");
Bdx.scenes.add(overlayScene);
```
You could just do this:
```java
Scene overlayScene = Bdx.scenes.add("Overlay");
```
Which is more convenient. But if it's not possible with the current ArrayListScenes class, then so be it.

**Comment by GoranM** [comment]
It's possible, but as I said #148:

> I don't think we can leave it at just add - I mean, you would also want add at index, and set.
>
> So, that's 3 additional methods.

Does the convenience you outlined justify that ... I'm not sure, but:

If you want to add those 3 methods, I'll merge those commits.

As I said: It's your decision.

**Comment by rafcolson** [comment]
>It's possible, ...

It wouldn't be possible with ArrayList extension, as you can read [here](http://stackoverflow.com/questions/30003115/java-extending-arraylist-have-add-return-object). I think I would be changing to much by reverting ```ArrayListScenes``` to just a regular ```Scenes``` class, and adding a private ```ArrayList``` to ```Bdx``` to store the scenes there. Then this would be possible.

>Don't you mean ```boolean```? You're referring to the same method as above.

Actually both method are not the same. One returns ```boolean```, the other ```void```, as been documented [here](http://docs.oracle.com/javase/7/docs/api/java/util/ArrayList.html#add(E)).

**Comment by GoranM** [comment]
In my tests, it's possible:

```java
public Scene add(String name){
    Scene scene = new Scene(name);
    add(scene);
    return scene;
}
```

It's true that overriding methods must return the same type, but `add(String)` is not an overriding method, because `ArrayListScenes` extends from `ArrayList<Scene>`, not `ArrayList<String>`, so underlying parent methods take `Scene`, not `String`.

This means that `add(String)` is a completely different method, which is free to return whatever you wish.

> Actually both methods are not the same. One returns boolean, the other void, as been documented here.

`add(Scene)` returns a boolean, `addScene(int, Scene)` returns void. You referred to both scenes by the same `add(int, Scene)` type signature, and that confused me.

**Comment by rafcolson** [comment]
I see. Thanks. One last question with ```set()```. The method doesn't seem to override anything. So could it be omitted?

**Comment by rafcolson** [comment]
PR merged. Thanks.
