### ISSUE TITLE
Suggestion: additional methods for Pointer

### ISSUE THREAD

**Issue by rafcolson** [GoranM/bdx#284]
I would like to move ```Mouse.position()``` to ```Pointer.position()``` because then this method could be used for ```Finger``` too.

Then I would like to add these methods to ```Pointer```:
- screenPosition(boolean keepRatio) - Vector2f vec
- screenPosition() - Vector2f vec
- screenPosition(Vector2f vec, boolean keepRatio)
- screenPosition(Vector2f vec)

By default ```keepRatio``` is ```false```. But if ```true```, the screen position will be relative to the screen ratio. For example, with a screen size of 1024 X 576, the upper right corner of the screen will be at ```(1,7777777, 1)```. This allows to get and set the screen position of the mouse without any deformations.

I also like to add this ```keepRatio``` option to ```Camera.screenPosition```.

**Comment by GoranM** [comment]
You can't actually set the position for Finger. I mean, you could probably make the system believe that you could, at least for a tick, but you can't move the actual finger - So, moving position() to Pointer would probably be ok, but only Mouse should have a position setter.

Regarding other methods: I don't know if the names make sense, because position already implies "screen". I think "normalizedPosition" would be a more relevant name, when creating a position vector with members that cannot exceed 1 (which is what I would recommend).

Also, it seems ok to simply include aspect ratio, instead of having an additional option - I don't think there's much utility in a position that excludes aspect ratio.

Again, as for position, normalizedPosition getter should be on Pointer, with setter method on Mouse.

**Comment by rafcolson** [comment]
With including aspect ratio I assume you mean that both width and height go from 0 to 1, right?

**Comment by rafcolson** [comment]
PR updated.

**Comment by rafcolson** [comment]
PR merged.
