### ISSUE TITLE
Bug: Physics general

### ISSUE THREAD

**Issue by rafcolson** [GoranM/bdx#297]
Hello guys,

I had a look at how physics work at the moment and there are a couple of problems. I may stumble into other issues, which I will be posting here, but for now I can mention two:

1. Physics Bounds for Convex Hull are slightly larger as normal. Box and Triangle Mesh are okay. Notice that the Margin is set to zero in all the examples. As a result, with parenting, object will stagger because their physics meshes intersect.

2. When compound children are dynamic or rigid bodies the compound mesh will fly around. I suspect that the old bodies are not removed properly and so they are intersecting.

![debug_physics_1](https://cloud.githubusercontent.com/assets/10002909/7547174/447e236e-f5e8-11e4-8933-cf23e0adbcc2.png)

Any thoughts on the subject are welcome. In the meantime I'll try to fix these issues.

**Comment by SolarLune** [comment]
> Physics Bounds for Convex Hull are slightly larger as normal. Box and Triangle Mesh are okay. Notice that the Margin is set to zero in all the examples. As a result, with parenting, object will stagger because their physics meshes intersect.

Hmm, I think I see what you're talking about (the green and red wireframe meshes appear larger on the non-parented convex hull shot). I don't think I did anything extra apart from send vertices to compose the physics mesh when I implemented it, so I'm not sure where this "swelling" is coming from. Have you tried other objects apart from cubes, and different scales to see if it's proportional or a constant increase in size?

> When compound children are dynamic or rigid bodies the compound mesh will fly around. I suspect that the old bodies are not removed properly and so they are intersecting.

I'm gonna guess it's probably because the children aren't ghost. They still have their own meshes, and those meshes are added to the parent, so that's kind of expected. I suppose BDX removing the meshes or the user simply setting the children to be ghost when parented to a compound parent would be satisfactory.

**Comment by rafcolson** [comment]
>Have you tried other objects apart from cubes, and different scales to see if it's proportional or a constant increase in size?

I did just now. (found another bug too). And it's constant increase in size.

>The user simply setting the children to be ghost when parented to a compound parent would work fine, too.

Yes, that solved it. But maybe better to throw out the mesh. I'll have to check if after a compound mesh is created the child body can be destroyed. If so, than it would only be beneficial, performance-wise too.

**Comment by SolarLune** [comment]
> I did just now. (found another bug too). And it's a constant increase in size.

So it's, like, 0.05 BU or whatever of space between the object and the physics mesh no matter the scale or shape of the object, huh?

> Yes, that solved it. But maybe better to throw out the mesh. I'll have to check if after a compound mesh is created the child body can be destroyed. If so, than it would only be beneficial, performance-wise too.

But you might want to un-parent a child mesh to have it act independently sometimes. Would your solution re-build the mesh for the child when it's un-parented?

**Comment by rafcolson** [comment]
PR submitted.

**Comment by rafcolson** [comment]
PR merged. That only leaves the issue with compound.
