### ISSUE TITLE
Bug: Children are lagging behind

### ISSUE THREAD

**Issue by rafcolson** [GoranM/bdx#298]
Hello,

Another thing I noticed when parenting is that children lag behind, which is unfortunate.

I don't know if this is a known issue but any pointers would help fixing this.

This is what I'm talking about:

Edit: [children_visual_update_bug.blend](https://www.dropbox.com/s/x1a2y90abx4w29f/children_visual_update_bug.blend?dl=0)

**Comment by SolarLune** [comment]
Okay, I think I see - the top cube is in front of the bottom one, which must be the child? Perhaps? In any case, if it's a matter of positioning, then I'm guessing the code that positions the child needs to run after the code that positions the parent, if it doesn't already. 

As a side-note, are you doing some blurring post-processing or layering screenshots on themselves in GIMP or something? Personally, it makes it a bit difficult to visually see the issue.

**Comment by rafcolson** [comment]
@SolarLune I'm sorry it's difficult to visualize. I'm still searching for a way to visualize things. Maybe I should fade it out the other way around, without physics visualization.

**Comment by GoranM** [comment]
On first glance, I thought that the child transform was updated based on the last frame parent transform, but looking at the code, that didn't seem to be the case; We properly update child transforms right after bullet updates the parents.

I confirmed this by calculating the delta during fall: `boxa.position().minus(boxb.position()).length()` always returned 1, so the problem had to be in how the visuals were updated.

As it turns out, we were getting the bullet transform from the motion state, which doesn't reflect current data.

We now get it directly from the body, which seems to work correctly.

PS: There was no need for a "Spawner", and the code that goes with it - You could have simply placed the boxes in the first layer, and parented one to the other via Ctrl-P. We should try to keep our examples as simple as possible.

**Comment by rafcolson** [comment]
Thanks, @GoranM. I'll try to keep examples simpler next time.

**Comment by rafcolson** [comment]
Fixed.
