### ISSUE TITLE
Suggestion: GameObject.mass setter and getter

### ISSUE THREAD

**Issue by rafcolson** [GoranM/bdx#306]
Getter and setter for mass, with private variables ```mass``` and ```inertia```. I've added inertia so this wouldn't have to be calculated with every body change.

**Comment by GoranM** [comment]
If you can simply recalculate inertia, that would be better than having an additional field on GameObject. Same with mass: If you can get the current mass from the body, you should just do that, instead of having a redundant field.

Also, is there a situation in which you want to change mass, but not calculate local inertia? If not, there's no need for an additional method - You can just have `mass(float)` which will always calculate local intertia.

**Comment by rafcolson** [comment]
Oh, yes, you are right. I missed that! I could remove ```inertia``` then. But I'll better keep ```mass``` for this will become necessary later on. We like to change mass and preserve the value without changing the json value, don't we? We can't always access the body for this, as sometimes objects will lose their mass when parented to other objects. When unparenting we have to get the old mass somewhere.

**Comment by GoranM** [comment]
I didn't say that we should change the json value - json data should be treated as read only.

For the mass getter, it should be possible to use the information already on the body, so, in general, that shouldn't require a mass field on GameObject.

For situations where you need to remember the last mass, it would make sense to have a `lastNonZeroMass` field.

**Comment by rafcolson** [comment]
PR submitted.

**Comment by rafcolson** [comment]
Thanks for the merge!
