### ISSUE TITLE
Bug: Xbox 360 Right Trigger Gets Stuck

### ISSUE THREAD

**Issue by SolarLune** [GoranM/bdx#323]
Hey, there. So basically, the right trigger sticks when you check for it in an input map. `Bdx.imaps.iDown()` reports as 1 when you click the trigger, but it never reports as 0 when you let go of the trigger. After some testing, I'm personally unsure as to what the issue is in particular.

**Comment by GoranM** [comment]
`Bdx.imaps.iDown()` is simply a wrap around `Bdx.imaps.down()`, which, for the gamepad, is simply a wrap around `Bdx.gamepad.btnDown()`. So, I suspect that this problem is isolated to `Bdx.gamepad.btnDown("rt")`.

If you read Gamepad.java, you'll notice that each profile is given a (well documented) processAxis method.

For the xbox 360:

```java
		// Unlike the original xbox, which uses one axis per trigger, 
		// xbox360 gamepads use a single axis for both triggers, where RT
		// values are positive, while LT values are negative. We convert 
		// to effectively place RT on a different axis index (5), which enables us 
		// to use positive values for both triggers.
		// 
		p.processAxis = new Profile.FnProcessAxis(){
			public float[] eval(int axis, float value){
				if (axis == 4 && value < 0){
					axis = 5; // RT
					value = -value;
				}
				return new float[]{axis, value};
			}
		};
```

I don't have an xbox 360 controller, so I can't test this, but I would guess that, when you release the right trigger, the value is 0, which doesn't fall under the `value < 0` case ... but then how do they actually differentiate between two triggers for the release? I mean, since both triggers are using the same hardware axis (4), if I'm holding down both triggers, and then only release one, how can I know which was released?

**Comment by SolarLune** [comment]
I think one would need to use an XInput library to differentiate between the axes; otherwise, as you've noted, it just reports as one single axis. 

I guess a potential workaround (to some extent) would be to force release of both triggers if the value is 0. So if you press RT and then LT, it "drops" both. Not ideal, but at least a bit more usable, rather than never being able to "un-trigger" RT.

**Comment by GoranM** [comment]
How did you test? I would try something like this:

```java
            ...
            public float[] eval(int axis, float value){
                System.out.println(String.format("axis: %d, value: %f", axis, value));
                if (axis == 4 && value < 0){
                ...
```

With that, you should be able to see the exact events, as provided by libgdx - There may be some pattern that we could leverage.

For example: If a release event, for a specific trigger, is always preceded by an event with a non-zero value, which corresponds to that trigger, that would be enough to differentiate.

**Comment by rafcolson** [comment]
>So basically, the right trigger sticks when you check for it in an input map.

The right trigger's axis code also gets stuck on my Logitech Wireless Gamepad F710.

**Comment by SolarLune** [comment]
PR was merged, so I'll close this. Thanks!
