### ISSUE TITLE
Bug: Bullet.makeShape() turns TRIANGLE_MESH into a box shape (FALSE ALARM)

### ISSUE THREAD

**Issue by rafcolson** [GoranM/bdx#360]
There seems to be something wrong with this code:
```java
		if (bounds.equals("TRIANGLE_MESH")){
			TriangleIndexVertexArray mi = new TriangleIndexVertexArray();
			mi.addIndexedMesh(Bullet.makeMesh(mesh), ScalarType.SHORT);
			shape = new BvhTriangleMeshShape(mi, false);
```
Because this seems to convert the shape into a regular box as you can see in [this example blend](https://www.dropbox.com/s/qlk85ue5nhvmuig/physics_triangle_mesh_bounds_bug.blend?dl=0).

Any idea's why this is the case?

**Comment by SolarLune** [comment]
OK, it looks like BDX isn't exporting the right collision types to the physics JSONValue collection. I'll take a look at exporter.py.

**Comment by SolarLune** [comment]
OK, looks like Box is being forced for some reason on non-static triangle mesh objects, which you can see here:

https://github.com/GoranM/bdx/blob/master/blender/bdx/exporter.py#L403

I seem to remember @GoranM did this intentionally to prevent something, but I don't remember what.

**Comment by GoranM** [comment]
I was under the impression that TRIANGLE_MESH is supposed to be used only for static objects, so I had that selection default to box for non-static types.

**Comment by SolarLune** [comment]
OK, I see a bit of information here about that:
http://bulletphysics.org/Bullet/phpBB3/viewtopic.php?f=9&t=437
A bit old, but that still might be the case. This reference on the Wiki indicates that triangle mesh objects are best saved for static, so I'd guess it's still correct.
http://www.bulletphysics.org/mediawiki-1.5.8/index.php/Collision_Shapes

I guess we might as well err on the side of safety, since we don't know if it's supported over the long-term, even if dynamic triangle mesh would appear to work fine.
____
It would appear that this is actually already documented on the General Overview > Object Physics page, so that's cool. I think I would recommend that the listing of what object physics types are supported and what bounds are supported be replaced by a simple table with the physics types and bounds types to make it clear...? What do you guys think?

**Comment by GoranM** [comment]
> A bit old, but that still might be the case.

Note that we're using gbullet, which is a port of jbullet, which is a port of bullet 2.72 ... so, the old info is more than likely to be relevant.

> I would recommend that the listing of what object physics types are supported and what bounds are supported be replaced by a simple table with the physics types and bounds types to make it clear...? What do you guys think?

If you think it would be useful, sure.

**Comment by rafcolson** [comment]
>OK, looks like Box is being forced for some reason on non-static triangle mesh objects

That explains it.

>I was under the impression that TRIANGLE_MESH is supposed to be used only for static objects, so I had that selection default to box for non-static types.

Yes, it seems that Dynamic TRIANGLE_MESH will penetrate other objects with TRIANGLE_MESH and in any case RIGID_BODY will work as DYNAMIC would.

>I would recommend that the listing of what object physics types are supported and what bounds are supported be replaced by a simple table with the physics types and bounds types to make it clear...? What do you guys think?

I've added CONE and CYLINDER. I don't mind of course, it's only that the only exception here is TRIANGLE_MESH. A table would make it more noticeable, but I think it would also by rephrasing the sentence:
>Static physics typed objects can have any of those types of bounds; Other physics types can have any collision bound type except triangle mesh.

Into:
>Attention: TRIANGLE_MESH is not supported with body types DYNAMIC and RIGID_BODY!

**Comment by SolarLune** [comment]
^ That sounds fine, I changed it into that.

I don't mind you closing this, either.

**Comment by rafcolson** [comment]
Okay, closing.
