### ISSUE TITLE
Question: GameObject.end()

### ISSUE THREAD

**Issue by rafcolson** [GoranM/bdx#454]
Hi guys, is there any reason why it's like this:

```java
	public void end(){
		for (GameObject g : new ArrayList<GameObject>(children)){
			g.end();
		}
		endNoChildren();
	}
```
Instead of this?
```java
	public void end(){
		for (GameObject g : children){
			g.end();
		}
		endNoChildren();
	}
```

**Comment by SolarLune** [comment]
I think it's because the endNoChildren() function removes the child from the parent's children list. So, if you just run through the array straight and remove the children, you'll skip over children and end up going out of the array's size. 

For example, when you remove a child at index 0, the array gets one shorter, so index 1 now points to the third child, not the second, because the second child is now at index 0, and so on. If that array was only 2 children long, though, then index 1 wouldn't exist anymore, and trying to remove the child at index 1 would then cause a crash.

At least, I believe that's what's up.

**Comment by GoranM** [comment]
> So, if you just run through the array straight and remove the children, you'll skip over children and end up going out of the array's size.

Actually, Java will throw a "ConcurrentModificationException" before letting that happen.

In more general terms: We can't remove objects from a list that we're currently iterating over, so we iterate over a copy.

**Comment by rafcolson** [comment]
Thanks for your explanations.
