### ISSUE TITLE
Suggestion: API changes -> GameObject.name is editable

### ISSUE THREAD

**Issue by rafcolson** [GoranM/bdx#466]
The API states the following:

><a name="name" href="#name">#</a> **name** - String 
>
>The name of the game object. A game object's name cannot be changed from BDX; this can only be done via Blender's GUI before the game is exported.

Especially the part "A game object's name cannot be changed from BDX" doesn't seem to be true entirely, because ```GameObject.name``` is editable alright.

I found this editability to be quite handy in some cases, for example with indexing added objects for saving and loading.

So my suggestion is to remove this sentence in the API or at least elaborate what is meant by not being able to change the name from BDX, if that still seems to be true in some way.

**Comment by GoranM** [comment]
@SolarLune added that description (this was before the new wiki editing policy, so that's why it slipped through).

I agree that it's misleading.

Originally, there was no description, which meant that it was supposed to be treated as a "read-only" value (this is clearly stated on [the main API page](https://github.com/GoranM/bdx/wiki/API) -> "Unless otherwise labeled, all fields should be considered read-only").

I think it's probably best if we revert to that.

**Comment by rafcolson** [comment]
Okay. So I'll remove the description.
