### ISSUE TITLE
Mac Development

### ISSUE THREAD

**Issue by tedmagic** [GoranM/bdx#477]
On a mac, I'm getting the exact same problem as [#11](https://github.com/GoranM/bdx/issues/11) and I don't understand how to fix it. I'm not super low level with this. Somehow excluding the jar in the classpath?

**Comment by GoranM** [comment]
I don't really know what's causing this - I outlined some theories in #11, but that's all have.

Hopefully, @slightfx will see this and explain what he did in more detail, as I gather that he managed to solve this issue.

Sorry I couldn't be more helpful.

**Comment by joorce** [comment]
I have the same problem. I was hopping to use BDX for the libgdxjam, It's a pitty because the project is very interesting.

**Comment by SolarLune** [comment]
@joorce - I take it that you've already checked out @slightfx's solution? What version of OS X do you have, and do you have this problem when running BDX through Blender, when using gradle to run your game project, etc.?

**Comment by joorce** [comment]
I've got a solution. It looks the problem is related with multiple Java installations. I tried @slightfx's aproach but to remove something from the /System/Library/Java in "El Capitan" you have to disable System Integrity Protection. Link below.
Once disable you can delete the whole Java installation or as I did just rename the Extensions directory. 

[How to uninstall Java from El Capitan](http://machow2.com/how-to-uninstall-java-from-el-capitan/)

**Comment by SolarLune** [comment]
Aw, sweet. Glad you figured it out! Too bad there's some sort of issue with (some?) Mac's Java installations that requires this, but I'm glad that a resolution seems to have emerged. Thanks for figuring it out! I'll add something in the docs to reference this.

**Comment by joorce** [comment]
You're welcome.

**Comment by SolarLune** [comment]
@tedmagic - Yo! Did you find that @joorce's suggestion solved your problem?

**Comment by tedmagic** [comment]
@SolarLune Yes, that fixed it. Too bad that's necessary but oh well. Thanks to joorce!

**Comment by SolarLune** [comment]
@tedmagic - Cool! Could you close this issue, then?

**Comment by tedmagic** [comment]
@SolarLune Right, lol.
