### ISSUE TITLE
Suggestion: Scene.objects Should Be ArrayListGameObject

### ISSUE THREAD

**Issue by SolarLune** [GoranM/bdx#492]
Hey, there. 

I think it'd be useful to have the scene.objects list be an instance of ArrayListGameObject. That way, you could easily grab an object that satisfies a criteria of having a specific property or component (i.e. get the first object found with the "Map" property).

It might also be nice to have a `getByName()` function for ArrayListGameObject. It'd return a GameObject if its name contains the string entered (useful to find an object by a name, but that may have duplicates elsewhere in the scene or in the Blend file).

**Comment by SolarLune** [comment]
Also, Scene.cameras should be the same way; at least, it should be ArrayListNamed<GameObject>, so you can retrieve cameras by name.

**Comment by GoranM** [comment]
A LinkedList is used because it allows for cheap element removal (especially when removing elements from the front), even when the list is fairly large.

With an ArrayList, a remove operation at the front of the list would have to copy down all the elements that follow the removed object, and that could get very expensive.

You could create a LinkedListGameObject, with same methods as ArrayListGameObject, and then use that.

> It might also be nice to have a getByName() function for ArrayListGameObject. It'd return a GameObject if its name contains the string entered (useful to find an object by a name, but that may have duplicates elsewhere in the scene or in the Blend file).

The method name implies the same operation as get(String name) ...

Getting an object with the name that contains a given string doesn't seem like a generally useful operation.

**Comment by SolarLune** [comment]
Ah, okay, so there were optimization concerns. That makes sense.

> Getting an object with the name that contains a given string doesn't seem like a generally useful operation.

Eh, it's somewhat useful, I think, but I could see it's not "pressing" enough to include, so it's fine.

Thanks!
