### ISSUE TITLE
New line in Text results in keyError

### ISSUE THREAD

**Issue by Nananas** [GoranM/bdx#51]
First of all, the demo works without a problem. :+1: 

But when using a `\n` (=10) character in a text object, I get a
```
KeyError: '10'
   c = ac["char"][str(ord(char))]
File "...bdx\exporter.py", line 173, in vertices_text
   ... etc.
```

**Comment by GoranM** [comment]
Thanks for testing!

Yea, new-lines, and some other characters are not supported. I can't give you the exact list, because it really depends on what the font supports, and what [Hiero](https://github.com/libgdx/libgdx/wiki/Hiero) decides to include in the angel code.

In the latest release, all unsupported characters will be interpreted as spaces, and you should no longer see that error.
