### ISSUE TITLE
Sugestion: Swap model textures

### ISSUE THREAD

**Issue by Fr0sk** [GoranM/bdx#524]
I think it would be nice to have a way to swap a model texture with another by code, so we can give some customization to our players. Right now the only way I can think of is to create a object for each texture I have and swap it with the current object being rendered. Also (don't know if should be here) is it impossible to have texture files in folders inside the textures folder? Because in mid/large projects it can get a mess preaty soon...

**Comment by SolarLune** [comment]
> I think it would be nice to have a way to swap a model texture with another by code, so we can give some customization to our players. Right now the only way I can think of is to create a object for each texture I have and swap it with the current object being rendered.

Yeah, that would be nice to have. Currently, like you mentioned, textures are kinda locked to materials, and materials are locked to models under BDX. However, being that we're using LibGDX under the hood, it might be possible to do manually.

Anyway, it'd be nice to alter these two aspects in-game via code, at least for replacing the material on a model, initially.

> Also (don't know if should be here) is it impossible to have texture files in folders inside the textures folder? Because in mid/large projects it can get a mess preaty soon...

That should be possible, but you're right. It looks like textures are expected to reside directly in the textures directory at the moment. That should be pretty easy to add in, though.

**Comment by Fr0sk** [comment]
> Yeah, that would be nice to have. Currently, like you mentioned, textures are kinda locked to materials, and materials are locked to models under BDX. However, being that we're using LibGDX under the hood, it might be possible to do manually.

> Anyway, it'd be nice to alter these two aspects in-game via code, at least for replacing the material on a model, initially.

Well, I'm  guessing that under the hood BGX is just creating libGDX modelInstances of the models, if so, at least provide a way to access the modelInstance and that would make possible to swap either materials or textures. Don't know if I'm right though... 

> That should be possible, but you're right. It looks like textures are expected to reside directly in the textures directory at the moment. That should be pretty easy to add in, though.

About this, I think that if the textures are easily swappable this might be easy to overcome, since code is not (or at least shouldn't be) locket to one dir and no subdirectories, but yeah, it would be a really nice addition.

**Comment by SolarLune** [comment]
> Well, I'm guessing that under the hood BGX is just creating libGDX modelInstances of the models, if so, at least provide a way to access the modelInstance and that would make possible to swap either materials or textures. Don't know if I'm right though...

You are correct. The mesh is available under the GameObject's modelInstance field, so for now, an entry-point would be there. It's not documented in the API because most of the time, I don't think most developers would really need to access a modelInstance oneself, directly. It might be a good idea to document it, nonetheless, though, with a note that it's the means through which you have more direct access to the model, should you need it.

**Comment by Fr0sk** [comment]
> You are correct. The mesh is available under the GameObject's modelInstance field, so for now, an entry-point would be there. It's not documented in the API because most of the time, I don't think most developers would really need to access a modelInstance oneself, directly. It might be a good idea to document it, nonetheless, though, with a note that it's the means through which you have more direct access to the model, should you need it

Well, you made my day now. I was about to drop BGX as the game engine for my game because I couldn't swap the textures and since I have many personalization opinions, it would be a mess to create an object for each texture and drop all of them on the same folder... If there is access to the modelInstance then yes, it should be documented. I spend some time reading the API trying to find something that could bridge me to the libgdx modelInstance or something like that, and it would serve my needs well if this was documented. 

Since the engine is built on top of libgdx you shouldn't be priving devs of getting to it's methods and neither hiding it somewhere in the background. Libgdx is a very mature set of libraries with a lot of tools created to it (i.e. app stores integrations and tutorials) and although the wrapping you are making around it is really, really good, leveraging the BGX functions, libgdx has more time, more devs, and therefore is more mature.

**Comment by SolarLune** [comment]
Yeah, the engine is still fairly new and young, so some things that would be nice to have just aren't there yet. However, feedback is very nice to hear, and we're always eager to hear how the engine could be improved from people who are actually making games with it. 

I'm not the creator of the engine, so I can't speak on the overall goal of BDX, but I do appreciate that if there's something we don't support with BDX, we shouldn't block off access through LibGDX. I've already added a note to the GameObject API page that informs of the modelinstance field.

As for material switching, I was going to add a function for this some time ago, but kinda got distracted - I'm back on the case now, haha.

**Comment by SolarLune** [comment]
I actually got material switching working fine, but I've ran into an issue. It looks like there's no way to tell which polygons use which materials in the object's material dropdown in Blender, so switching material by slot number isn't as nice as you would like. For example, you can switch the material in slot 0, but the material in slot 0 in Blender may not be the material in slot 0 in BDX.

@GoranM - When you've gotten a chance to read through this, do you have a suggested solution for this? 

One would be to export the material slot order alongside everything else so that we can tell which materials are in which slots for each object. 

Another would be to internally store a mapping of material names to slots on object creation, and use the name of the material to switch (i.e. using a function like: `material("FirstMaterialName",  "IntendedMaterial")`). Upside of this one is that it's pretty easy to visualize before the fact, but the down-side is that after that first switch, that visualization changes, but the naming would stay the same. So, you would use the function with the first material's name still if you wanted to change it again.

**Comment by Fr0sk** [comment]
> I actually got material switching working fine, but I've ran into an issue. It looks like there's no way to tell which polygons use which materials in the object's material dropdown in Blender, so switching material by slot number isn't as nice as you would like. For example, you can switch the material in slot 0, but the material in slot 0 in Blender may not be the material in slot 0 in BDX.

If you don't mind, can you tell me how do you manage to switch the material? Is it implemented in the latest release of GDX? Because I keep trying but can't find the way :(

**Comment by SolarLune** [comment]
Sure, but materials that are exported from Blender aren't publicly available in the Scene class (though the PR I just opened would fix this).

Anyway, this should work, and should work in whatever version of LibGDX you have, I believe:

```java
public void material(Material newMat, int slot) {
	for (Node n : modelInstance.nodes){
		n.parts.get(matSlots.get(slot)).material = newMat;
	}
}
```

Note that the slot number for the mesh is not what was exported from Blender. 

_____

In the meantime, I've opened a PR for material switching. It's not too awkward, but it's also not quite as I'd like it. The core issue that in Blender, you can have materials on multiple slots, or materials in slots that aren't used on the mesh. For BDX, though, those don't apply - if a material isn't on the mesh, no vertices for the mesh will be built with the material, and so there won't be a MeshPart "material slot" on the mesh there. Also, if two or more slots share a material, then they will be "compounded" into a single MeshPart "slot". The solution I opted for is just to basically store the slot numbers to material names so that you would call `material()` to switch material as though it's never been switched before.

So, for example, if you had a ball with a red top half and a blue bottom half (with materials named "Red" and "Blue" on the mesh), and you wanted to switch the red top half to yellow, you'd call:

```java
material("Yellow", "Red");
```

If you then, though, wanted to switch it from yellow to blue, you would call

```java
material("Blue", "Red");
```

and NOT

```java
material("Blue", "Yellow");
```

As there's no yellow material present on the original mesh.

This was done to preserve channels, so that changing separate faces to use a single material didn't mean you lost the ability to change those separated portions of the mesh. This is what feels a bit unsatisfactory, to me. An alternative would be a "slot" HashMap or function that allowed you to number your materials, and then use those numbers to switch material. For example:

```java

slot("Blue", 0);  // Identify the material known as "Blue" on the mesh as being in slot 0
slot("White", 1);  // Same, but with slot 1 for white

material("Yellow", 1);  // Switch any and all materials (White) in slot 1 to Yellow
material("Blue", 1);  // Same, but with blue
```

**Comment by GoranM** [comment]
> That should be possible, but you're right. It looks like textures are expected to reside directly in the textures directory at the moment. That should be pretty easy to add in, though.

Instead of just a texture name, we could export the path, and use that.

It would be a nice little project for him, if he's interested in contributing.

> When you've gotten a chance to read through this, do you have a suggested solution for this?

It would probably be best to ensure that the order in modelInstance.nodes matches the order in the blender material slots.

Perhaps making [m_verts](https://github.com/GoranM/bdx/blob/master/blender/bdx/exporter.py#L111) into an ordered dictionary would be enough. If not, we can export additional information, and order the nodes based on that.

**Comment by SolarLune** [comment]
> Perhaps making m_verts into an ordered dictionary would be enough. If not, we can export additional information, and order the nodes based on that.

I think I tried making m_ps into an ordered dictionary, and that didn't work, but it might be OK now that I made m_verts into an OrderedDict and am looping through the materials first to set the arrays in mat_tris, rather than doing so based on the polygons.

Is it OK that polygons using the same material in separate slots gets combined down into one?

**Comment by SolarLune** [comment]
Well, if it's not OK, lemme know if you think of a design change, Goran. Otherwise, I've updated the PR with the improved version that pays closer attention to Blender's slot material setup. Even materials that have no vertices assigned to them are "used" in modelInstance parts now.

**Comment by Fr0sk** [comment]
> Instead of just a texture name, we could export the path, and use that.

> It would be a nice little project for him, if he's interested in contributing.

I sure don't mind contributing, it does not seem too hard as well. As far as I can tell is only changing a thing in the blender exporter right? I'll try that tomorrow, when I get to my computer, right now I'm on my phone. 

> Sure, but materials that are exported from Blender aren't publicly available in the Scene class (though the PR I just opened would fix this).

About the functions you had to the game object class, can I ask why not to include a function that returns the material itself? It might allow to change some material properties without creating a new one. Just asking though.

**Comment by SolarLune** [comment]
> About the functions you had to the game object class, can I ask why not to include a function that returns the material itself? It might allow to change some material properties without creating a new one. Just asking though.

Ah, that's true... But with the materials() function simply returning an ArrayList of Strings, you can easily check to see if an object's materials contains a specific named material (`if collidedObject.materials().contains("PlayerMaterial")`, for example). 

If you wanted to alter a material with the PR proposed, you would just get the material by getting the name of the material you're looking for (either if you know it, or from a GameObject's materials() function), and then get the actual LibGDX Material object by name from the scene.materials HashMap. 

After all, the materials aren't GameObject-specific, but rather just used by the GameObject's modelInstance and stored in the Scene. The materials are "globally" available for any and all objects in the scene to share. There's also a function to switch out the material with a LibGDX Material object if you create one or clone one yourself.

**Comment by Fr0sk** [comment]
> If you wanted to alter a material with the PR proposed, you would just get the material by getting the name of the material you're looking for (either if you know it, or from a GameObject's materials() function), and then get the actual LibGDX Material object by name from the scene.materials HashMap.

Didn't realized that, it make sence then.

About the textures being inside folders, I've managed to make the exporter work, where can I submit the code? Can't create pull requests for some reason...

**Comment by SolarLune** [comment]
Not sure, but it might be because you forked my BDX branch rather than Goran's?

**Comment by Fr0sk** [comment]
> Not sure, but it might be because you forked my BDX branch rather than Goran's?

Yep, I was watching your pull request and accidentally forked the wrong branch. I think it should be ready now.

**Comment by SolarLune** [comment]
Nice! :sunglasses:

As a note, when you submit a PR, put the issue number that the PR relates to in the title. That way, it's tied to the issue.

**Comment by GoranM** [comment]
Oh, and when these are merged, @GoranM, can we get another BDX release?

Sure.

**Comment by SolarLune** [comment]
Both PRs were merged, so this can be closed. Good work @Fr0sk!
