### ISSUE TITLE
Performance on android

### ISSUE THREAD

**Issue by rafcolson** [GoranM/bdx#53]
I'm wondering if this is normal.

In this scene there are 30 X 30 cubes added, with no collision. No scripts running, just a little cube bouncing on a platform on the foreground, to illustrate if there are any frame drops. I have tested with two android mobile phones (Samsung Galaxy Core II and Galaxy Ace 4). Nothing fancy but it should be a standard right now. On both I'm getting 2fps. That's much too slow. So I wonder, is this normal?

Here's the link to the *.apk if anyone would want to test it:

https://www.dropbox.com/s/0ta01nbs8n6akgu/Performance_test2.apk?dl=0

Edit:

I've added another test. This time it's 10 X 10 planes, with no collision. Not so many drops, but I guess this is the limit for my phone.

https://www.dropbox.com/s/iz1d8wiu5oxpdh6/Performance_test4.apk?dl=0

Edit:

I could make a culling system, but then I still have 200 visible planes the most. If there's no way to improve the source I'm afraid I have to model (instead of generate from an image).

Edit:

Culling (making all objects inside the camera's frustum visible, the rest invisible) doesn't change anything. It's strange because I had expected it would.

**Comment by GoranM** [comment]
As I said in your last issue, I didn't really try to optimize anything yet, and mobile hardware is generally under-powered.

I encountered similar performance problems using JMonkey, with just 100 or so cubes clogging down the framerate - [here's the thread](http://hub.jmonkeyengine.org/forum/topic/slow-loadstart-up-and-general-performance-issues/).

So, while there's probably plenty in BDX that could be faster, I'm not sure we'll be able to get significantly higher performance, especially since the underlying libGDX layer is completely out of my control.

If you're really interested in this, and you want to isolate problems, you should run everything through a profiler, or at least time [update](https://github.com/GoranM/bdx/blob/master/blender/bdx/gen/BdxApp.java#L49) vs [renderScene](https://github.com/GoranM/bdx/blob/master/blender/bdx/gen/BdxApp.java#L50).

**Comment by rafcolson** [comment]
Thanks, for all that useful information. I had read somewhere before that what is causing the lag is the actual GL call (I don't know the proper term). And I read that the solution would be to adjust that specific part of the code so all objects with the same mesh are called together all at once, instead of individually. But I wouldn't know how to do that for now. I don't even know if that's even possible with BDX (or GDX). Anyhow, it would change everything for BDX on Android, if it were implemented someday.

Thanks again, and I like those new updates!
