### ISSUE TITLE
Suggestion: Using one scene as library of objects

### ISSUE THREAD

**Issue by dualjack** [GoranM/bdx#541]
It would be nice, if we had possibility to hold gameObjects in some kind of library. It would help me a lot, because I want to use blender's scenes to create different levels for my game.

For now I experiment like that:
```
Bdx.scenes.add(new Scene("Level1"));
Bdx.scenes.add(new Scene("Objects"));
Bdx.firstScene = "Level1";

Player player = (Player) Bdx.scenes.get("Objects").objects.get("Player");
player.position(0, 0, 10);
Bdx.scenes.get("Level1").add(player);
```

and repeat that process for every level

```
Bdx.scenes.remove("Level1");  // remove Level1 and load Level2
Bdx.scenes.add(new Scene("Level2"));

Player player = (Player) Bdx.scenes.get("Objects").objects.get("Player");
player.position(0, 0, 10);
Bdx.scenes.get("Level2").add(player);
```

For some reason objects from Blender scene "Objects" show up before creating instance of them.
Maybe I'm doing something wrong? I tried to move objects to other layer but it doesn't help.

**Comment by SolarLune** [comment]
> It would be nice, if we had possibility to hold gameObjects in some kind of library. It would help me a lot, because I want to use blender's scenes to create different levels for my game.

An easy way to do this is to make a group for objects in Blender and add instances of these groups where you want them. You can then place these instances where you want in Blender, or put them in a hidden layer in the game scenes and spawn them in with BDX.

> For some reason objects from Blender scene "Objects" show up before creating instance of them.
Maybe I'm doing something wrong? I tried to move objects to other layer but it doesn't help.

If you add a scene via Bdx.scenes.add(), then it's added to BDX's scene list, and it will be rendered and updated. Whatever layer is the currently viewed layer _for the scene_ will be the active layer in BDX. You can see what the currently viewed layer for the scene is by clicking the "Lock Camera and Layers" button in the 3D view (next to the layer buttons). If this isn't checked, the current layer and camera may be different from the one that you see in Blender. 

Basically, you can turn this on, set your camera and layer as you want them, and then turn it off to go edit an object in another layer or something.

____

So to summerize:

- If you want to add an object that's not present, just put it in a hidden scene in Blender, and you can add it via code in BDX.

- If you want to keep a library of objects in another scene, you can set up objects as you want them in your Objects scene, put them in a group, and then place an instance of that group in a hidden layer in your game scene. All of the objects will then be available to be spawned in-game. Or, just put them where you want in your game scene.

- This might also extend to keeping objects in alternate .blend files and linking them between another blend file and the current one. Not sure about this, though - BDX only exports the current blend file (of course), but to BDX, it might appear to be a "normal" object, so that's something to think about trying at some point.

- Lastly, what might work code-wise (but probably won't work in practice) would be to add in an object using the scene's templates hashmap. So you'd do something like:

```java
Scene libraryScene = new Scene("Library");
GameObject player = scene.add(libraryScene.templates.get("Player"));
```

Might be worth a shot just to see if it'd work, but I wouldn't recommend it because the object in the library scene would refer to and require resources from that library scene. So, if you, for example, end the game scene or the library scene, BDX would probably throw an error.

**Comment by dualjack** [comment]
Thanks @SolarLune !
Does it mean physics for objects in hidden layers are not calculated?
For a second I thought it's not good to hold these somewhere else, because they will be falling down forever, causing FPS drop.

Wow, this is so cool :)

**Comment by SolarLune** [comment]
Objects in hidden layers aren't drawn, updated, or calculated. They basically don't exist, except that you can spawn them in-game or look at their properties via the Scene's templates HashMap.

Only the current layer of scenes that are in the `Bdx.scenes` list are drawn, updated, or physically simulated. If you have a scene that you want to keep for later, you can remove it from the list, but not call `end()` on it, and keep it around. Then, when you add it back to the `Bdx.scenes` list later, the state will be restored. See the [Scenes](https://github.com/GoranM/bdx/wiki/General-Overview#scenes) and [Spawning and Removing](https://github.com/GoranM/bdx/wiki/General-Overview#spawning-and-removing) sections of the General Overview.

I should add a bit of info to the spawning and removing section to state where those objects come from...

**Comment by SolarLune** [comment]
Ah, I forgot that there's an [Instancing](https://github.com/GoranM/bdx/wiki/General-Overview#instances) section in the General Overview, as well; check that out, too.

**Comment by dualjack** [comment]
I saw that before, but I didn't know objects in hidden layers are not calculated. It changes everything.

**Comment by SolarLune** [comment]
Cool! 

If all of this answers your issue, then you can close it.
