### ISSUE TITLE
Issue: HTML5 / Web Target Not Working

### ISSUE THREAD

**Issue by SolarLune** [GoranM/bdx#551]
Hey, there. 

So, Gradlew can't compile the HTML target because of line 83 of Inputmaps.java, which is where the gamepad index is retrieved from the first character of the descriptor string. 

Submitting an alternative.

EDIT: Holding off for now - looks like there might be several things that are causing HTML5 not to compile. Does it work for anyone else right now?

The current issues I'm seeing:

1) The gamepad index string code isn't working.
2) GWT can't read textures from other folders.
3) There's something wrong with a uniform (u_pointLights) in our lighting shader.

There might be (probably are) more; those are just the ones I saw.

**Comment by GoranM** [comment]
Try removing all the things it complains about, until you get a working build.

With that, we'll have a clear idea of everything that needs to be addressed, and we can try creating workarounds from there.

**Comment by SolarLune** [comment]
> Try removing all the things it complains about, until you get a working build

Will do. I was just wondering if anyone else was also having issues building web / HTML5? If not, then it might be something else; was just trying to figure out where the issue lies, at first.

**Comment by aliasaila** [comment]
The texture filenames in the bdx file have a slash prepended to them, line 220 of Scene.java adds another slash, and we end up with "bdx/textures**_//_**texture.png". Not exactly sure why but that definitely doesn't work in Chrome and probably other browsers as well.

The shader errors are due to the fact that by default the precision for float in vertex shaders is highp, yet the default precision in the fragment shader is declared as mediump.

And finally, changing line 241 of Bdx.java to simply:

`for (Scene scene : scenes) {`

allows me to run the Sacky demo in Chrome 49.

I realize that line was changed to avoid a ConcurrentModificationException, however it does seem to cause an issue with GWT. 

With the original line, I get a ClassCastException in the javascript console.

**Comment by GoranM** [comment]
Thanks for the research.

> The texture filenames in the bdx file have a slash prepended to them, line 220 of Scene.java adds another slash, and we end up with "bdx/textures//texture.png". Not exactly sure why but that definitely doesn't work in Chrome and probably other browsers as well.

I think this bug was introduced by @Fr0sk's [PR](https://github.com/GoranM/bdx/pull/527) - should be easy to fix.

> The shader errors are due to the fact that by default the precision for float in vertex shaders is highp, yet the default precision in the fragment shader is declared as mediump.

It's strange that this is only causing problems in the web build, considering that we're compiling all our shaders in strict mode ... Or maybe we're not?

@SolarLune would know more about that.

> With the original line, I get a ClassCastException in the javascript console.

Well, I don't know why that's happening. If it's valid java code, and not low-level system dependent, it should basically just work with GWT.

Maybe if we manually create a copy of scenes, instead of using the clone method ... ?

Just a guess.

**Comment by aliasaila** [comment]
@SolarLune I have fixes for all except the Character.getNumericValue() issue. How would you like to proceed?

**Comment by SolarLune** [comment]
If you're talking about the one in the Gamepad, I think I was able to bypass it by simply using String.subString() to get a sub string of the first character, instead of Character.getNumericValue.

If that works, please feel free to submit a PR to fix this! I never looked further into it, so it'd be greatly appreciated.

**Comment by SolarLune** [comment]
Cool, the fixes were merged. I'll close this now, and reopen if I have trouble building for HTML5. Thanks, everybody!
