### ISSUE TITLE
Suggestion: functionality to set Gamepad.Profile

### ISSUE THREAD

**Issue by rafcolson** [GoranM/bdx#564]
I would essentially like to be able to define a Gamepad.Profile by pressing buttons on my gamepad. In many games this is a standard feature and especially useful in case the game developer wouldn't be able to add profiles for every kind of gamepad.

Don't know much on how to approach this, so @SolarLune, maybe you have an idea of how this could be implemented?

Oh, and it seems that the ```Gamepad.profiles``` field isn't exposed to the API yet. It probably should if it is our intention to add specific profiles.

Following methods I have in mind:
- Gamepad.btnCode() - int code
- Gamepad.axisCode() - int code

Could be missing something else.

**Comment by SolarLune** [comment]
> Oh, and it seems that the Gamepad.profiles field isn't exposed to the API yet. It probably should if it is our intention to add specific profiles.

Do you mean exposed in the API reference here on GitHub? Yeah, that probably would be wise.

> Following methods I have in mind:
Gamepad.btnCode() - int code
Gamepad.axisCode() - int code

What would these functions do? Just detect a button or axis being pushed? If so, then the axisCode function would need to return at least two arguments - the axis being held, and the direction (1 or -1). 

Also, perhaps naming the functions more descriptively would help - something like `detectBtn()` and `detectAxis()`, and possibly `detectHat()`, or something like that.

**Comment by rafcolson** [comment]
>What would these functions do?

These methods would return the index(es) of a button or axis button being pressed, else null. For example, if I would have a little program running for a menu:
```java
private int index = 0;
private String[] btns = {"left", "right", "up", "down", "a", "b", "x", "y", "start"};
...
if (Bdx.keyboard.keyHit("down") && index != 8)
	index++;
else if (Bdx.keyboard.keyHit("up") && index != 0)
	index--;

Gamepad gp = Bdx.gamepads.get(0);
Gamepad.Profile p = new Profile("MyProfile");
if (gp.btnHit())
	p.btnToCode.put(btns[index], gp.btnCode());
```

>Also, perhaps naming the functions more descriptively would help - something like detectBtn() and detectAxis(), and possibly detectHat(), or something like that.

Well, it's not really a matter of "detecting" a button, axis or hat, but simply "getting" it, and more specifically the "code".

I've looked into ```Gamepad``` and ```GdxProcessor``` in order to understand how input from a LibGdx controller is translated to a ```Gamepad.Profile```. Unfortunately I couldn't find anything. Maybe you could explain briefly how it works, if it's not to much trouble?

**Comment by SolarLune** [comment]
I don't really know too much, myself; I just use it and it works, haha. Seems like basically, each input - an axis being push, a button being pressed, or a hat being pushed, gets a code. The codes are related to the inputs themselves, but also with numbers added to make sure they don't overlap. 

Buttons get the profile code of their indices from the controllers themselves. POV hats get 100 plus the POVDirection ordinals (which might be bitwise, IIRC). Axes get codes internally because they can go in either direction. So, their profile code is 200 plus or -200 minus the axis' code, depending on the axis' direction.

The function you want would just loop through each input (buttons, axes, or just the hat) and return the index that is true (or exceeds a deadzone value, for axes), or else return null, like you mention. You'd have to then look through the `btnToCode` or `axes` lists to find the input name that it corresponds to (if it does), add that to the InputMaps under the desired action name, and that should basically be it.

**Comment by rafcolson** [comment]
Thanks a lot.

>The function you want would just loop through each input (buttons, axes, or just the hat) and return the index that is true (or exceeds a deadzone value, for axes), or else return null, like you mention. You'd have to then look through the btnToCode or axes lists to find the input name that it corresponds to (if it does), add that to the InputMaps under the desired action name, and that should basically be it.

So if I understand correctly, ```gp.btnHit()``` would require to loop through each input? I really hope LibGdx already has a function which already does that, or just returns true whenever a button is pressed.

I'm not using InputMaps as I'm having my own ```Input``` class which custom features, such as a virtual controller (a gamepad on screen using the touchpad for input). But I suppose I don't need InputMaps, do I?

**Comment by SolarLune** [comment]
You should be able to just loop through, say, the first 100 buttons in the [LibGDX controller](https://github.com/libgdx/libgdx/blob/master/extensions/gdx-controllers/gdx-controllers/src/com/badlogic/gdx/controllers/Controller.java#L29) and check.

> I'm not using InputMaps as I'm having my own Input class which custom features, such as a virtual controller (a gamepad on screen using the touchpad for input). But I suppose I don't need InputMaps, do I?

Not if it's a virtual gamepad, no, but I don't know what you're trying to do, exactly. If you want to, feel free to implement button detection - it'd be useful. 

_______

I guess an alternative, better route for this would be to go at this from the opposite direction. Just make a function that returns an ArrayList of the names of all of the buttons that are pressed or held in the Gamepad class itself. 

Because it works based off of the profile, it'd work automatically without having to deal with the differences between buttons, hats, and axes; it'd just loop through the `btnToCode` keys and use `btnDown()` on them. 

If it returns true, it adds that string to an ArrayList and returns it. Even easier, I think.

**Comment by SolarLune** [comment]
Oh, wait, this is automatic detection of inputs, not definition of profiles. That's different. The profile system's just tying button and axis codes to numbers; it's not like you can't physically use an SNES controller with 360 bindings (though you can't because BDX would crash as the SNES controller lacks the inputs). Your InputMaps are what tie gamepad controls to in-game actions, and they are what the player should be able to alter.
_______
What we might think of is having a "default" gamepad that has a basic set of inputs (support for, say, 16 axes, a POV, and 64 buttons). Also, BDX shouldn't crash if the inputs don't exist. That way, the profile can "fill in" the need as necessary for whatever arrangement and type of gamepad the player uses.

**Comment by SolarLune** [comment]
Hey, if you weren't going to do automatic detection of profile inputs, I'll do it. I foresee it being useful for config screens to rearrange keybindings.

**Comment by rafcolson** [comment]
>Hey, if you weren't going to do automatic detection of profile inputs, I'll do it. I foresee it being useful for config screens to rearrange keybindings.

That would be great, @SolarLune ! As I'm not completely understanding the workings of it still. But could you please make sure that you don't build it on top of ```InputMaps```? It's a nice feature, but I don't think it should be the basis for everything that deals with input. I also think it's unfortunate that the ```Logger``` is build on top of it. If I would want to use this, I'm practically obligated to also use ```InputMaps```.

Why don't I use ```InputMaps```? Mainly because I'm more for the approach to first determine the kind of input (keyboard, mouse, gamepad) so there's no need to iterate through several kinds of input for every keystroke, or press of a button.

About your proposal to implement button detection. I'll have to think about what would be the best implementation for this.

**Comment by SolarLune** [comment]
> But could you please make sure that you don't build it on top of InputMaps?

Ah, well, that's how I was going to do it.

> It's a nice feature, but I don't think it should be the basis for everything that deals with input. 

I don't think so either, but it seems like input maps (binding inputs to actions) would be the logical place for this. And I'm not really sure how else the logging system could work. We have to store something and use that to trigger events later. I don't know if it's possible to programmatically actually "fake" hardware input events with LibGDX.

> Mainly because I'm more for the approach to first determine the kind of input (keyboard, mouse, gamepad) so there's no need to iterate through several kinds of input with every keystroke, or press of a button.

Hmm... Not sure if I understand you. I'd think the InputMaps only iterate through the inputs for the action specified, so if you're checking for, say, "jump", it'll look through the one, two, or however many values that are mapped to the "jump" action.

**Comment by rafcolson** [comment]
> don't think so either, but it seems like input maps (binding inputs to actions) would be the logical place for this. And I'm not really sure how else the logging system could work. We have to store something and use that to trigger events later. I don't know if it's possible to programmatically actually "fake" hardware input events with LibGDX.

I don't mind if you make a logging system for InputMaps especially. As long as it's build out of parts that can be used for building logging systems, apart from InputMaps. I still don't understand why we couldn't just get raw input. When a button is pressed, the LibGdx controller returns something, right? I'm sorry I still don't understand why we would need InputMaps for that. I'm only assuming that a simple ```Bdx.gamepad.btnHit("start")``` is not build on top of InputMaps. So where do you get the raw input from in this case?

Just to be clear. It would be nice to just be able to assign raw input to a profile. So if I would like to define my start button I would just have to do this:
```java
Gamepad gp = Bdx.gamepads.get(0);
int btnCode = gp.btnCode();
if (btnCode != null)
    gpProfile.btnToCode.put("start", btnCode);
```
>Hmm... Not sure if I understand you. I'd think the InputMaps only iterate through the inputs for the action specified, so if you're checking for, say, "jump", it'll look through the one, two, or however many values that are mapped to the "jump" action.

The idea is to be able to play games with a keyboard or with a gamepad without having to iterate through those inputs with every key stroke or push of a button. So of course both inputs will have to be specified in front in order to have the ability to chose between the two. I definitely wouldn't want to use InputMaps if all I do is just specify input for the keyboard. Then I would use the Keyboard.

Anyway, I hope you understand that I'm not against a feature such as InputMaps. But in my opinion BDX's input shouldn't rely on it, as it would narrow down our options.

**Comment by SolarLune** [comment]
> When a button is pressed, the LibGdx controller returns something, right? I'm sorry I still don't understand why we would need InputMaps for that. I'm only assuming that a simple Bdx.gamepad.btnHit("start") is not built on top of InputMaps. So where do you get the raw input from in this case?

Yeah, the controller does return something. We can check input devices manually (keyboard, mouse, and gamepad), and those methods are exposed through BDX. However, there's no way to send input changes to BDX unless we made some sort of code-based system that acted as an intermediary, to read input changes and "push" them out for reading. If it were done this way, then we could, by code, "push" those changes from input devices, or from replays. 

Basically, without InputMaps, we could record "you pushed A on frame 100", but how do we play it back? We'd need something else.

> I definitely wouldn't want to use InputMaps if all I do is specify input for the keyboard. Then I would use the Keyboard.

I'm still not getting it - why wouldn't you use InputMaps if you only are using one input device? Even for just the keyboard, it would allow you to easily remap keys to actions and make your code easily changeable, rather than having key constants floating around your Player class, for example.

> The idea is to be able to play games with a keyboard or with a gamepad without having to iterate through those inputs with every key stroke or push of a button.

I guess I'm wondering what's wrong with this. Like, what's the problem with this, and what's the alternative, assuming you wanted a system to map actions to defineable inputs?

> But in my opinion BDX's input shouldn't rely on it, as it would narrow down our options.

Yeah, I agree overall.

_______

PR Submitted. 

The pushedAxes() and pushedButtons() functions loop through the number of buttons or axes provided to check for the values. The correct way would be to get the number of buttons or axes and just loop through that number, but the vanilla LibGDX Controller interface doesn't provide this information for some reaso). 

Apparently, the different flavors of the Controllers for each platform do, but that'd mean that we would have to determine which platform the game's running on, and then cast the controller instance to the correct class (I guess?) to get access to the functions. 

So I just looped through.

**Comment by rafcolson** [comment]
I think that should work. Thanks. About InputMaps, I guess I could consider using it when the VirtualController is in. Right now I'm having my own Input class in order to support input from the Keyboard, the Gamepad and a VirtualController. I'll just have to see how it performs.

**Comment by SolarLune** [comment]
Updated the PR to change the function names to `hitButtons` and `hitAxes` to match the keyboard's `hitKeys` function.

**Comment by SolarLune** [comment]
Forgot about the function I wanted to add, `hitInputs()`. It returns the names of the bindings that have been defined in the profile if the profile's been set up already (e.g. `start, ls-left, x, y,...`).

**Comment by rafcolson** [comment]
Great! And by the way, imaps sure is neat. I'm gonna use it. That's if the VirtualController gets approved.

**Comment by SolarLune** [comment]
Haha, yeah, dude, that's what I was trying to say. I mean, it's not the end-all-be-all, but it works really well and is easy to use and customize. 

One problem is the thing that I mentioned earlier - that you can't just plug in a gamepad and have it work with the default XBOX 360 profile because the profile will mention things that the gamepad might not have (like analog sticks, as an example). 

I guess we could just alter the Profile class to have the btn functions return false if the code isn't defined, actually. That way, any profile will work with any gamepad; it's just that the gamepad the Profile was made for will be correct.

**Comment by rafcolson** [comment]
>I guess we could just alter the Profile class to have the btn functions return false if the code isn't defined or the input doesn't exist on the gamepad. That way, any profile will work with any gamepad; it's just that the gamepad the Profile was made for will be correct.

That would be great! But here's another idea. (it's only an idea).

First, we should have a function which creates an "empty" Profile: ```Gamepad.Profile myProfile = Gamepad.Profile.new("MyProfile")```. Empty would mean it is a "full" Profile, but with all values set to ```null```.

Then there should be a "FullProfile" Profile, which would be used to get the id's from, directly assigning this to the new "MyProfile".

Then, when "MyProfile" is fully set, it would be assigned to the Gamepad: ```gp.profile("MyProfile")```. Then the ```Gamepad.profile()``` method would only put in values which are not ```null```.
```java
Gamepad gp = Bdx.gamepads.get(0);
Profile myProfile;

// entering the config screen
gp.profile("FullProfile");
myProfile = Profile.new("MyProfile");

// assigning a value to a button
myProfile.btnToCode.put("x", hitInputs().get(0));

// exiting the config screen
gp.profile(myProfile);
```

**Comment by SolarLune** [comment]
I just want to make sure you saw my previous post:

I believe the correct way of handling input remapping is not to change which gamepad button is called "X", but rather to change what action "X" maps to. So basically, you would be changing which actions correspond to which buttons in the input maps, not changing what the buttons mean, directly.

We could allow the user to change gamepad profiles themselves, but it's not really that big of a deal, especially if we have the ability to simply support all gamepads (and not crash if the gamepad doesn't have inputs that the profile lists).

**Comment by rafcolson** [comment]
>I believe the correct way of handling input remapping is not to change which gamepad button is called "X", but rather to change what action "X" maps to. So basically, you would be changing which actions correspond to which buttons in the input maps, not changing what the buttons mean, directly.

I wouldn't use the term "input remapping", rather "profile definition",

The default profile is "XBOX360". If I set the profile to "XBOX" during the game, what happens is that a new profile is defined and set. This doesn't change what action "X" maps to in InputMaps. So it seems illogical to me to resort to InputMaps when setting up other profiles.

Anyway, I thought we were in agreement that we shouldn't have to rely on InputMaps, when it comes to input. 

>So, we can't really rely on people setting up their own profiles, but rather to support some common ones, allow people to use whatever gamepad they wish with whatever profile, and allow people to remap their controls to actions.

I'm sorry @SolarLune, it just doesn't make sense to me. I mean, with setting up a profile (in game) I wouldn't be asking the player to assign buttons to "x", "y", ..., but to "start", "strike", "jump", "left", "right", .... Internally I still could translate those descriptions to whatever mappings I choose.

All we need is a "FULL" profile, which has all buttons, all axis and all sticks, and it doesn't really matter if button with index 0 is named "x" or "a". In InputMaps we could have defined "a", "b", "x", "y" and "start", these mappings won't change after a new profile is set. What has changed is the indices.

**Comment by SolarLune** [comment]
OK, I think I see. 

This entire thing stems from you not wanting to use InputMaps, but wanting to still be able to remap inputs to actions. You want to change what indexes a button in a profile refers to, rather than changing what action a button in the input maps refers to.

Is that right?

**Comment by rafcolson** [comment]
>You want to change what indexes a button in a profile refers to, rather than changing what action a button in the input maps refers to.

Yes.

**Comment by SolarLune** [comment]
OK. Here's the problems that I see with that approach.

1) You can't map different actions to the same buttons, as the buttons are hard-wired. For example, say that initially, you have the A button be jump and also "Accept / OK" for menus. If you change the index for A to another button code, you'll switch it for both; you won't be able to allow the player to change that mapping (so that "Accept" can be X, and Jump can be B, for example).

2) You won't be able to map non-buttons (axes or POVs) to buttons.

3) You won't be able to map non-gamepad inputs to actions; this would only work for gamepads, which is fairly specific.

4) Personally, it makes no sense to me to change which index a button's name refers to (so that the "X" button now triggers based on the "Y" button, for example) when you could just correctly point the action to the button the player pressed. If you alter the code internally like this, then you can't easily be sure of which button an action is referring to. Leaving the codes alone would be useful when, for example, displaying icons onscreen for actions. Since the code isn't altered, you know that if the action to interact with things depends on the X button, you could safely display "Press X to Interact". Remapping the button index internally is like trying to have keyboard remapping by setting the "q" key to point to the "a" key's scancode; it's just easier to have the action point to the "a" key in the first place.

Using InputMaps would solve all of these problems. So, you don't have to use InputMaps if you don't want to, of course, but unless there's a rather good reason, I'd say it's the recommended approach when checking for inputs, especially when looking into input remapping.

But whatever, this is for your game and you know what you want to use.
____

All that being said, your problem still exists, and it's a problem that InputMaps users will also face. I think it boils down to:

1) Profiles shouldn't fail on controllers that aren't made for them, and

2) I agree that we could use a Generic profile with many buttons and axes. This profile would just have button indices mapped as their names (i.e. "0" being the first button, rather than being named something else gamepad-specific, like "X"). With such a profile, it should work for basically any gamepad, and should work regardless of if used with InputMaps or not.

**Comment by rafcolson** [comment]
>1) [...] If you change the index for A to another button code, you'll switch it for both; [...]

Only when you would be changing indices on the fly. But in my example I tried to explain that you should first create a new profile and define that profile, while the current profile is still active. Not until you confirm any changes made the new profile is set.

>2) You won't be able to map non-buttons (axes or POVs) to buttons.

Why wouldn't that be possible?

>3) You won't be able to map non-gamepad inputs to actions; this would only work for gamepads, which is fairly specific.

A gamepad profile doesn't contain non-gamepad inputs, does it? So I'm not sure what you mean.

>4) [...] Remapping the button index internally is like trying to have keyboard remapping by setting the "q" key to point to the "a" key's scancode; it's just easier to have the action point to the "a" key in the first place.
>
>Using InputMaps would solve all of these problems. [...]

All it asks is code. You can argue it is "easier" to use InputMaps, but that wouldn't actually solve everything, as it should be possible to define gamepad buttons without it. In my opinion that would be the raise of another problem instead.

>So, you don't have to use InputMaps if you don't want to, of course, but unless there's a rather good reason, I'd say it's the recommended approach when checking for inputs, especially when looking into input remapping.

Some inconsistency here. You can't say that I can choose not to use InputMaps if all you say is that the approach should be to use InputMaps...

I'm still curious what your findings are about the approach I was suggesting. It seems that you misunderstood as you were talking about defining the profile you are currently using, while I was talking about defining a profile you are not yet using.

**Comment by SolarLune** [comment]
> Only when you would be changing indices on the fly. But in my example I tried to explain that you should first create a new profile and define that profile, while the current profile is still active. Not until you confirm any changes being made, the new profile is set.

OK, so that snippet has the new profile's "X" button being hard coded to another button. Any action that checks the "X" button would then also be changed, so there's no way to have two bindings that both, at the beginning, use the "X" button, use different buttons later. Whether you're using InputMaps, or just checking the "X" button itself, rebinding it is hard binding it to another button. That means that other actions would also be rebound. Unless I'm misunderstanding something?

> Why wouldn't that be possible?

Because in the example above, you're mapping the name of a button, "X", to another button index (one that's being pressed). Axes and the hat can't be assigned like this (i.e. you can't just plug axis 0 into the btnToCode line). I mean, it's possible to bind axis and hat pushes to buttons, but that's extra work and code for something that InputMaps does already.

>  A gamepad profile doesn't contain non-gamepad inputs, does it? So I'm not sure what you mean.

Basically, this entire rebinding solution is just for gamepads. This doesn't cover the keyboard or mouse, so that's additional rebinding code that you'll have to add. With InputMaps, you can bind actions to keyboard, mouse, or gamepad actions, so it's just easier to use (and, of course, less additional code).

> All it asks is code. You can argue it is "easier" to use InputMaps, but it's not impossible to make it work without having to use InputMaps. And using it wouldn't actually solve everything, as it raises another problem instead: defining the gamepad buttons now completely relies on InputMaps.

When defining InputMaps, you're not defining the gamepad buttons. You're defining what the buttons do. The gamepad basically doesn't change; what the player wants the gamepad to do changes. When you set up a profile, you're setting up a "blank slate" that represents the controller, to which you assign actions later.

And I don't see how it's a problem that InputMaps are being used. You've never outlined to me what the problem is with using InputMaps.

> Some inconsistency here. You can't say that I can choose not to use InputMaps if all you say is that the approach should be to use InputMaps...

No, I can. Like I said, you can do as you like, I would just do, and advise, differently. You know your game the best. I personally don't see why you wouldn't want to use InputMaps, especially if you want input remapping; that's what it's there for. If you can help explain it to me, then I'd understand better, but as of currently, it seems like you're trying to do a lot of work to avoid something that I don't know about.

_______

In any case, none of my opinions on how you implement input rebinding matters.

The bottom line is that we'll need those changes that I outlined previously, regardless of if you're using InputMaps or not.

**Comment by rafcolson** [comment]
>OK, so that snippet has the new profile's "X" button being hard coded to another button. Any action that checks the "X" button would then also be changed, so there's no way to have two bindings that both, at the beginning, use the "X" button, use different buttons later.

You didn't follow the example. I also said that the new "MyProfile" should be an 'empty' profile. This means that no indices have been set, everything is ```null```. So when "X" is hard coded to 0 for example, there is no other 0. Of course, in order to make it work every ```null``` should be ignored afterwards.
```java
public void profile(String name){
	...
			for (Integer code : profile.btnToCode.values()){
				if (code != null)
					profile.codeToLog.put(code, new GdxProcessor.UpDownLog());
			}
	...
```
>I mean, it's possible to bind axis and hat pushes to buttons, but that's extra work and code for something that InputMaps does already.

If it's possible than the extra work or code won't matter. What matters is that we should give developers the freedom to not use InputMaps for setting up profiles. If you say that using InputMaps as a work-around, is doing things, okay, but it is not the same thing. You can't even call it setting up a new profile.

>Basically, this entire rebinding solution is just for gamepads. This doesn't cover the keyboard or mouse, so that's additional rebinding code that you'll have to add. With InputMaps, you can bind actions to keyboard, mouse, or gamepad actions, so it's just easier to use (and, of course, less additional code).

I don't understand what you are trying to say.

>And I don't see how it's a problem that InputMaps are being used. You've never outlined to me what the problem is with using InputMaps.

Yes I did. I said: "But in my opinion BDX's input shouldn't rely on it, as it would narrow down our options." And you agreed that this was a valid argument.

Again, I'm not against using InputMaps. But I am against narrowing down our options. I also don't like work-arounds in a program's code-base, especially when those aren't absolutely necessary, which in this case is true, as you confirmed that nothing's impossible.

>Like I said, you can do as you like

No I couldn't. Doing as I like is only possible if BDX provides the infrastructure for me to define and set new profiles to a gamepad. The reason I started this issue was first to ask you guys if it would be justified to add such a feature, and if so, to ask your help, because you wrote the related classes in the first place.

>I personally don't see why you wouldn't want to use InputMaps, especially if you want input remapping; that's what it's there for.

I don't want to remap input, I want to be able to 'easily' define a custom profile before setting it with ```Gamepad.profile(Profile p)```. But every time I say this, I hear "Just use InputMaps. What's wrong with InputMaps?"  It's a bit of a vicious circle.

>If you can help explain it to me, then I'd understand better, but as of currently, it seems like you're trying to do a lot of work to avoid something that I don't know about.

I'm not against using InputMaps. But I am against narrowing down our options. I also don't like work-arounds in a program's code-base, especially when those aren't absolutely necessary, which in this case is true, as you confirmed that nothing's impossible.

Do you agree that unnecessarily forcing the user to use InputMaps is something we should avoid? 

>In any case, none of my opinions on how you implement input rebinding matters.

I had hoped that you would help me with this, but it's okay if you don't. I respect your decision.

**Comment by SolarLune** [comment]
OK, I think I'm kinda getting it.

Firstly: I never told you - you already can define your own Profiles. I thought you knew already. Sorry about that!

```java
static public Profile SNES(){
		
	Profile p = new Profile("SNES");

	p.btnToCode.put("x", 0);
	p.btnToCode.put("y", 3);
	p.btnToCode.put("a", 1);
	p.btnToCode.put("b", 2);
	p.btnToCode.put("l", 4);
	p.btnToCode.put("r", 5);
	p.btnToCode.put("start", 10);
	p.btnToCode.put("select", 9);

	p.axes.put("lx", new Axis(1));
	p.axes.put("ly", new Axis(0));
		
	p.btnToCode.put("left", -200 - p.axes.get("lx").code);
	p.btnToCode.put("right", 200 + p.axes.get("lx").code);
	p.btnToCode.put("up", -200 - p.axes.get("ly").code);
	p.btnToCode.put("down", 200 + p.axes.get("ly").code);

	return p;
		
}
```

Then you just add it to the Gamepad's profiles hash map and call profile() with it.

Secondly: I agree that we shouldn't force InputMaps on people to check for input, but I also think we shouldn't add a lot of code to do gamepad-based remapping. We should take advantage of the code we already have. If a user wants to have action to input binding and remapping, that's what InputMaps are for.

If they do not want to go with InputMaps for some reason, they can now manually remap the controls of an existing profiles, or create a new profile themselves.

I think it'd be too much unnecessary code to add the ability to allow the user to map non-buttons to buttons. So if they wanted that and don't want to use InputMaps, they can make their own solution.

**Comment by rafcolson** [comment]
>Firstly: I never told you - you already can define your own Profiles. I thought you knew already. Sorry about that!

I knew that you can define a profile for a gamepad you own. But I nor anyone else will own every gamepad on the market. That's why I made the suggestion to add functionality to be able to define a Gamepad.Profile by pressing buttons on my gamepad.

Anyway, it's clear now that you don't agree with this suggestion and that's okay.

**Comment by SolarLune** [comment]
OK, so some time passed, and you mentioned in the previous thread (#739):

> we should provide of an easier way to define gamepad profiles as was mentioned earlier in #564. The alternative would be to do research on various gamepads (for every operating system).

Now, I agree that we should at least have a manageable controller, though we wouldn't have to do research on various gamepads for every system. We could just implement a generic profile with a large number of buttons and axes, and generic terms for the inputs in the profile (i.e. "0" instead of "x", "axis0+" and "axis0-" instead of "ls-left" and "ls-right", etc). 

I don't know about defining gamepad profiles themselves. I guess it's just another way to resolve the "custom remap" problem - either ask the player what button "jump" is (current), or ask them what button "Xbox A" is (your idea, right?). 

Are there additional use cases where customizing joystick profiles would be useful?

**Comment by rafcolson** [comment]
I understand what you are saying. InputMaps can be a means to define keyboard, mouse and gamepad "profiles".

**Comment by SolarLune** [comment]
> So with adding a generic profile, do you mean that we should have just one Gamepad profile, and lose XBOX360 and XBOX profiles?

No, we could just add a generic profile, in addition to the existing ones. People could select their profile in the game, however the developer wants to implement it (e.g. they could select "X-Input / XBOX 360", "XBOX" (though I don't know if wired original XBOX controllers really exist?), and "Generic"). 

They are all functionally the same, it's just that "Generic" has more buttons and axes to cover most possible gamepads, no sticks, and they're not labeled in the profile by the input name on the gamepad (i.e. "2" instead of "b").

**Comment by rafcolson** [comment]
So it would be a two-way street. It's either using this generic profile in combination with InputMaps, or it's using predefined profiles, without the option to let the player define what's 'up', 'down' and so fort.

Because:
>If I set the profile to "XBOX" during the game, what happens is that a new profile is defined and set. **This doesn't change what action "X" maps to in InputMaps.**

I hope you see why I have the opinion that defining gamepad profiles in BDX is somewhat ambiguous. Ideally, we should be able to switch to XBOX360, XBOX, ... Gamepad Profiles AND be able to define custom Profiles at the same time. But right now, this is not possible, for the aforementioned reason. (If I'm not mistaken, because I'll admit I don't quite understand everything about BDX controllers).

**Comment by SolarLune** [comment]
> It's either using this generic profile in combination with InputMaps, or it's using predefined profiles, without the option of letting the player define what's 'up', 'down' and so fort.

No, you would be able to use the generic profile without InputMaps.

And I didn't catch this:

> The default profile is "XBOX360". If I set the profile to "XBOX" during the game, what happens is that a new profile is defined and set. This doesn't change what action "X" maps to in InputMaps. So it seems illogical to me to resort to InputMaps when setting up other profiles.

No, when you set the profile to "XBOX", it sets the current profile for the gamepad to the XBOX one stored in the Gamepad's profile hashmap - a new profile isn't created when you switch profiles. The two default profiles (XBOX and XBOX360) are created and stored in the BDX's Gamepad class's init() function.

You can create your own custom profiles now, so I don't know what you mean by "be able to switch profiles and be able to define custom ones at the same time".

____

So I still don't think I fully understand what you want to do. Perhaps you should present a use case, and @GoranM could weigh in on his thoughts?

**Comment by rafcolson** [comment]
>So I still don't think I fully understand what you want to do. Perhaps you should present a use case

Alright. I'll do that when I can. Can take a while though. Closing for now.

**Comment by SolarLune** [comment]
Hey, I submitted a PR for a generic gamepad profile. Check it out and lemme know if it's usable at all for your purposes.

**Comment by rafcolson** [comment]
Thanks. As soon as I can I'll make the time, I'll let you know. But don't wait for me to merge this.
