### ISSUE TITLE
Issue: gdx can't find required jars for font gen

### ISSUE THREAD

**Issue by Lucrecious** [GoranM/bdx#568]
I followed the install instructions carefully for bdx, however, when I try to export and run a bdx project with text I get an exception:

Exception: Font gen: Can't find required gdx jars

**Comment by SolarLune** [comment]
Yo! Hmm... I have a few questions.

1) What font?
2) Does it work with the default Blender font?
3) What is the entire message from the command prompt?
4) What OS?

**Comment by Lucrecious** [comment]
Hey!
1 and 2. Blender default font.
3. http://www.pasteall.org/65696
4. Windows 10

**Comment by rafcolson** [comment]
Did you try running the game without any text objects first?

**Comment by Lucrecious** [comment]
Yes, I ran the game without text objects - it worked fine. I ran the game with one text object - exception.

**Comment by SolarLune** [comment]
What version of BDX are you using, and would you mind sharing a blend file? Also, does the problem arise with the demo scene (Sacky)?

The problem comes in because BDX is looking for the LibGDX jars that gradle downloaded, but they aren't being found... If you wanted to test things out, go to line 696 of exporter.py and print out the variable `gcr`. Then look in the folder that you printed out and see if you can find the jar files. It might be a misspelling or something that's tripping you up. 

To do this, go find the BDX add-on folder (not the zip that you installed it from), and edit the exporter.py file. The file should be in `/[your user name]/appdata/roaming/blender foundation/blender/[your blender version]/scripts/addons/bdx`. Print it out, and then restart Blender and check the console when you try to export the game again.

**Comment by Lucrecious** [comment]
I'm using the latest version of BDX (0.2.3) and the latest version of Blender (2.76). The problem also arises on the default Sacky the Text works surprisingly (when I create a new project). I must have done something weird on my other .blend...

I don't know which jar files I'm looking for, by the way. The folder that gets printed is:
C:\Users\[my user name]\.gradle\caches\modules-2\files-2.1
In this folder there are no .jars.
In the com.badlogicgame.gdx, there are also no .jars, just more folders (for gdx), I searched:
'font', 'gen' and 'text' but got nothing.

Where are the jars supposed to be?

Here's a link to the .blend:
http://www.pasteall.org/blend/40911


Also, I completely forgot to mention a potentially important detail:
Removed all instances of android project stuff in the gradle.build, local.properties and the setting.gradle (like I deleted actual lines).

I wasn't able to open up the grade.build in IntelliJIDEA because it couldn't find the android sdk stuff, which I didn't care about.

Here is the gradle.build:
http://www.pasteall.org/65706

local.properties was left empty after I took out the android-sdk blender location.

Here is settings.gradle:
`include 'core', 'desktop', 'ios', 'html'`
I took out 'android'

**Comment by SolarLune** [comment]
OK, that explains some stuff. The jar files that BDX requires are in that folder. They're the

- `gdx-VERSION-.jar`,
- `gdx-platform-VERSION-natives-desktop.jar`,
- `gdx-backend-lwjgl-VERSION.jar`

files. Make sure they're there (the first one is in the /com.badlogicgames.gdx/gdx/1.7.2/ccf.....` folder, for me).

Also, you might want to undo that, uh, mangling of the gradle files. You should be able to open the gradle.build file just fine through IDEA, regardless of if it can find the Android SDK. I don't have my Android SDK set up for my project, I don't think, and I can open my build.gradle file in IDEA, though I don't think I have gradle set up for use in IDEA.

In any case, if you can't undo the gradle stuff, just recreate the project and copy your assets over. If it works, then you know the problem isn't finding the jar files, but rather with those edits to the gradle files. Just getting IDEA to open your build.gradle file would then be your problem.

**Comment by Lucrecious** [comment]
The problem was messing with the gradle stuff.

Thanks!
