### ISSUE TITLE
Bug: GameObjects Re-Initialized On Parent

### ISSUE THREAD

**Issue by SolarLune** [GoranM/bdx#615]
Hey, there. 

So basically, it would appear that Gameobjects can be initialized twice - once when the GameObject is added, and then again when parented to an object.

[Here's an example blend file.](https://www.dropbox.com/s/q3puh7anutacvyv/ParentingProblem.blend?dl=0)

Any ideas on what could be the cause of this? I looked through the codebase, but didn't see anything...

**Comment by rafcolson** [comment]
I'm not able to look at it now, but I will once I've completed a fresh installation of my pc.

**Comment by GoranM** [comment]
> I looked through the codebase, but didn't see anything...

I'm not really sure what you mean by that, because you can't just "look through the codebase" and expect something to just catch your eye. I assume you actually have a debugging strategy that you follow ... ?

Here's mine:

If GameObject.init is being called twice, the issue is probably in the place where it's actually being called. In BDX, Scene.initGameObject is a place where that call occurs:

```java
	private void initGameObject(GameObject gobj){
		gobj.init();

		ArrayList<GameObject> children = new ArrayList<GameObject>(gobj.children);

		for (GameObject c : children){
			initGameObject(c);
		}
	}
```

And at this point, it should be fairly obvious:

Clone.init is called when scene.add("Clone") is called in Sacky.init, and then once more when Sacky's children are initialized (because Clone was added as a child before that happened).

**Comment by SolarLune** [comment]
Hah, of course I don't literally just look through code when I squash bugs. That would be silly. I was walking back through the init function calls like you, but didn't see where the bug was coming from.

In any case, what's the proposed solution? Keep a variable that keeps track of whether an object was already initialized?

**Comment by GoranM** [comment]
That sounds fine.

**Comment by SolarLune** [comment]
PR submitted.

**Comment by SolarLune** [comment]
PR merged, so I'll close this now.
