### ISSUE TITLE
Suggestion: Forum

### ISSUE THREAD

**Issue by dualjack** [GoranM/bdx#624]
Hey buddies!
Have you ever think about creating small forum with 3-5 categories, where we - the community, could post for example new components?

It would look like this:
- General discusion
- Suggestions
- Community made components
- ...

**Comment by SolarLune** [comment]
Hmm, I dunno. We already have a subreddit at /r/bdx. Is that not sufficient for the needs you imagine?

**Comment by rafcolson** [comment]
I think that would be useful. To be honest I don't like Reddit. As far as I know there's no way to have subforums, and creating posts have no preview, and the UI and graphical layout not pleasant for the eye (in my opinion).

Would it be an idea to ask BlenderArtists for a BDX subforum?

**Comment by SolarLune** [comment]
That's true that subreddits are pretty fixed... We could also post builds of the engine up for free on itch.io - I think every game and application can have its own forum there, but I don't know if they can have subforums.

Asking Blenderartists might work, but I don't know if there are nearly enough BDX users to justify a brand new set of subforums for them...

**Comment by dualjack** [comment]
Reddit is not a good place to post things like this :)

**Comment by SolarLune** [comment]
Well, I dunno. General discussion and suggestions would fit in fine on Reddit. Custom components, maybe not so much, as it would require posting new threads each time a Component is updated to properly show it all. But it's not like it couldn't (or wouldn't) work.

**Comment by GoranM** [comment]
For now, I think r/bdx is good enough. I'm not sure if the community will ever grow to a point where we actually need something as structured as a forum, but even then, I feel like a few additional subreddits would probably work just as well.

As for the look and feel: The layout can be changed, if you guys really hate the default.

> General discussion and suggestions would fit in fine on Reddit. Custom components, maybe not so much, as it would require posting new threads each time a Component is updated to properly show it all.

I actually think it's more straightforward to post a new thread.

With a monolithic forum thread, in addition to making a new post, you're expected to change the title, and edit the first post so that it contains the latest update information (for people who tend to read from page one, instead of just going to the latest post).

**Comment by SolarLune** [comment]
Hey, I don't think we're gonna get a forum (at least anytime soon); we probably can stick with a subreddit for now, anyway. Maybe if the community gets larger, we can consider a forum.

Is the issue OK to close?

**Comment by GoranM** [comment]
Yes. Closing.
