### ISSUE TITLE
Error when running standalone .jar

### ISSUE THREAD

**Issue by Lucrecious** [GoranM/bdx#651]
Here's the entire trace:
http://www.pasteall.org/69198

I created this .jar with the command on windows:
gradle.bat desktop:dist

Any ideas what might have gone wrong?

**Comment by SolarLune** [comment]
Looks like it can't find the scene file "bdx/scenes/menu.bdx". Are you able to load the menu scene when running from Blender?

**Comment by Lucrecious** [comment]
Yes, everything works fine on Blender, it's only when I try to open the jar after creating it with
gradlew.bat desktop:dist

**Comment by SolarLune** [comment]
Hmm... I just tried distributing like this and it worked fine for me... Is the menu the active scene in the blend file, or are you setting it via code?

If you open the jar file as a zip file, and look through it, does it look like the scene file exists? 

Also, what OS, and what Java version are you using?

Finally, does that command work with the default demo scene for you?

**Comment by Lucrecious** [comment]
Ahh, alright, so I think I found a bug possibly! Thanks Solar!

I checked if the scene existed in bdx/scenes/menu.bdx, and technically - it didn't, bdx/scenes/Menu.bdx existed.

I do in fact remember that when I created the menu scene, it was initialized named "Menu", but after a while I named it to "menu". I also know I've ran the game multiple times through Blender when it was called "menu". Maybe this happens to you, too? Can you try to reproduce? (Try naming a scene in Pascal case like, "Menu", and then renaming it later to lower case, "menu").

I'm running the latest version of Bdx, and this is a projected created by the original exporter.py (I haven't touched it).

After I renamed Menu.bdx to menu.bdx, it seemed to work properly!

**Comment by SolarLune** [comment]
Hm, when I renamed my scene to change the case, it just created a new scene file. This is probably because I'm on Linux, and Linux is case-sensitive (unlike Windows). I'm guessing Java's file-loading is case-sensitive, though, and that's why you had the problems (Blender exported the first scene as being "menu.bdx", but only "Menu.bdx" existed in Windows).

A solution to this would be to delete the scenes in the scenes folder before exporting the game, and is something that we've been meaning to do for awhile now, I think.

PR submitted.

**Comment by SolarLune** [comment]
Hey, that PR was merged, so I think it should solve this so this problem doesn't arise again.

**Comment by Lucrecious** [comment]
Awesome. Thanks :D
