### ISSUE TITLE
About External Libraries

### ISSUE THREAD

**Issue by JBird62** [GoranM/bdx#672]
While using BDX and having a small experience with LibGDX, I attempted to import other jar files into the BDX lib directory for use of external GUI elements. I have failed with every attempt to use any external libraries; is this possible to accomplish and I am having errors in my code, or do I need to find another route? 
For reference, The java program I currently use (no games or animation, just a GUI) utilizes java swing components and is written in netbeans. I wanted to integrate BDX into the current netbeans project. Or, I thought maybe I could use LibGDX GUI Compenents inside of BDX and rewrite my current GUI. Is this possible?

Thanks in advance!

**Comment by SolarLune** [comment]
Well, what was the errors you got?

There shouldn't be any problems in using external libraries; BDX as a whole can be split up into basically two pieces - the Blender Add-On, which handles exporting, and the API, which handles the engine flow and added API. BDX just uses vanilla LibGDX to handle the engine flow (and jBullet for the physics), so anything that you could use with LibGDX should work under BDX.

However, integrating BDX into another project won't work, as it requires that you export data from Blender to load into BDX, and that you run the BDXApp as the main application. So you can't just, say, `import com.nilunder.bdx.*` at the top of another main application .java file and go from there. 

You have to be working with BDX as the base of your application to use it. If you're trying to add a GUI using other elements to an existing BDX application, that should work, though you might have to alter [the BDX engine loop](https://github.com/GoranM/bdx/blob/master/src/com/nilunder/bdx/Bdx.java#L238) to draw the GUI elements (not sure if plugging it into a GameObject-derived class will work).

**Comment by GoranM** [comment]
Assuming it's possible, I don't think it would be easy to use swing in combination with BDX; Everything in BDX is drawn by LibGDX, via OpenGL, and you would have to effectively create a swing main application loop in a different thread, and find a way to draw swing widgets into an OpenGL framebuffer.

It would be easier to simply create whatever UI elements you need yourself, on an overlay scene (usually, people would prefer doing that, because they want their UI to have a custom look/feel).

**Comment by JBird62** [comment]
Thank you! @SolarLune  @GoranM 
   The main element I was looking to use was a progress bar, timer bar, and a scroll panel. I will do away with the idea of java swing then. I will look into creating custom widgets of the three elements. 
@SolarLune I was getting a version 1.6 compatibility error. The errors I was receiving must have been from trying swing without attempting what Goran was explaining. I will attempt plugging LibGDX Gui elements into a GameObject-derived class. Thank you both for the help. You gave me a lot to think about and experiment with. 
I appreciate Yall's time.

**Comment by SolarLune** [comment]
No problem! Plugging in the LibGDX GUI elements might work (particularly in an overlay scene (a scene on top of all others)), but it might would be easier to just do it in-engine using planes, text, and so on to construct your UI "items" yourself.

Anyway, glad to be of service. If your issue's solved, feel free to close it. Otherwise, you can keep it open.

**Comment by JBird62** [comment]
Ok, sounds good. Thanks again.
