### ISSUE TITLE
Bug: Android *.apk won't run since LibGDX 1.9.2 update

### ISSUE THREAD

**Issue by rafcolson** [GoranM/bdx#691]
Since [the LibGDX 1.9.2 update (27th of April)](https://github.com/GoranM/bdx/commit/c9166309fef09346494c74f5f42150a252427192) *.apk will crash, even when it is assembled without any errors.

ADB logcat (Android Studio) mentions this error:
```java
06-01 23:45:45.525 6760-6760/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                 Process: com.raco.test, PID: 6760
                                                 java.lang.RuntimeException: Unable to instantiate activity ComponentInfo{com.raco.test/com.raco.test.AndroidLauncher}: java.lang.ClassNotFoundException: Didn't find class "com.raco.test.AndroidLauncher" on path: DexPathList[[zip file "/data/app/com.raco.test-1/base.apk"],nativeLibraryDirectories=[/data/app/com.raco.test-1/lib/arm, /vendor/lib, /system/lib]]
```

Reverting the update seems to fix the issue -> [(#437) revert of LibGdx 1.9.2 update & fixes](https://github.com/rafcolson/bdx/commit/65bc93fb208ddf3c31b7573c1220a6e80a9e7531). My guess is that this has something to do with `createproj.modify_build_gradle()`.

**Comment by GoranM** [comment]
> My guess is that this has something to do with createproj.modify_build_gradle().

That method is just an alternative way by which we create a build.gradle file that contains all our required dependencies; Instead of using a pre-generated build.gradle that defines our required dependencies (as we did before), we now add relevant dependencies to a default build.gradle file that's already in the project (originally generated by gdx-setup.jar).

You can compare a build.gradle file of a project created using a pre-update version of bdx, with a build.gradle file of a project created using a post-update version of bdx.

They should both basically describe the same dependency structure.

**Comment by rafcolson** [comment]
Yes. I confused this with the `build.gradle` in the project's `android` folder. The version after the LibGDX update generates a different path for the `AndroidLauncher`:
```java
commandLine "$adb", 'shell', 'am', 'start', '-n', 'com.raco.test.android/com.raco.test.android.AndroidLauncher'
```
Whilst the old version gives:
```java
commandLine "$adb", 'shell', 'am', 'start', '-n', 'com.raco.test/com.raco.test.AndroidLauncher'
```
I'll be checking if replacing this line solves the issue.

**Comment by rafcolson** [comment]
PR submitted.

**Comment by rafcolson** [comment]
PR merged. Thanks.
