### ISSUE TITLE
Bug: SpriteAnim.frame() returns < 0 for negative speed

### ISSUE THREAD

**Issue by SolarLune** [GoranM/bdx#694]
Hey, there. 

So if SpriteAnim.speed is less than 0, then `frame()` returns negative numbers (i.e. 0, -1, -2, and then it wraps).

I can fix this, but something else that came up is that SpriteAnim ignores the first frame of the animation when you first play it (so when playing an animation that goes {0, 1, 2, 1}, it would display {1, 2, 1, 0, 1, 2, 1, 0...}). Any ideas on this?

**Comment by rafcolson** [comment]
>SpriteAnim ignores the first frame of the animation when you first play it (so when playing an animation that goes {0, 1, 2, 1}, it would display {1, 2, 1, 0, 1, 2, 1, 0...}).

It doesn't appear that way on my end. I replaced `Sacky.java` with:
```java
import com.nilunder.bdx.*;
import com.nilunder.bdx.components.SpriteAnim;

public class Sacky extends GameObject{
	
	public GameObject visual;
	public SpriteAnim sa;
	
	public void init(){
		visual = children.get("G_Sacky");
		sa = new SpriteAnim(visual, 32, 32);
		sa.add("startle", 0, new int[]{0, 1, 2, 3}, 1, true);
		sa.play("startle");
		visual.components.add(sa);
	}
	
	public void main(){
		if (Bdx.keyboard.keyHit("space")){
			Bdx.restart();
			System.out.println("RESTARTS");
		}else{
			System.out.println(sa.frame());
		}
	}
	
}
```
This returns: `-1, 0, 0, 0, ... , 1, 1, 1, ... , 2, 2, 2, ....`.

However, the first frame is always `-1`. I'm not sure why..

**Comment by GoranM** [comment]
A packed .blend that demonstrates the bug/s clearly would be helpful.

**Comment by SolarLune** [comment]
OK, I guess we should start with the first problem, then. Here's the problem blend file.

https://www.dropbox.com/s/dybuesdby5taof3/NegativeSpeedProblemPacked.blend?dl=0

**Comment by GoranM** [comment]
The important thing to note here is that the actual in-game frames are displayed in correct sequence, both when speed is positive, and when speed is negative.

So, if frame() is returning incorrect values, it's highly likely that the bug is contained within that method.

Hint: Remember why you changed the code from simply returning the `active.playHead`, to returning `active.playHead - 1`? What does that assume about playback direction?

**Comment by SolarLune** [comment]
> So, if frame() is returning incorrect values, it's highly likely that the bug is contained within that method.

That's a reasonable assumption, but the fact that `frame()` returns -2 means that there's more to it than that. Possibly the frame() function is returning "one less than it should", but also SpriteAnim isn't updating the playhead as it should be. It should never be below zero, which it apparently is, as `frame()` is returning the playhead - 1 (or -2). 

So there's two points of interest here.

**Comment by GoranM** [comment]
> It should never be below zero

The implementation of Animation.onLastFrame implies otherwise.

**Comment by SolarLune** [comment]
Ok, so fundamentally, the playhead can go below 0. Is that intentional? Because that doesn't seem right.

**Comment by GoranM** [comment]
> Ok, so fundamentally, the playhead can go below 0. Is that intentional?

There wouldn't be an explicit check for `playHead == -1` if it wasn't.

> that doesn't seem right.

It seems right to me; The logic of the system expects exactly that.

**Comment by SolarLune** [comment]
OK, I don't quite see why you'd design it to allow the playhead to go below 0 when you could wrap it to be within expected range of the animation length.

**Comment by rafcolson** [comment]
At some point I made some changes to the code so 'frame()' would just get the 'playhead'. Even so, it gives the same results. I don't quite understand why because I made sure that the lastFrame would always be the last frame at initialization. So it couldn't be -1. @GoranM If 'frame()' would get the 'playhead', wouldn't it be the next frame? Because the playhead of the next frame is defined before the main loop? Ideally the playhead would be defined after 'spriteAnim.main()' somehow.

**Comment by GoranM** [comment]
> If 'frame()' would get the 'playhead', wouldn't it be the next frame?

Yes, it would, and that's why frame() doesn't just do that.

Also, note that I never suggested that frame() should do that.

> OK, I don't quite see why you'd design it to allow the playhead to go below 0 when you could wrap it to be within expected range of the animation length.

Wrapping it to animation range introduces other complications, like having to update the playhead outside the component (raf touched on that a bit), or having to create additional state.

Anyway, as I hinted previously, the current implementation of frame() assumes that animation direction will never change, and that's why you get incorrect values when it's reversed.

**Comment by SolarLune** [comment]
> Wrapping it to animation range introduces other complications, like having to update the playhead outside the component (raf touched on that a bit), or having to create additional state.

Could you explain?

> Anyway, as I hinted previously, the current implementation of frame() assumes that animation direction will never change, and that's why you get incorrect values when it's reversed.

But that's an incorrect implementation, because one could want to play an animation (like a door opening) backwards.

**Comment by GoranM** [comment]
> Could you or rafcolson explain?

The SpriteAnim component needs to get and display the current frame, based on a playHead that needs to update properly.

If you start with updating the playHead, and then displaying the frame it references as "current", that would skip the initially set frame. You can play tricks like setting the playHead to an "earlier frame" (which could be out of bounds), initially, and for every call of the frame setter, but that's not really simpler than compensating in the getter (as we do now). Also, you would have to explicitly calculate the next frame in order to figure out if you're going to be out of bounds (so you could properly reset, loop, etc), which is not something we have to do in the current setup.

You could update the playHead outside the component, to avoid the need for setting an "earlier frame", but that implies SpritAnim-specific code somewhere in the engine, which is generally more complex than a self-contained component that can just update itself.

> But that's an incorrect implementation

That's my whole point. 

The implementation of frame() is incorrect, because it makes the wrong assumptions about the direction of playback, and that's the problem that needs to be fixed.

**Comment by SolarLune** [comment]
OK, I see. Thanks, I think I got it now!

PR submitted.

**Comment by SolarLune** [comment]
OK, that should do it. PR was merged. Thanks!
