### ISSUE TITLE
Camera does not follow object along Y axis....

### ISSUE THREAD

**Issue by akash55** [GoranM/bdx#699]
![bdx cam](https://cloud.githubusercontent.com/assets/20142360/16357540/0c0a1702-3b17-11e6-98ee-39c6c4e9cd93.PNG)

I am creating a racing game. The issue is camera can follow the object but not along Y axis of object.
If you have any idea.....please help me...

**Comment by gerardogc2378** [comment]
@akash55 try camera parenting with your player or object to follow, camera is child of your player

![parenting](https://cloud.githubusercontent.com/assets/24534/16358341/f17b9ac8-3ad5-11e6-945c-24b59e0a8123.png)

**Comment by SolarLune** [comment]
@akash55 - Logic bricks don't work in BDX. All logic is coded through Java.

**Comment by SolarLune** [comment]
@akash55 - Oh, and please don't open issues here on GitHub for questions regarding use of BDX. We have a subreddit for that [here](https://www.reddit.com/r/bdx).

**Comment by akash55** [comment]
This issue is also related to feature of BDX. Basically, BDX is developed to support all features of  Blender. In blender this issue is solved by simply adding a Camera Actuator to follow the object. I want to develop it in BDX, i.e, in Java.
@gerardogc2378  as you suggest me to parent camera with object. I already tried this. It is working but problem is when object is jumping camera also doing so. Because of the object is type of RigidBody.
So i want Camera follow the object without parenting using java code. I also did it using camera.position(object.position().x,object.position().y-15,10); 
Camera is following the object without jumping, but when object is rotating, camera doesn't.

**Comment by akash55** [comment]
@SolarLune  Can you tell me how to develop Blender's Camera Actuator features?

**Comment by SolarLune** [comment]
> Basically, BDX is developed to support all features of Blender. 

I don't think it is, actually. We're adding in things that assist development and that are useful, and leaving out things that either aren't helpful or that influence the engine too heavily (speed, overall codebase size, or otherwise). In my opinion, visual scripting (logic bricks particularly) just can't do code as efficiently as normal code (Java or otherwise), and the cost of adding full actual logic brick support to the engine is prohibitive. Maybe @GoranM can weigh in on his thoughts as well.

> Can you tell me how to develop Blender's Camera Actuator features?

For the Camera actuator to work, we'd have to build logic brick support in the system. That means that we'd probably do something like export logic brick information to JSON with the other scene data, translate each brick with its parameters and links to Java code, and build object behavior out of these translations. It's, in my opinion, too much work and code for simply another, less developed means of coding the game.

It's not impossible to do, though, if you wanted to do it yourself.

As for the way to do this in pure Java, you could use the [GameObject.axis()](https://github.com/GoranM/bdx/wiki/API-GameObject#axis-string) function to get the direction behind the GameObject, add that to its position, and set the Camera's position to that. If you want it to be smooth instead of instant and precise, you could look up lerping as well, which would be something like:

```java

--Camera.java--

Vector3f targetPosition = player.position().minus(player.axis(1).mul(4));  // The target position is the player's position minus 4 X the player's front axis

Vectort3f diff = targetPosition.minus(position()).mul(0.1f);  // 0.1 is how much of a percentage of the difference between the target position and the camera's actual position to move

move(diff);

```

Oh, or you could just add a [Track](https://github.com/GoranM/bdx/wiki/API-Track) component to have the Camera look at the target object, if that's the only problem.

**Comment by rafcolson** [comment]
@akash55 
Take a look at the `follow.java` script in [this example blend](https://www.dropbox.com/s/4jdek3jxova6zd9/notes.blend?dl=0) . It may be what you're looking for. I don't see BDX will support logic bricks at any time.

**Comment by GoranM** [comment]
BDX was not, is not, and will probably never be "developed to support all features of Blender".

-

> the cost of adding full actual logic brick support to the engine is prohibitive

In theory, it's possible to create an external, and largely independent program that can "compile" blender's logic brick data into Java code that uses the BDX api.

However, I don't think it would be worth the effort, since logic bricks (and visual languages in general) have so many fundamental limitations.

**Comment by SolarLune** [comment]
I suppose this can be closed?
