### ISSUE TITLE
Question: SpriteAnim.animations

### ISSUE THREAD

**Issue by rafcolson** [GoranM/bdx#712]
I see that `SpriteAnim.animations` is a `public` field. Is there any reason for why this is not exposed in the API?

Reason I ask is because I found it to be useful to have access to the `HashMap` in case I just want to play the first which is also the only animation.

Edit: Hmm, it's not easy to get the first and only animation:
```java
import java.util.ArrayList;
import com.nilunder.bdx.components.SpriteAnim.Animation;
spriteAnim.play(new ArrayList<Animation>(spriteAnim.animations.values()).get(0).name);
```
Edit: I guess it is easier to do this:
```java
import com.nilunder.bdx.components.SpriteAnim.Animation;
for (Animation anim : spriteAnim.animations.values()){
	spriteAnim.play(anim.name);
}
```

**Comment by GoranM** [comment]
Not that I can remember.

**Comment by rafcolson** [comment]
Should it be exposed?

**Comment by SolarLune** [comment]
Sure, why not. I believe I asked to make it public to make it easier to tell which animations are available, and this was after adding the `animationNames()` function, or something to that effect. If the animations hash map is public, then we don't really need the `animationNames()` function anymore.

**Comment by rafcolson** [comment]
>If the `animations` hash map is public, then we don't really need the `animationNames()` function anymore.

I think I'd rather utilize `animationNames()` then for my particular case. Much simpler.
```java
spriteAnim.play(spriteAnim.animationNames().get(0));
```
I can't think of any reason why `animations` should be exposed then. So I'll close this. I didn't know that it existed until now, because it was not exposed in the API either. Maybe `animationNames()` could be exposed?

I'll close this then. Thanks for the help.

**Comment by SolarLune** [comment]
> I can't think of any reason why animations should be exposed then. I didn't know that animationNames() existed until now, because it was not exposed in the API either. Shouldn't this be exposed?

If they're public, they should both be exposed. However, I don't think there's a reason for animationNames() since you should be able to get the names through `spriteAnim.animations.keySet()`, right?

**Comment by rafcolson** [comment]
>If they're public, they should both be exposed. However, I don't think there's a reason for `animationNames()` since you should be able to get the names through `spriteAnim.animations.keySet()`, right?

`ArrayList<String, String>(spriteAnim.animations.keySet())` to be exact. It's more convenient to do `spriteAnim.animationNames().get(0)`, so I would be doing that.

Is there any other reason why you think `animations` should be public? If not `animationNames()` serves our purposes well enough for `animations` to be private, don't you think?

**Comment by SolarLune** [comment]
> ArrayList<String, String>(spriteAnim.animations.keySet()).get(0)

Ah, KeySets don't have the same functions as Lists, so I guess you can't actually `get` anything from a Set. That's surprising.

So I guess the alternative would be `spriteAnim.animations.keySet().toArray()[0]`, which is a mouthful, haha. `animationNames()` is useful, then.

> Is there any other reason why you think animations should be public?

Well, for altering animations, it'd be useful (changing the FPS, of one, for example), though it might be better to alter the speed of the SpriteAnim component than alter the animation's actual FPS values. It'd also be useful to be able to inspect the individual frames of an animation (i.e. look for where frame number "19" shows up), but that's not really possible because the frames are turned to Vector2fs when created rather than kept as integers (which is a bit unfortunate).

**Comment by SolarLune** [comment]
Oh, and an alternative would be to add a `name` property to Animation and turn SpriteAnim.animations from `HashMap` into `ArrayListNamed` and then just do
`spriteAnim.animations.get(0).name

**Comment by GoranM** [comment]
> though it might be better to alter the speed of the SpriteAnim component than alter the animation's actual FPS values

It seems like that would be better.

FPS is more like a notion of how an animation should play at "normal speed", and then speed is actually the multiplier that can be used to set faster or slower playback.

> It'd also be useful to be able to inspect the individual frames of an animation (i.e. look for where frame number "19" shows up)

Couldn't you just look at the sequence definition?

> Oh, and an alternative would be to add a name property to Animation and turn SpriteAnim.animations from HashMap into ArrayListNamed and then just do spriteAnim.animations.get(0).name.

But then setting an animation by name would require a linear search, on every call. I mean, if it's really that important to easily get "the one and only animation", it would be better to just make a method specifically for that.

Although, I'm not convinced that it's necessary, because, in most cases, you know the name ahead of time, and you can just use that.

> Should it be exposed?

I'm fine with whatever you guys decide.

**Comment by SolarLune** [comment]
> Couldn't you just look at the sequence definition?

Well, that would require that I store the frames of the animation in addition to defining them (which isn't hard to do, but it's just an extra step). It seems better conceptually to store the data in the same way the user defines it, and just perform the math when necessary to convert to the data the component actually needs.

**Comment by GoranM** [comment]
I don't really understand why you would need to search a sequence at runtime, but if you can provide a compelling use case, that would justify including the data that makes that possible.

> It seems better conceptually to store the data in the same way the user defines it, and just perform the math when necessary to convert to the data the component actually needs.

Yes, but it's better for performance to just have the required data at hand, instead of having to recalculate it on every frame.

**Comment by SolarLune** [comment]
> I don't really understand why you would need to search a sequence at runtime, but if you can provide a compelling use case, that would justify including the data that makes that possible.

The use case I had I can't quite remember, but it centered around being able to tell what frame indices the animation contains. 

> Yes, but it's better for performance to just have the required data at hand, instead of having to recalculate it on every frame.

I don't know if the performance drop would be a big enough deal to worry about. It's not like BDX would have to perform the math for every frame in the animation; just the one that's displaying at the time, and only on actually changing the frame.

But it doesn't matter too much to me either way.

**Comment by rafcolson** [comment]
>But it doesn't matter too much to me either way.

Me neither. I would just stick to what we have right now and expose `animationNames()` and `animations` for the reasons you had mentioned.

**Comment by rafcolson** [comment]
API updated.
