### ISSUE TITLE
Group Instance Spawning Ignores Group Offset

### ISSUE THREAD

**Issue by SolarLune** [GoranM/bdx#72]
Hey, there. So group offsets are ignored when spawning in a group instance. Objects that make up the group are created based off of the group's center (as far as I can tell), rather than based off of their relative position from the group's offset position / center point (the dot in Blender for group instances).

**Comment by GoranM** [comment]
Technically, not a bug, because this is intended behavior.

I reasoned that most people would want to use link groups to represent an instance of a single master object (where ignoring offset is what one would usually want), so I wrote very simple code to only support that.

To support the complete "link group" concept, as it exists in Blender, would require more code, and I'm not sure if the benefits justify the additional complexity.

**Comment by SolarLune** [comment]
Hm. Well, fair enough, I suppose. Closed.
