### ISSUE TITLE
Bdx game is very slow on Android device.....

### ISSUE THREAD

**Issue by akash55** [GoranM/bdx#733]

**Comment by SolarLune** [comment]
Please ask support questions over on the [BDX subreddit](https://www.reddit.com/r/bdx); GitHub is mainly for issues related to the development of the engine (feature requests, suggestions, bugs, etc). Just the game running slowly doesn't demonstrate anything wrong with BDX particularly.

That said, I'll try helping. What device are you using? What's the game project itself? Is it the basic demo? What does the Profiler say? To see the profiler's settings, enable it in the Game menu in Blender, in the main menu section (top of the screen, by default).

**Comment by rafcolson** [comment]
Hi akash55.

Have you tried profiling your game? You can enable the BDX profiler by checking *Show Framerate and Profile* in the *Game* tab (on the *Info* bar).

Check which subsystems are taking the most time to be processed. If *render* is one of those, you'd probably want to check for *gl calls*. Mobile devices have low-end graphics. A lot of *gl calls* could slow down the game considerably. This has nothing to do with BDX (software), but with hardware.

To enable gl statistics, do:
```java
// at initialization
Bdx.profiler.gl.enable();
```

In my tests frames will drop quickly when the scene has more than 24 objects with physics type STATIC or when the scene has more than 64 objects with NO_COLLISION. So I wouldn't be surprised if this is the source of your issue.

Luckily there are ways to reduce the amount of *gl calls*. If there are a lot of stationary objects in your scene, you could *join* those. Take a look at [this post about performance on low-end devices](https://github.com/GoranM/bdx/issues/437#issuecomment-146987944) and the API for [[GameObject.updateJoinedMesh()|API-GameObject#updateJoinedMesh]].

The source of your problem could also be the excessive use of physics in your game. In such case the BDX profiler should show higher processing times for the *physics* subsystem.

@SolarLune beat me to it, but yeah. It would have been better if you posted your issue on Reddit, because you're probably not sure if this issue is related to the development of BDX. But I hope this reply will give you some pointers on how to go forth.

**Comment by akash55** [comment]
This is the Profiler output

**Comment by rafcolson** [comment]
Gl statistics?

**Comment by akash55** [comment]
here what is outside? Most of time is consumed by "outside"..............

**Comment by rafcolson** [comment]
Have a look in the General Overview in the Wiki.

**Comment by akash55** [comment]
Gl stattistics is enabled in init method.

**Comment by rafcolson** [comment]
Oh my bad. You should also set to visible:
```java
Bdx.profiler.gl.enable();
Bdx.profiler.glVisible(true);
```

**Comment by SolarLune** [comment]
This doesn't look like the demo blend file, but a custom game, right? 

The screenshot you posted shows 59 FPS, and it looks like it's of the game running on desktop. So this doesn't really matter that much. It's doable to profiler here, but you need to profile the game on the device that's giving you trouble.

**Comment by akash55** [comment]
This is the demo blend not a custom game. Yeah, that screenshot was of desktop. When I am running this demo  on mobile, it shows :
 7 FPS  
gl calls =1274
gl draw calls= 23
gl shader switches= 20
gl texture bindings= 7
gl vertex count= 7521
gl triangle count= 2507
and 70% of CPU consumed by "render". How will I reduce the render's time?

**Comment by rafcolson** [comment]
Are all of these objects STATIC objects? What kind of smart phone are you testing on?

**Comment by aliasaila** [comment]
Disabling advanced lighting may help.

`Bdx.display.advancedLighting(false);`

**Comment by akash55** [comment]
@rafcolson one object is of type "rigid body" and others are "static". And smart phone is Samsung  Galaxy Core Prime.

**Comment by akash55** [comment]
I searched this topic on Google, found that Unity games are not rendered at playing time but they use bake method.

**Comment by SolarLune** [comment]
You mean that the lighting is baked? Well, you should be able to bake the lighting to a texture in Blender. Then just apply the texture to the objects you baked. After that, you can turn on shadelessness on objects' materials, turn off advanced lighting, and reduce the number of point, spot, and sun lamps. You might also combine the textures of objects in with the baked lighting texture if you have a diffuse texture and need it for objects (BDX doesn't support multi-texture blending as of yet).

**Comment by rafcolson** [comment]
@one object is of type "rigid body" and others are "static". And smart phone is Samsung Galaxy Core Prime.

Well, I tested with the the Core II which has about the same specs. With advanced lightning turned off, I got [these](https://github.com/GoranM/bdx/issues/437#issuecomment-146987944) results. My Samsung Galaxy J5 (next generation) runs at 20 fps with around about 200 STATIC objects. You can download a test apk [here](https://www.dropbox.com/s/7e7iwrkbhsl9sw8/joiner_single_material_200_STATIC_cubes.apk?dl=0). If you're getting around 20 fps too, that means you probably have turned advanced lighting on still.

**Comment by rafcolson** [comment]
@akash55

So, did the test apk run at 20 fps with around 200 STATIC objects? If so, then the problem should lie somewhere else.

>When I run this demo on mobile, it shows : 7 FPS

What demo?

**Comment by rafcolson** [comment]
@akash55

I'm trying to figure out if this issue is normal or not. It's a little confusing when you're talking about "the demo blend". I doubt that you're talking about the "default blend" as the picture in [this post](https://github.com/GoranM/bdx/issues/733#issuecomment-234733155) shows something else.

So how about performance with the "default blend"? This is the blend with Sacky.

I would like to help to figure out the problem, but if for whatever reason this is not necessary anymore, could you please close this issue? Thanks.
