### ISSUE TITLE
BDX can't detect source files directories down

### ISSUE THREAD

**Issue by SolarLune** [GoranM/bdx#75]
Hey, there. So, it'd be nice for productivity if BDX could detect source files for objects wherever they are in the core/src folder. Currently, they have to be at the end of the java classpath for any of them to be picked up (so a `Player.java` file in `com/username/gamename/gameobjects` won't be used). Could this possibly be implemented?

**Comment by GoranM** [comment]
Could you elaborate a bit on the productivity benefits?

I mean, wouldn't it be easier to just place object classes in `/com/username/gamename`, instead of creating a new subdirectory, and then putting them there?

Organizationally, the "gameobjects" directory seems redundant, because that's what the base directory was designed to contain.

You can place other classes (that don't correspond directly to objects in the .blend) in different subpackages, and that should work fine, so I don't see how this would be limiting, in terms of productivity, or even organizational flexibility.

**Comment by SolarLune** [comment]
Of course "gameobjects" is redundant - that was just an example. It could be any folder for any "category" of objects in your game.
- items/
  - Ham.java
  - Potion.java
  - Edible.java
- weapons/
  - LaserGun.java
  - Sword.java
  - RangedWeapon.java
  - MeleeWeapon.java
- characters/
  - NPC.java
  - Enemy.java
  - Player.java

... And so on and so forth.  Seems like it'd be kinda difficult to deal with the source files if every file for every object in the game, including "template" classes, sits right next to one another. I'm only sitting at 9 source files (counting BdxApp.java), which is why I looked into placing files into folders to organize them better.

**Comment by rafcolson** [comment]
I'm all for it. Using the internal scripts in Blender can be beneficial, especially for small game files, but for anything bigger I'd prefer to organize things in the way SolarLune described.

**Comment by GoranM** [comment]
Ok, I'm convinced.

I'll get to it soon enough.

**Comment by GoranM** [comment]
It's in the new release - Give it a try.

**Comment by SolarLune** [comment]
Tried it, and it works really well. Thanks! This should really help out with organization for larger projects. Issue closed!
