### ISSUE TITLE
Timer function takes longer on Android

### ISSUE THREAD

**Issue by songproducer** [GoranM/bdx#757]
Been trying to loop some music and discovered for some reason the timer function is taking longer on the device than the desktop.

**Comment by SolarLune** [comment]
What's the difference in timing amounts? It might just be the device has less precision for floating point variables and ends up finishing slower than the desktop (just a guess).

**Comment by GoranM** [comment]
The Timer object calculates simulation time (time += 1/60 for every frame), not wall clock time.

**Comment by songproducer** [comment]
> What's the difference in timing amounts?

About 6 seconds.

> It might just be the device has less precision for floating point variables and ends up finishing slower than the desktop (just a guess).

I rounded the timer float to 3 decimal places but the timing issue still remains.

Also, strangely, the Bdx.music.get function isn't working at all inside the timer function on the phone.

`   

        if (timer.done()){
        timer.restart();
        Bdx.music.dispose();
        Bdx.music.get("Space").play();
    }
`

**Comment by songproducer** [comment]
>The Timer object calculates simulation time (time += 1/60 for every frame), not wall clock time.

Does the Android device run less frames per second than the desktop?

**Comment by SolarLune** [comment]
> Also, strangely, the Bdx.music.get function isn't working at all inside the timer function on the phone.

Well, that's a different issue; it should definitely work. Are you sure it's working fine otherwise (i.e. that file does exist, the timer is running out, you can play music elsewhere, etc)?

> Does the Android device run less frames per second than the desktop?

No, not by design, but if the scene is complex and the device can't handle it, then it'll slow down, which can make the Timer execute more slowly as well. Use the profiler (in the Game menu in Blender) to see if / where the device is having trouble.

**Comment by songproducer** [comment]
I can't use the profiler because of the text issue. I solved the looping thanks to your help in the other issue - thanks!
