### ISSUE TITLE
API: Bdx.end() futile?

### ISSUE THREAD

**Issue by rafcolson** [GoranM/bdx#759]
[Bdx.end()](https://github.com/GoranM/bdx/wiki/API-Bdx#end) seems a bit useless, since it won't dispose of resources. On Android devices it's noticeable, on Desktop not so much.

We have `Bdx.dispose()`, which isn't exposed in the API (yet). I would suggest to either rename it to `Bdx.end()` or remove `Bdx.end()` and expose `Bdx.dispose()`. We then could replace [this line](https://github.com/GoranM/bdx/blob/master/src/com/nilunder/bdx/Scene.java#L890) with: `Gdx.app.exit();`

Thoughts?

**Comment by SolarLune** [comment]
> Bdx.end() seems a bit useless, since it won't dispose of resources. On Android devices it's noticeable, on Desktop not so much.

That's odd, I thought `dispose()` gets called to clean up resources when LibGDX ends the game with `Gdx.app.exit()`. Are you sure it's not being called? I recall seeing scenes get `end()` called after calling `Bdx.end()`.

> We have Bdx.dispose(), which isn't exposed in the API (yet).

Generally, I don't think people should touch the `dispose()` functions, because resources that have `dispose()` functions are handled and disposed by us in-engine. So this would be a `dispose()` function that people are encouraged to use, apart from other `dispose()` functions that aren't documented and that people aren't encouraged to use.

**Comment by rafcolson** [comment]
Okay, thanks. I'll have another look at it tomorrow.

**Comment by rafcolson** [comment]
>That's odd, I thought dispose() gets called to clean up resources when LibGDX ends the game with Gdx.app.exit(). Are you sure it's not being called? I recall seeing scenes get end() called after calling Bdx.end().

Yes. You are right. I think the confusion started after I started to get errors (which I can't reproduce anymore).

However, I think there's a bit of an infinite loop going on in `Bdx.end()`. It calls `Gdx.app.exit()`, which calls `Bdx.dispose()`, which calls `Bdx.end()` [when removing the last existing scene](https://github.com/GoranM/bdx/blob/master/src/com/nilunder/bdx/Scene.java#L890).

**Comment by SolarLune** [comment]
I don't know if it does infinitely loop, because `Bdx.dispose()` still only is called once, as I recall. If it were an actual loop, then the app would freeze until Java shut off because of a recursive loop. 

It might still be worth it to add a boolean to Bdx, like `Bdx.valid()` to indicate if the game is being shut off (if so, then ending the last scene won't try to call `Bdx.end()`).

**Comment by rafcolson** [comment]
>It might still be worth it to add a boolean to Bdx, like Bdx.valid()

Maybe so. I'll keep that in mind.
