### ISSUE TITLE
Profiler showing up on device even though disabled in Blender

### ISSUE THREAD

**Issue by songproducer** [GoranM/bdx#762]
I tried running ./gradlew clean, uninstalling the apk and restarting blender but it's still there.

**Comment by rafcolson** [comment]
Are you using the latest build (0.2.5) ?

If not, the source of the problem might be that one of the scenes in Blender has *useFramerateProfile* enabled (although the main scene hasn't). But this should be fixed since [0.2.5](https://github.com/GoranM/bdx/commit/346b5f1d5683cefd0f5b01c029cf9b9036df1b08).

>uninstalling the apk and restarting blender but it's still there.

Did you disable *useFramerateProfile*, saved the blend, ***ran the project***, assembled the apk, and reinstalled the apk on your device?

**Comment by songproducer** [comment]
Thanks, I tried deleting a scene I had appended and running and it's working correctly now.
