### ISSUE TITLE
Physics:  Model geometry drifts from physics body parent

### ISSUE THREAD

**Issue by satno** [GoranM/bdx#768]
Hi, another thing i dont understand is that simulated rigid or dynamic body drifts away from its linked non dynamic children. In my prototype im using physics to simulate paddle / ball action, but after a while the ball begins to drift away in z axis and leaves the level bounds.
![Physics bug image](https://i.imgur.com/rh8kkJQ.png)

Ball has this code:
'''
public class Ball extends GameObject {

    float movementSpeed = 0.5f;
    float maxSpeed = 1000;
    float rotationDamping = 0.98f;
    float force = 200;
    float bounceMult = 20;

    public void init() {
        //hide bounding shape
        visibleNoChildren(false);
    }

    public void main(){

        //limit rotation
        Vector3f rot = angularVelocity();
        rot.scale(rotationDamping);
        angularVelocity(rot);

        //limit speed
        Vector3f vel = velocity();
        vel.clampMax(maxSpeed);
        velocity(vel);

        //lock out y axis
        Vector3f pos = position();  
        pos.y = 0;  
        position(pos); 

        if (hit("Paddle")){
            applyForce(velocity().x*bounceMult,velocity().y*bounceMult,velocity().z+(maxSpeed));
        }

    }

}
'''

**Comment by GoranM** [comment]
The parent doesn't actually drift away from its children. If you make the parent visible, you'll be able to confirm that.

However, there is a discrepancy between the visuals in the scene, and the debug geometry, because the engine updates visual data before running the physics engine, so the physics engine generates debug geometry which is ahead by one frame.

I'm guessing that your problem here is typical tunneling: The ball is moving fast enough to avoid intersection with the boundary on a single discrete simulation step. 

The scale of your object could also be an issue: Note that blender units are interpreted as meters by the physics engine, so if your objects are far too large, or far too small, that could cause unstable/unexpected behavior. From the bullet wiki:

> Moving objects are assumed to be in the range of 0.05 units, about the size of a pebble, to 10, the size of a truck.

**Comment by satno** [comment]
I dont think my scale is off, ball has size of 1 blender unit and level bounds are 16 blender units high. Physics body still moves in y axis (at least it looks that way in simulation), even when im ressetting it each frame to 0. But the non simulated children looks locked on z/x axes, when the rigid body moves closer on y, the ball mesh begins to disappear and later shots out of scene. Also raising simulation steps does not help.

![Image if drifting](http://i.imgur.com/LBEtlEk.png)

**Comment by satno** [comment]
Looks like main problem was in setting the position.y and not the velocity.y to 0. When im setting velocity.y to 0, there is almost no drifting.

**Comment by GoranM** [comment]
> raising simulation steps does not help.

In BDX, there is only one step per frame, so changing the simulation steps in blender has no effect.

We only support a small subset of BGE features.

> Looks like main problem was in setting the position.y and not the velocity.y to 0. When im setting velocity.y to 0, there is almost no drifting.

Ah, yes, if you don't cancel out the velocity, it would just continue to accumulate, and that would explain the behavior you observed.
