### ISSUE TITLE
Deleting a .java file stops BDX compilation process

### ISSUE THREAD

**Issue by SolarLune** [GoranM/bdx#78]
Hello. So, if you create a .java file for an object and run the game so that everything works (the object running the .java file), but then decide later to delete the .java file, BDX won't be able to compile. You'll have to delete the `inst` folder (or, more specifically I suppose, the .java file that shares names with the scene the object was instantiated in).

To counter this, perhaps the process by which the inst/ folder .java files are made can be re-run whenever the source .java files (excluding the instantiated ones for the scenes) change.

**Comment by GoranM** [comment]
Yep.

Removing all files in inst, before new ones are generated, should resolve this issue.

I'll make this fix, along with the code for supbackage support (#75), as soon as Raf's work is merged (his branch is currently up to date, and since he's not that familiar with git, I don't want to make things more difficult for him by changing that).

**Comment by GoranM** [comment]
Should be resolved in the latest release.

**Comment by SolarLune** [comment]
Yep, it's solved. Thanks! Issue closed.
