### ISSUE TITLE
SpriteAnim.Animation.reset() Not Working Correctly

### ISSUE THREAD

**Issue by SolarLune** [GoranM/bdx#792]
Similarly to #791, the `reset()` function doesn't seem to be working correctly for Animations. This seems to be because the `PlayDir` property only updates when the component updates, meaning that if you call `play()` or `reset()` and alter the playback speed, the SpriteAnim will suddenly end the animation, heading in the opposite direction.

Here's an example blend file. Notice that pressing A to play a oneshot animation doesn't work - the SpriteAnim "slams" into the other end of the animation, rather than simply playing backwards. 

https://www.dropbox.com/s/kcxxo12ytf4e7l5/SpriteAnimOneshotProblem.blend?dl=0

It might also be a good idea to make it so that the `play()` function has no effect on non-looping Animations unless you manually call `Animation.reset()` or switch to another Animation first.

**Comment by SolarLune** [comment]
As another example, here's something showing what I have to do in Gearend to correctly animate a block that can be activated and de-activated using a single animation played bidirectionally:

```java

public void on(boolean setOn) {
        
    if (sa != null) {
            
        sa.play("open");
    
        if (setOn) {
            sa.speed = -1;
            sa.frame(sa.active.size() - 1);
        }
        else {
            sa.speed = 1;
            sa.frame(0);
        }
            
    }
        
    super.on(setOn);
}
```

I shouldn't have to manually set the frames here to the beginning or end - the component should correctly reset in the `reset()` function, called in the `play()` function (I believe).

Note that what I propose would probably only work if the speed were set before `play()` were called, but that's OK. Perhaps a direction attribute could be added to the `play()` function, to make it clearer that the order is important?

**Comment by GoranM** [comment]
> This seems to be because the PlayDir property only updates when the component updates

Well, it's supposed to update when the component updates, because the component is (and should be) responsible for managing the animation process. 

The core of the problem is in how the animation is actually updated, which depends on how the playHead is updated, which involves the playDir.

So, start by inspecting that code.

**Comment by SolarLune** [comment]
OK, I think this should fix it. 

PR submitted.

**Comment by rafcolson** [comment]
What do you guys think of revisiting the code of `SpriteAnim.java` in general. It seems there are also other issues related to the direction of the play head. For instance, getting the current frame will give incorrect results if I just changed direction (theoretically).
```java
sa.speed = 1;
int currentFrame = frame(); // if this is 3
sa.speed = -1;
int currentFrame = frame(); // then this will be 5
```
Because:
```java
	public int frame(){
		return active.playHead - active.playDir;
	}
```
Maybe for another Issue, but I would like to suggest to *store* the previous frame instead of calculating it.

**Comment by SolarLune** [comment]
I've never really found the SpriteAnim as easy to use as it should be, but I don't know if revisiting the code is necessary. We can slowly improve it as we have been.

**Comment by GoranM** [comment]
I'm not really sure what you mean by "revisiting", and how that would be different from just a regular analysis (in a suggestion thread) about how to generally improve things.

As long as it's clearly justified, I'm open to any change, of any size.

**Comment by SolarLune** [comment]
Well, yeah, I guess that was a bit premature. What do you mean by "revisiting", @rafcolson?

**Comment by rafcolson** [comment]
I meant, instead of improving the code gradually, we could take a closer look at the class itself, investigate where possible issues originate structurally. And improve from there.

I'm pretty sure that not every issue with SpriteAnim is solved yet. So I could give it a try. In any case I'll make the suggestion in another thread, then you and @GoranM can evaluate if those structural changes are worth it.

**Comment by SolarLune** [comment]
OK, that sounds fine. I'll close this one, for now, then, since the PR was merged.

Thanks.
