### ISSUE TITLE
Suggestion: Investigate to improve text

### ISSUE THREAD

**Issue by rafcolson** [GoranM/bdx#797]
While trying to improve the profiler, I noticed that regardless of what resolution I use (even 128), the characters will not be rendered as I had expected. I'm not sure what's going on, but it seems as if the texture is calibrated to a lower resolution, regardless of the text resolution.

@SolarLune:

Do you know what the exact ratio between the size of one pixel and one Blender Unit is?

**Comment by SolarLune** [comment]
> I'm not sure what's going on, but it seems as if the texture is calibrated to a lower resolution, regardless of the text resolution.

That doesn't sound right - are you sure the resolution is actually changing (i.e. does it look pixelly at really low font sizes)? It also might be the kerning of the actual font used - perhaps a monospaced font would look better, if the Profiler isn't already using one.

> Do you know what the exact ratio between the size of one pixel and one Blender Unit is?

Nah, I haven't looked into it - it seems that the export process is doing something to change how large the text object is represented in BDX. For example, a larger font size will lead to a larger text object in-game. 

This should probably be fixed first so Text objects are always the same size regardless of font texture size, and then are whatever size it is in Blender on run-time.

Once that's done, converting the pixel size to a Blender Unit should be a relatively simple function to add (since you know what size the texture is and how large the font object is).

**Comment by GoranM** [comment]
If you're trying to approach something that would resemble native resolution, you would need the base size to change with the point size, because otherwise you would have to manually scale the text object.

A more general problem would be with the fact that you can't predict the true resolution at which the game will be played, so you can't generate a perfect font texture at build time.

**Comment by rafcolson** [comment]
>A more general problem would be with the fact that you can't predict the true resolution at which the game will be played, so you can't generate a perfect font texture at build time.

The SCREEN viewport takes care of that. I think the main problem is getting the actual size. I noticed that the point size is not reflecting that. And I remember that Hiero exported a variable that did but fontwriter doesn't.

**Comment by rafcolson** [comment]
>That doesn't sound right - are you sure the resolution is actually changing (i.e. does it look pixelly at really low font sizes)?

Yes I'm sure.

>It also might be the kerning of the actual font used - perhaps a monospaced font would look better, if the Profiler isn't already using one.

`BDXFontMono.ttf` is mono-spaced.

I managed to get perfect-pixel results, just by sizing the text and/or zoom of the orthographic camera. The problem is that every font seems to have it's own ratio and I'm not finding anything in the `*.fntx` from which the ratio can be derived.

**Comment by SolarLune** [comment]
Hmm, I don't know about any such variable with Hiero.

We should be able to find that ratio of pixel-to-unit ourselves, right?

**Comment by GoranM** [comment]
> The SCREEN viewport takes care of that.

I don't see how it could do that; You have no guarantee that the resolution will be the same as that for which the fonts were originally rendered at build time.

**Comment by SolarLune** [comment]
Hey, so I'm back to working on this, because I need centered text (which means adding alignment).

So I could just apply a transform to the finished mesh after text() to move the vertices around to add in alignment, but this can't really work because text objects are still not displaying 1:1 to Blender or world space. I think I need to properly fix this before continuing, so does anyone have any suggestions? 

As a refresher, the first-most problem is essentially that Text objects don't share the same size between Blender and BDX.

**Comment by SolarLune** [comment]
Never mind, I'll make a new issue for my problem.

**Comment by SolarLune** [comment]
@rafcolson As for your initial question, the ratio of pixel-to-world unit can be found [here](https://github.com/GoranM/bdx/blob/master/src/com/nilunder/bdx/Text.java#L24) - that's 1 / the font texture's width and height, or what one pixel equates to in world units (Blender Units).

**Comment by rafcolson** [comment]
Thanks.
