### ISSUE TITLE
Using a group instance containing objects not in current scene prevents compilation

### ISSUE THREAD

**Issue by SolarLune** [GoranM/bdx#81]
Hey, there. So if you use a group instance that consists of objects that aren't in a layer in the current scene, BDX won't compile. 

I suppose a possible solution to this would be to run through each scene either in java or in the exporter.py script and copy template objects, materials, and textures (things that might eventually need to be changed) to a static location that can be read. 

Or print something out, like ```Warning! Group Instance "Object Name" contains objects that don't exist in current scene!``` and not add in the "problematic" object.

**Comment by GoranM** [comment]
I don't think it would be that difficult to support: We can simply include referenced objects from other scenes into the export list for the scene in question - that should pull-in the data just the same.

Or maybe we should just restructure to have one .bdx file, with all relevant .blend data, instead of the "one scene per file" approach ... I'll need to evaluate the pros and cons of that.

**Comment by GoranM** [comment]
Ok, this seems to work (in my tests, at least).

Give it a try.

**Comment by SolarLune** [comment]
Yeah, it seems to work for me as well. Thank you very much!

Closed.
