### ISSUE TITLE
Bug: physics body convex hull is offset

### ISSUE THREAD

**Issue by satno** [GoranM/bdx#847]
When angle of the model in blender is not 0, physics body is not aligned with object geometry while program is running. It can be avoided if object rotation is set to 0 in blender, and initial angle is set in code.

**Comment by SolarLune** [comment]
Hello! 

I'm not sure what you're referring to - what do you mean "the angle of the model in blender is not 0"? When I rotate an object in Blender, its physics body updates correctly in BDX.

Do you have an example blend file?

**Comment by satno** [comment]
Hi!
here is the project:
https://drive.google.com/open?id=0B8SaezemfM6cS1pDVGc2d2tTa1U
object with the problem is Flipper (Flipper.java, to amend the problem uncomment line 25, set Y rotation in blender to -40)

i meant rotation on Y axis, sorry :)

**Comment by SolarLune** [comment]
OK, I'm going to have to ask you to make a distilled example blend file, as there could be multiple different reasons for this particular issue, and having additional content just muddies the waters.

The blend file should show just the problem, and should be as simple as possible. The less unnecessary content, the better. As for classes and code, it should contain just the code necessary to display the problem, rather than an entire WIP project.

**Comment by satno** [comment]
Ok, packed the basic problem. Click LMB to rotate :)
https://drive.google.com/open?id=0B8SaezemfM6cRGdQWW5ybEVmUWs

**Comment by SolarLune** [comment]
Hey, thanks This still could've been simpler - modifiers could've been applied, and the same with scale. The class doesn't do anything to create the problem, either - the problem's there without any code, with just a static Flipper.

_____

So it seems like the issue is that Convex Hull objects are off-center for some reason. Other physics body types seem fine, it's just Convex Hull that's off-centered. Maybe it's this [offset we're doing](https://github.com/GoranM/bdx/blob/master/src/com/nilunder/bdx/utils/Bullet.java#L163) - any ideas of the reason, guys?

**Comment by GoranM** [comment]
> Maybe it's this offset we're doing

The next step in the process would be to confirm the validity of that code.

That, or you can wait for the original author (@rafcolson) to do it.

**Comment by rafcolson** [comment]
I'll look into it.

**Comment by rafcolson** [comment]
I'm terribly sorry that I didn't take the time yet. But I promise to do this as quickly as possible. I've just had some real-life issues during the last couple of months. I couldn't concentrate on the project. Hope you guys understand.

**Comment by GoranM** [comment]
You're not obligated to provide support in a timely manner, so there's no need to apologize when you can't, irrespective of the reason.

PS: Happy new year.

**Comment by SolarLune** [comment]
Yeah, don't worry about it - real life always comes first, and you don't owe anybody anything regarding BDX. 

Thank you very much for the huge amount of work you've put in so far.

**Comment by rafcolson** [comment]
@satno I'm guessing this issue got fixed along the way, right?

**Comment by rafcolson** [comment]
I think this can be closed. The test file shows no problems with current master.

**Comment by GoranM** [comment]
Ok.
