### ISSUE TITLE
Android Low FPS

### ISSUE THREAD

**Issue by benkaranja** [GoranM/bdx#851]
Hey guys,

I have been experiencing low FPS on my android projects, and now on the default Sacky project.
Low FPS on my devices and also the bluestacks emulator(which is always lighting fast).
![screen shot 2017-01-11 at 7 32 33 pm](https://cloud.githubusercontent.com/assets/9350718/21857389/53f13886-d836-11e6-82b4-8fd5dc8acb99.png)

I have built the test apks windows and also mac in my debugging attempt. Tried blender 2.78a and also 2.77. With & without profiler. The only thing i have changed on my computers, is that i have updated the Android SDK's to latest, was previously on API 19,: Kitkat as target library. 

Am out of debugging options. Anyone else with similar issues please advice.
Thanks

**Comment by SolarLune** [comment]
1) Awhile back, we improved the GLSL shader to allow for per-pixel lighting. This can kill the FPS (because the graphics card has to work harder to render the scene). [Try turning off per-pixel lighting](https://github.com/GoranM/bdx/wiki/API-Display#advancedLightingSet).

2) In addition to that, the maximum light count impacts the number of uniforms sent for lighting. If you want to try optimizing things for mobile devices, you can try lowering the maximum light count to lower values (like, say, 1 for each category). Those functions are found on the same page as the link above, just below.

________

If those don't help, I'll need to gather some more info:

1) Has this FPS problem been evident all of the time, or just recently? 

2) What version of OSX (?) do you have?

3) What version of BDX are you using?

It might be the SDK level you installed, but I'm not sure. @rafcolson might be able to weigh in.

**Comment by benkaranja** [comment]
Thanks Solar Lune. 

 To answer you questions,
- The FPS problem started recently
- I am on OSX Yosemite 10.10.5
- I am on the last BDX release 0.2.6

I am also not suspecting the SDK updates. Will try and turn off per pixel lighting, but it shouldn't kill the FPS that hard especially on a PC emulator. I will try some more tweaks & hopefully get back.

**Comment by magicgoose** [comment]
@benkaranja so did that end well?
> I will try some more tweaks & hopefully get back.

**Comment by benkaranja** [comment]
@magicgoose its been a long time, but i remember it didn't end well. Maybe I'll make some time over the weekend and give another shot
