### ISSUE TITLE
Suggestion: Replace current state machine with GDX-AI state machine

### ISSUE THREAD

**Issue by Lucrecious** [GoranM/bdx#888]
I've been using the gdx-ai API for behaviour trees and state machines, and it's much more flexible than the current system.

Here's what I'm talking about:
https://github.com/libgdx/gdx-ai/wiki/State-Machine
https://github.com/libgdx/gdx-ai/wiki/Behavior-Trees

I still like the idea of components with state machines, however, instead of using the nilunder states, using the gdx-ai states would be better. Having two types of components, one for the state machine and one for the behaviour tree would be best. All a component would need at this point is an entry point. My workaround right now is using one state to run either the state machine or the behaviour tree.

Some interesting things that their state machine allows are global states and embedded state machines (i.e. a state machine inside a state). They also keep track of the previous state, which is pretty useful.

Right now, the benefit with using the current system is that it's dead simple and super lightweight. Are these really worth it?

What do you guys think?

**Comment by SolarLune** [comment]
Hmm~

> They also keep track of the previous state, which is pretty useful.

That could be added. I also like the idea of a "state blip", like they mention - having a state go back to a previous state after exiting. Having each state keep track of the number of times it's been triggered might be cool to assist in this (so you can, for example, switch to states in sequence from a single "main" state by checking each sub state's `times` field against that of the main state). Messaging is also cool. [I actually came up with messaging for BDX awhile ago.](https://github.com/GoranM/bdx/issues/678) Didn't get in, though, haha.

> embedded state machines (i.e. a state machine inside a state)

You should be able to do this in BDX by just putting a Component inside a State and passing the acting GameObject.

> Right now, the benefit with using the current system is that it's dead simple and super lightweight. 

Yeah, I like the simplicity of our current system, too.

I think there's not really a huge reason to add code to run Gdx-ai state machines or behavior trees, since running them is pretty simple, right? Is it too complex?

I think it might be a good idea to add Gdx-ai to the list of dependencies, so it's easier to add to your project.

**Comment by Lucrecious** [comment]
Yo! Some of the things I've mentioned I've been able to do with a work around, not a big deal.

Like I said, I already run the behaviour trees and state machines using the current system (I just run their update on a state in a component). My only problems are (1) the unnecessary memory usage for a nilunder state (when using gd --it) and (2) having and maintaining a state machine when there already exists a state machine that's maintained. I mean why not use that already exists and is written for us?

Also, the state machine we have right now is coupled with the GameObject, when a GameObject is updated, the components' state machines are also stepped. Wouldn't it be better if we decoupled these logical machines, and instead provided an entry point for a GameObject to run whatever machine is on a component?

**Comment by SolarLune** [comment]
Hmm... Well, I think we did want to implement path finding at some point - #788, and I still like the idea behind messaging, so it might be a good idea to just go with Gdx-ai.

So what would be your plan forward?

**Comment by Lucrecious** [comment]
@SolarLune Yo! I don't really have plan yet. This suggestion was to see if anyone would object to this, and why they would object. I thought there was more to "we want to keep everything simple".

Anyways, another problem this switching over would be deprecation, a lot of "old" games would be broken because of how GameObjects are coupled with the state machines and components - I don't really see a way around that.

My biggest issues with the current BDX setup is that it kind of forces a paradigm upon the developer. GameObjects come with a list of components, and components are coupled with an FSM. The scene updates not only a GameObject's main method, but also its components' FSMs. In my eyes, it might just be better to remove the coupling with components all together, and either allow the developer to create a "component" based GameObject (which is already possible with a GameObject's init, end and main methods) or, create a ComponentGameObject that does that type of implementation.

It's just right now, at the lowest level of GameObject, BDX is forcing a paradigm - which I guess is the real underlying issue. Albeit, the issue is not really that concerning since we can still use simple workarounds to work a different paradigm.

I'm wondering if at @GoranM has any thoughts?

**Comment by BluePrintRandom** [comment]
Also story telling*

**Comment by GoranM** [comment]
What is the specific problem that you're trying to solve, and why can't you, or why do you find it difficult to solve with the existing system?

Can you give us a use case?

**Comment by Lucrecious** [comment]
Sure, there are multiple.

Problem: Embedded state machines
The only way to do this with the current setup is to create a new Component within a single State, and run its logic there. But you'd also need to copy Scene code to prevent running a null State.

Problem: Global state per component
There are multiple components but only one main method on the GameObject, so I can't use that. The only "easy" way to have a global state is to have an embedded state machine - which has the above difficulty.

Problem: Reverting to previous state
Can't do this unless I keep track of it myself or edit the source's Component's "state" method.

Problem: I want to use Behaviour Trees
I need to create one State just to update a Behaviour Tree. Kind of a waste of a Component.

My main point is that GDX-AI already has all these systems ready to go - a state machine and all. Why does BDX have its own version? If I want to use GDX-AI I have to go through BDX's Component system. Why not just use GDX-AI to begin with and remove the middle man?

**Comment by GoranM** [comment]
Those are approaches for solving certain problems, not really problems themselves.

What is the actual behavior that you're trying to define, that couldn't be effectively defined with the existing system?

> Why does BDX have its own version?

Because that version seemed like the simplest, most straightforward approach, with ample flexibility for most game types.

**Comment by Lucrecious** [comment]
> Because that version seemed like the simplest, most straightforward approach, with ample flexibility for most game types.
I understand, but GDX-AI has a very similar approach (almost the same actually). And it includes extra features that don't bulk up or complicate the system.

As for a problem - I understand now :)

I want to use behaviour trees so I can reuse primitive tasks and define more complex behaviour. An FSM kind of picks an entity's "state of being". For example, an NPC can _be_ "Attacking". My issue is that this "Attacking" state isn't reusable if I want to make slight changes for another NPC.

Behaviour trees allow me to define primitive tasks, so instead of defining a "state of being", I can define an action. For example, I can define an "Attack" task, and this is much more easily reusable.

So here's a scenario:
Say I define an "Attacking" state in which an NPC does the following in this order
attack -> wait 5 seconds -> attack -> attack -> wait 5 seconds

Now I want to create another NPC with just a slightly different pattern:
attack -> attack -> wait 2 seconds -> guard

The State I wrote for the first NPC is useless, I need to rewrite it for the new NPC.

With a behaviour tree I can define "Attack", "Wait (seconds)" and "Guard". I can now reuse these primitive tasks to define two behaviours using the same logic.

This is kind of a simple example, but it can get more complex in a larger system. Say the first NPC can only attack under certain conditions and the second NPC under a different set of conditions. I wouldn't be able to reuse the state that transitions to the "Attacking" state because the conditions for the first NPC don't apply to the second. Again, with a behaviour tree, I just need to define these primitive conditions, and I can reuse them without rewriting a bunch of code.

Also, specifically with GDX-AI, behaviour trees require less code from me to achieve the same thing as an FSM.

As for the current FSM, I use it just fine - however, if there are going to exist components that use behaviour trees and components that use state machines, I was suggesting to decouple the component from the FSM. And if we were going to do that, it might be worth to just replace the current FSM with GDX-AI's.

**Comment by GoranM** [comment]
Those "primitive tasks" are effectively a "state of being", because when you perform an attack, that implies that you're waiting for an attack animation to finish. Same with just waiting, or guarding, or really any behavior that needs to be perceived by the player. These are not singular events that happen instantly, in a completely isolated fashion (if they were, they could simply be implemented as pure functions).

Fundamentally, all these systems are dealing with states, with the core difference being in how those states, and their transitions are defined.

> The State I wrote for the first NPC is useless, I need to rewrite it for the new NPC.

The actual working code of the state could be factored out into methods, so that new states could just serve as a place to define transition logic.

You could also extend State:

```java
class MyState extends State{
    public MyState next;
    public MyState to(MyState next){
        this.next = next;
        return next;
    }
}

class Attack extends MyState { ...
class Wait ...
class Guard ...

// NPC A:
root = new Attack(this);
root.to(new Wait(this, 5)).
       to(new Attack(this)).
       to(new Attack(this)).
       to(new Wait(this, 5));
state(root);

// NPC B:
root = new Attack(this);
root.to(new Attack(this)).
       to(new Wait(this, 2)).
       to(new Guard(this));
state(root);
```

Not that I think any of this is really necessary, at least not if you're making the kind of small/simple games that BDX was intended to support, but it's not like you're limited to just one approach.

... Putting aside whether or not we should replace the existing system, is there anything in BDX that's making it difficult for you to use gdx-ai?

**Comment by Lucrecious** [comment]
Hey!

So I'm not really sure how that code works... I think I'm missing something.

I'll just assume it works in a similar fashion as to what I've described. Anyways, the states are such that you don't know whether it fails or succeeds (fail or succeed terminology doesn't really make sense for a state anyways). In fact, you never really know how a state "ends" which kind of sucks because sometimes you want behaviour depending on what's happened (for example if an Attack misses). With the behaviour tree, all the primitive tasks have a status, and when they finish they either succeed or fail. These statuses ride up the tree gradually, and depending on the status, different paths on the tree can be taken.

I'm not so sure how to do this with the current state machine since it doesn't really track the decision of the "leaf" states - there's not a good way to "ride" up states. I feel like an FSM would grow faster than a behaviour tree for this reason.

As for the necessity of this for smaller games, maybe not, but even small games could contain complex AI. I mean, would you consider a game like [Gearend](https://www.youtube.com/watch?v=W-aHj-084NE) too large for BDX (that's not to say Gearend is a small game)? I also feel like behaviour trees would increase the allowable scale of games that BDX can make without infringing on its simplicity for creating small games.

Lastly, as I've said before, utilizing a behaviour tree with the current setup is very simple, however, it _is_ a workaround. A workaround that does not need to exist. Having components' FSM decoupled from scene updates, does not affect a new user or the game loop in any significant way, and it allows for different approaches to solving a problem while not adding bulk to the current system.

**Comment by GoranM** [comment]
> So I'm not really sure how that code works...

If you can be more specific about what you don't understand, I can try to explain in more detail.

Keep in mind that I'm not trying to replicate the general functionality of a "behavior tree". I simply showed one of the methods by which you can create a reusable state, because that was the core issue your chosen scenario.

> As for the necessity of this for smaller games, maybe not, but even small games could contain complex AI.

That's why I said "small/simple" instead of just "small".

> Lastly, as I've said before, utilizing a behaviour tree with the current setup is very simple, however, it is a workaround. A workaround that does not need to exist.

A workaround for what, specifically? I still don't really understand that. Why is the current implementation/operation of BDX components an issue? Shouldn't you be able to use gdx-ai independently?

**Comment by SolarLune** [comment]
> I mean, would you consider a game like Gearend too large for BDX (that's not to say Gearend is a small game)? I also feel like behaviour trees would increase the allowable scale of games that BDX can make without infringing on its simplicity for creating small games.

Gearend isn't a big game, but it was a bit too complex for BDX. That's part of the reason why I added multi-blend loading and workflow improvements - to make development easier, and to make larger projects more easily supported for the future.

> Not that I think any of this is really necessary, at least not if you're making the kind of small/simple games that BDX was intended to support

As an aside, I'm not certain how small BDX games were originally intended to be, but I think at the current stage, the engine can certainly do larger games (like, Gearend) pretty well. Especially so if the game in question is coded especially well (unlike Gearend, haha).

> That's why I said "small/simple" instead of just "small".

That could also be read as "small or simple", not necessarily "small and simple".

_____

Getting back to the issue at hand, if behavior trees are desired (and I think they are) and Goran is against gdx-ai usage for the moment, maybe we could do something to make behavior trees easier to implement into BDX. The example Goran posted looks pretty simple - maybe with a few alterations and improvements to the State class, a Component could stand in as a behavior tree just as easily as it could a Finite State Machine.

For example, assuming we alter States to be able to return success, a State could serve as a container of other States (or a decorator, to change the outcome of States), and a Component could stand in as the behavior tree root to set everything in motion.

**Comment by Lucrecious** [comment]
> If you can be more specific about what you don't understand, I can try to explain in more detail.

I wasn't understanding what the "to" function was supposed to do. I was guessing it was so that when each state finished, it would change to the "next". But that would mean every state's main method would need a "state(next)" at some point. I don't see how that makes a State reusable as it would only be allowed to go to the next state (and if it doesn't, it kind of makes the entire "to" thing confusing).

When I spoke about this example, I also mentioned that there might be conditions for getting to and continuing to "Attack". Let's say you can only be in an attacking sequence if you can reach the target.
`Reach? (target): Attack -> Wait 5 -> ...`

If at any point Reach? is a failure (npc can't reach target), I can choose to call Attack (target) a fail, stop its execution before it updates again, and continue with another behaviour. If I wanted a different condition, it's as easy as:
`not StaggeredBy? (target): Attack -> Guard -> ...`

Moreover, after a condition, I can choose a type of sequence for the behaviour. For instance, I can choose to do a regular sequence or a randomized one (or a regular sequence and _then_ a randomized one).
```
not StaggeredBy? (target)
     Run in Order
          Attack, Guard, Run in Random
               Wait 5, Flee
```

I can do all of this without any of these individual primitive tasks having _any_ concept of the "next" state or task. That's what makes a primitive task in a behaviour tree so much more reusable than a state.

------------------------

> That's why I said "small/simple" instead of just "small".

I don't feel like any of these scenarios are large or complex (maybe the behaviour tree makes them look small and simple lol). Out of curiosity, why do you expect "small/simple" games from BDX? The only issues I can come up with are with Java or its garbage collection.

------------------------

> Shouldn't you be able to use gdx-ai independently?

How? If I want a component to use a behaviour tree instead of an FSM, I can't. I need to create a behaviour tree inside one of its states.

-------------------------

Lastly, I just want to mention, that the pseudocode I've written for the behaviour trees are very close to the actual syntax I would use to actually write one.

**Comment by GoranM** [comment]
> I don't see how that makes a State reusable as it would only be allowed to go to the next state

It's reusable because it can be used in other components, without modifying internal code, while specifying properties that drive certain actions of the state.

Yes, it's a special purpose chaining for a linear sequence, but that's all your scenario seemed to require, so that's all I did.

The point of my example was to illustrate that you can fashion whatever system you actually need, *if* you really need it.

Although, I don't think it's necessary to actually do that in most cases, because you can just write the states directly, and then if there's common code that seems to repeat too often, it's not really that difficult to factor it out into common methods.

> I don't feel like any of these scenarios are large or complex

They're not, and that's my point: If it's simple, it can be expressed with just a simple state machine, without requiring overwhelming effort, or really needing the benefits of "full reusability".

> Out of curiosity, why do you expect "small/simple" games from BDX?

I don't really "expect" anything. My focus was on small/simple games because, realistically, I think those are the only kind of games that most independent developers can actually bring to completion.

Also, I've seen far too many people (including myself) get trapped in an endless cycle of mental masturbation around things like "hyper generic, highly reusable, fully data driven" systems, who ultimately failed to make anything decent, because they were too focused on systematic redundancy, even when that was far from being the biggest issue in their project.

> How? If I want a component to use a behaviour tree instead of an FSM, I can't. I need to create a behaviour tree inside one of its states.

Why do you need a component to use a behavior tree? Couldn't you just have it on the GameObject?

If you want to create a container specifically for behavior trees on GameObject, and write some system code to update them, I think that would be fine.

**Comment by Lucrecious** [comment]
Alright, that's a fair response.

To address some minor things...
> Why do you need a component to use a behaviour tree? Couldn't you just have it on the GameObject?

Yes... and I could also just have an FSM on the GameObject too. But components are really nice for organization (and if I wanted different BTs to handle different things).

> If you want to create a container specifically for behavior trees on GameObject, and write some system code to update them, I think that would be fine.

To be fair, I'm only really using behaviour trees to handle one thing lol I'm just still of the opinion that if we are to include behaviour trees from GDX-AI, we should replace the current FSM with theirs for the sake of consistency (and because theirs only improves on the one BDX currently has).

**Comment by BluePrintRandom** [comment]
About the seeking agnostic generic code
I think I have finally reached the end of the rabbit hole on that one,
However this is machines that may have multiple input systems

Inputs add a list to a list
If "inputString" in dictionary, add ["GameCommand", index] to list

Sort tuples by index

For tuple in intital_list:
(tab)if tuple[0] not in moveList:
(tab)(tab)moveList.append(tuple[0])

This serializes the input and removes doubles

Then I directly call movement states, if the agent does not have a
ActStrip.

If str(input) in MovementDictionary:
(tab)funcList = MovementDictionary[str(input)]
(tab)for function in funcList:
(tab)(tab)func = function[0]
(tab)(tab)data = function[1]
(tab)(tab)func(data)


Calling functions like set_target_rot, apply_rot, move, play_animation,

This Is as deep as abstraction as one needs to go,

I actually use 2 input streams,
Act and Move
Act primarily calls transitions into states, by setting an actstrip

Player, enemy, enemy vehicles, player vehicles, friendly agents, can all
call the same stuff, to navigate, face, play anim etc.

This is py,

https://youtu.be/z3jQZ26jS-8
But I am sure java has its own stuff.

This code barely branches.

**Comment by GoranM** [comment]
I'm not convinced that a libgdx FSM is "an improvement" on the very simple API currently in BDX.

With a BDX component, I can just write the class and define the states in-line, but in the libgdx FSM, it seems that I need to write an enum that implements all the methods of the "State" interface ... Also, it seems that I don't have direct access to the state machine from within the state method, so instead of being able to change state with `state(some_state)`, I have to call `troll.stateMachine.changeState(SOME_STATE)`. Changing state is a fairly frequent activity (for me, at least), so it's hard to overlook the additional friction.

Overall, I'm not sure that replacing the existing system is a good idea, but if you need to add some code to BDX that makes using gdx-ai easier, in a way that's completely independent from BDX components, I'm open to doing that (as I said before).

**Comment by Lucrecious** [comment]
The GDX-AI API for state machines can be used in exactly the same way your simple API is being used. I mean, that's how I use them - I don't use enums, I just setup a class that implements State. From there, it looks and acts exactly like the State machine BDX currently has.

```
// Inside some Component derived class definition

private State<GameObject> core = new State<GameObject> {
     @Override
     public void update(GameObject g) {
     }
     ......
};

public Component(GameObject g) {
     StateMachine sm = new DefaultStateMachine();
     sm.changeState(core);
     ........
}
```

My only issue currently is the forced override on end(), enter() and main(), but that could easily be fixed with an intermediate class that implements empty functions.
```
class NilState implements State<GameObject> {
     @Override
     public void enter(GameObject g) {
     }

     @Override
     public void update(GameObject g) {
     }

     @Override
     public void exit(GameObject g) {
     }
}

private NilState state = new NilState() {
     ........
};
```

As for Components, I think everything would work well if Component was an interface with simply an entry point called "main". Then have an FSMComponent that extends DefaultStateMachine and implements Component (use main to step the state machine). Since a BDX Component is pretty much an FSM and we need to create a new StateMachine instance whenever we use an FSM, this isn't really much of a stretch from what Component already does.

**Comment by GoranM** [comment]
> but that could easily be fixed with an intermediate class that implements empty functions

I don't have to do that in the existing system.

> this isn't really much of a stretch from what Component already does

It's still a stretch, and one that doesn't really seem to bring significant benefits.

**Comment by Lucrecious** [comment]
Well to me, it only seems to bring only benefits with trivial drawback. This isn't like it's some next level algorithm that we're trying to implement either. It just seems worth to replace the current FSM.

> It's still a stretch, and one that doesn't really seem to bring significant benefits.

To be fair, Component doesn't specify any specific logical machine like an FSM or BT, so it could be anything. In fact, it seems _more_ reasonable if Component was agnostic to how it ran logic.

But sure, this seems like fair criticism from your perspective. I'm not really down to continue this discussion anyways, because I do agree there are only minor benefits to replacing the FSM.

Regardless, I'll do a pull request for Behaviour Trees whenever I get to it...

One question and you can close this after: If I'm not touching Component, will this new BTComponent have a separate array for BDX scene to iterate through?

**Comment by GoranM** [comment]
I'm not really sure if "BTComponent" is necessary. In BDX, a "Component" serves as a container for states, which is necessary to make a complete state machine. Does a behavior tree really need an additional container class?

---

I don't typically close issues authored by other people. You can close it whenever you want.

**Comment by Lucrecious** [comment]
Well now I got a different idea lol

> Does a behavior tree really need an additional container class?

Not really, it's just "optimal". What I do now is make one State in a Component and step/update the behavior tree in its main. It works fine, I just feel like it's wasting the FSM, and it's kind of a roundabout way of doing it.

Again, making Component an interface for an entry point doesn't cost BDX any simplicity and would only make the current system more flexible. Not to mention that it adds virtually zero bulk, it's one extra file and minor Scene.java edits. If anyone wanted to make their own type of Component, they'd just implement the Component interface. Scene.java would only have to call `component.main()` or something. Lastly, BDX could ship FSMComponent (which would be what Component is now). I don't see what's the problem with this proposition really, aside from people having to change Component to FSMComponent, which search/replace can do in less than two seconds.

**Comment by GoranM** [comment]
> It works fine, I just feel like it's wasting the FSM, and it's kind of a roundabout way of doing it.

If you just need a component that will run a specific method on some object you pass in, couldn't you just write something like this:

```java
class BT extends Component<GameObject>{
    public BehaviorTree bt;
    public BT(GameObject g, BehaviorTree bt){
        super(g);
        this.bt = bt;
        state(btUpdate);
    }
    public State btUpdate = new State(){
        public void main(){
            bt.run();
        }
    };
}
```

And then use it wherever, as many times as you need:

```java
components.add(new BT(this, some_behavior_tree));
components.add(new BT(this, some_other_behavior_tree));
```

?

**Comment by Lucrecious** [comment]
Yes, that is exactly what I'm doing already.

But you still need to create a state just to update one thing - which is my point. Like I'm creating an FSM to run a BT, rather than just creating the BT and running it.

**Comment by GoranM** [comment]
> But you still need to create a state just to update one thing

By "create a state", I assume you're referring to the actions of the runtime, rather than just writing that single state once, in the BT component class?

Having to write it once is not really a big deal. Beyond that, the additional typing is basically just `new BT(this,`, which seems almost as negligible as the runtime overhead of the additional instance.

**Comment by Lucrecious** [comment]
Whoops, forgot to respond. I meant that the new state creates extra (unnecessary) garbage for garbage collection. But yeah, it's not a big deal since State instances are pretty light.

Closing now.
