### ISSUE TITLE
Text object can't exceed max length of initial string

### ISSUE THREAD

**Issue by SolarLune** [GoranM/bdx#89]
Hey, there. So, when you create a text object in Blender, that is the maximum length that you will be able to set text to in BDX using the set() method. If your text reads "Hello" in Blender, then that means the Text object will only display up to 5 characters of whatever string you set it to display.

**Comment by GoranM** [comment]
Yes, this is by design.

Every character needs to be displayed on a quad, and in order to generate additional quads, one would have to re-create the model. Rather than add more code to do that, it seemed sensible to simply lock to the number of available characters in the original string.

This is something that will probably change in the future, but for now, simply set the string in blender to the max number of characters you expect to have at any given time; Typically, you would want to do that either way, just to see how things would actually look in those circumstances.

So, technically, not a bug.

**Comment by SolarLune** [comment]
Well, it's unexpected behavior, so I would imagine that it would be best to keep it in mind for change in the future. You probably don't want to have an additional potential point of error for users.

PR closed for now.
