### ISSUE TITLE
Multi-threading Logic Execution

### ISSUE THREAD

**Issue by SolarLune** [GoranM/bdx#895]
Hello, there.

I was working on Gearend, and while I do need to stay on top of optimization, it's still a bit underwhelming to see logic execution nearly dragging the game down from 60 FPS while the game's just using ~20% of my total CPU capability.

Being that BDX only runs on one thread at the moment, it might be a good idea to look into multi-threading logic execution. Ideally, BDX would handle multi-threading logic execution, but that might introduce a lot of engine complexity on our end, especially since not all platforms support threading. So, it might be good to introduce a "stand-in" thread class. It would execute logic for GameObjects, and the user could extend the class to execute the logic on an actual Java thread, on their desktop project (or any other project that supports threading). 

That way, it'd be a pretty small amount of work to implement on our end while still making it fairly easy to introduce actual multi-threading for individual projects that need them.

**Comment by SolarLune** [comment]
Hmm, I tried implementing this and testing, and it seems like it might not be really effective enough to implement as a base-line engine feature - raycasting from another thread, for example, seems impossible to do, unfortunately.

Here's the code I have so far: https://github.com/SolarLune/bdx/commit/986afa74ccd339817c25ca69e543161226a2782e

**Comment by GoranM** [comment]
General logic parallelism is very difficult to achieve (it takes much more than just an additional thread abstraction). It can be done, but the solutions tend to be very complicated, and rarely worth the effort.

I suspect your problem is not actually with general logic performance, but more with specific functions that happen to be extremely expensive, relative to everything else.

**Comment by SolarLune** [comment]
> It can be done, but the solutions tend to be very complicated, and rarely worth the effort.

That's kind of what I'm seeing - seems like the entire engine would have to be written in a way that favors parallelism. It's a shame, given that so much power behind CPUs are hidden behind the use of cores / threading, but it seems rare that engines or even languages put emphasis on the use of threading (I guess because of the complexity and non cross-platform compatibility of the process).

> I suspect your problem is not actually with general logic performance, but more with specific functions that happen to be extremely expensive, relative to everything else.

Yeah, it's also kind of got to do with how I made the game - if I remade it, I'm pretty sure I'd make it in a way "smaller" and more modular format and it would fare far better. Oh, well.

As a side-note, would it be possible to parallel the physics stepping and allow it to be pushed to another thread?

**Comment by BluePrintRandom** [comment]
what about batching all the raycasts and casting them in parallel ?
(bullet was talking about supporting this)


have you tried using a tree to load / unload scene elements to disk?

(unloaded elements cost no logic)


are you path finding every frame for every agent?

**Comment by BluePrintRandom** [comment]
for ray in batch:
if ray true -> callback or callback
else -> none or callback

**Comment by GoranM** [comment]
Everything in BDX functions under the assumption that execution is serial, and that certain code is guaranteed to execute before, or after some other code. I doubt that you could just take a piece of the system and run it in a different thread, without having to do some serious refactoring around all the other systems that interact with it.

Is physics stepping really the cause of the performance issue? I thought it was something in the logic system? Was it raycasts?

You need to establish where the bottleneck actually resides, before you can have an effective plan to remove it.

If you're doing too many raycasts (relative to the amount of geometry they have to sift through), I think bullet can run them faster if they fire over a limited distance, instead of the whole scene. If you can't lower that distance, maybe you can just fire them on every other frame, and organize that firing so that half of those raycast calls execute on the even frame, and the other half executes on the odd frame.

Of course, if you can actually make a system that would generally not rely so much on raycasts, that would be ideal (assuming that raycasts are at the core of the problem).

**Comment by SolarLune** [comment]
> Is physics stepping really the cause of the performance issue?

Nah, it's not, just looking for ways to improve performance in general. I might look into pushing the physics onto another thread, but that's probably more trouble than it's worth.

Thanks, anyway.
