### ISSUE TITLE
Unable to import com.nilunder.bdx.audio

### ISSUE THREAD

**Issue by TheShadyColombian** [GoranM/bdx#907]
I'm trying to import the audio libraries for bdx by inserting this line at the beginning of by game (under the package definition)

`com.nilunder.bdx.audio`

However, this produces the following errors in the console:

`
error: cannot find symbol
import com.nilunder.bdx.audio;
`
`
  symbol:   class audio
  location: package com.nilunder.bdx
`

I've tried importing other classes such as Components and the base bdx.* and both work perfectly

**Comment by GoranM** [comment]
The `import com.nilunder.bdx.audio;` statement is a directive to import a class named `audio` from the `com.nilunder.bdx` package. As the error states, that class doesn't exist in that package.

You can access audio capabilities via the already present audio object on the Bdx class: https://github.com/GoranM/bdx/wiki/General-Overview#sound-and-music

@SolarLune - The Bdx class contains an audio *object*, not a package. That should be fixed in the wiki, to avoid future confusion.

**Comment by SolarLune** [comment]
Thanks, fixed.

**Comment by SolarLune** [comment]
Is there anything else that you need help with, @TheShadyColombian? If not, you can close this issue by clicking the "Close Issue" button below the comment box.

**Comment by TheShadyColombian** [comment]
My apologies! Thanks for the excellent support guys!

**Comment by SolarLune** [comment]
No prob! 

Also, if you have any further questions, please feel free to ask on /r/bdx, as this is mainly for bug reports / feature tracking.
