### ISSUE TITLE
Camera 3D to 2D function

### ISSUE THREAD

**Issue by SolarLune** [GoranM/bdx#92]
Hey, there. A "getScreenPosition()" function on the camera class would be useful; it'd convert a 3D Vector3f to a 2D Vector2f indicating the point's position on screen from (0, 0), to (1,1). I usually use such a function to do something like display information about a character next to them in flat 2D space in a GUI overlay scene (rather than doing it in 3D in the game scene).

**Comment by GoranM** [comment]
I think it's a good idea, but I don't see the need for a "get" prefix: 
`screenPosition(Vector3f worldPosition)` seems like a nice name.

Also, when you say from (0,0) to (1,1), do you mean OpenGL traditional, where origin is at bottom left, or do you just mean normalized screen coordinates, where origin is at top left?

In either case, it seems like you would have to convert that to world coordinates of your overlay scene, and this conversion would require screen width and height.

It might be more convenient for screen position to derive from something like clip coordinates, where (0, 0) would be at the center, with X ranging from -1 to 1, and Y from -1 * height/width to 1 * height/width (assuming width > height - otherwise X ranges would be multiplied by inverse aspect ratio, while Y would be -1 to 1).

Perhaps that would be better?

**Comment by SolarLune** [comment]
That sounds pretty good, I'd suppose. I had openGL coords in mind, I suppose, but there's no need for them to have any real base in OpenGL (I don't suppose). If clip coordinates are the precedent, then there's no reason to make it more complex.

screenPosition() is fine, and the position scheme sounds OK.

I'm not sure quite how this should be approached, though, as the base Camera class in BDX lacks the necessary properties to implement this feature (no view matrix is accessible). It also lacks a pointer to the associated LibGDX camera class that I assume it relates to when you actually create a camera in the Scene.java file. What's your idea for this? Should the Camera class extend the LibGDX camera class, or should the LibGDX camera be a property of the BDX Camera class (like Camera.data or something like that)?

**Comment by GoranM** [comment]
I don't see the benefit in extending LibGDX PerspectiveCamera, or even holding a direct reference to it on the Camera class. There is only one PerspectiveCamera per scene, and it is available from scene.cam, which should be more than sufficient.

The "view matrix" is just the inverse of the camera transform, so that's not a problem.

Generally, I think the implementation would be similar to that of [raySource](https://github.com/GoranM/bdx/blob/master/src/com/nilunder/bdx/inputs/Pointer.java#L24), but done in reverse.

**Comment by SolarLune** [comment]
Isn't that short-sighted? Eventually you're going to have multiple cameras for multiple views, right?

**Comment by GoranM** [comment]
There can only be one "camera in use" at any given time: Even for things like split screen, and render to texture, unless you're doing parallel processing (we're not), you can only render one view at a time.

Of course, we'll need to store camera-specific data, but it could all easily flow through a single PerspectiveCamera instance ... Although, if we need multiple instances, or if that turns out to be more convenient, we can always do that.

It would just be a matter of setting the reference to a different instance, so using scene.cam, for now, seems perfectly reasonable.

However, if you have implementation-specific concerns, I would encourage you to outline them in detail.

**Comment by SolarLune** [comment]
I don't have implementation-specific concerns; it just seems like an odd, "hacky" piece of the API that could come back to bite people later, though it sounds like you have considered how multiple cameras would actually be used.

I gave a try at approaching this, but projection's still over my head. Please look into implementing this if possible.

**Comment by GoranM** [comment]
> it just seems like an odd, "hacky" piece of the API that could come back to bite people later

Why does it seem that way?

> projection using matrixes is still over my head

I don't mind waiting for you to learn about projection using matrices.

Not that I'm trying to push you into anything, but I think this is a really good learning opportunity.

Also, this feature is not that high on my priority list, so it's going to take a while before I get to it.

**Comment by SolarLune** [comment]
> Why does it seem that way?

No particular reason; like I said, you've considered how it works. Coming at it from a "normal" coding background, it just seems odd to have related concepts (BDX Camera and LibGDX Camera) separated.

> I don't mind waiting for you to learn about projection using matrices. Not that I'm trying to push you into anything, but I think this is a really good learning opportunity. Also, this feature is not that high on my priority list, so it's going to take a while before I get to it.

OK, but I don't know when I'm going to get to it (already trying to get game development done, much less engine development). I guess this'll just remain open until I or someone else broaches it and assigns it.

**Comment by Nananas** [comment]
Just looked into the source of the Libgdx `Camera` and found a nice [function](http://libgdx.badlogicgames.com/nightlies/docs/api/com/badlogic/gdx/graphics/Camera.html#project-com.badlogic.gdx.math.Vector3-) for this.

You can then use it like:
```java
Vector3 world_coord = new Vector3(object_or_mouse_position_as_Vector3f);
Vector3 screen_coord = scene.cam.project(world_coord);
System.out.println(screen_coord);    // prints for example: 874.0, 751.0, 0.2416482
```
Note that the coordinates start at the left bottom corner and go from 0 to the total width of the window (viewport?). Also, there is a z-component.

It would be nice to have a little wrapper around this, to hide the `Vector3` at least.

**Comment by SolarLune** [comment]
Huh, I didn't think to check the actual Camera class for this. Thanks, @Nananas!

PR submitted. So this screenPosition() function just normalizes the returned screen position that LibGDX reports (so it goes from 0,0 in the bottom-left corner to 1,1 in the top-right).

**Comment by SolarLune** [comment]
PR merged. Thanks! Issue closed.
