### ISSUE TITLE
Velocity Channels?

### ISSUE THREAD

**Issue by SolarLune** [GoranM/bdx#950]
Hey, there.

So I'm thinking of creating a solution for easily handling different velocities in GameObjects. My basic use case is that of a standard 2D platformer where an entity (like a Player) would stand on a moving platform. A simple approach would be for the developer to simply `move()` objects that are standing on the platform, but if the platform moves extremely quickly, it would cause the standing entity to phase through walls or other solid objects. 

Actually adding a velocity to the entity would be the ideal, but velocities add up every frame, so you can't easily mix a GameObject's own driven velocity with velocity gained from other external forces. We really want the velocity to stack in separate "channels" (so the Entity's movement speed could be its own, but then be added to velocity in a separate "channel", gained from moving platforms, treadmills, or other objects, which can be easily set to and read from every frame, whenever necessary).

Does this sound like a solid enough approach / common enough use case to build this functionality into BDX, or should we just expect the developer to extend GameObjects to do this manually?

**Comment by rafcolson** [comment]
I like the concept very much. Especially because you don't have to worry about friction levels, since there's no transporting involved. But how would it be implemented? Would BDX automatically detect if an object is forced down on another object (by gravity)? Or would the user still has to "select" the object from which the additional velocity is taken?
I'm not sure if this feature would be common enough, but I guess if by extension it can work, I'd rather pick such approach over the other. Just to keep the engine free of any potential unnecessary features.

**Comment by SolarLune** [comment]
Nah, it would just be velocity channels (where you can set or get velocity tied to a specific channel), which are then all added together.

**Comment by rafcolson** [comment]
Okay. I understand better now.

**Comment by GoranM** [comment]
It sounds like something that should be a part of a helper library (for games that really need it), rather than a part of the engine.

**Comment by SolarLune** [comment]
Yeah, I guess I could see that. Thanks, I'll close this, then.
