### ISSUE TITLE
[Suggestion] Remove manual disposing for Meshes

### ISSUE THREAD

**Issue by Lucrecious** [GoranM/bdx#961]
Hi

So I noticed that in Scene.java, when a Scene is "disposed" of, it calls Dispose on a lot of the items that are not necessarily owned by the Scene. For example, Meshes are not really owned by a Scene and yet they can be disposed of if their "autoDispose" is set to true, which is initially set to true due to its constructor.

I don't find this to be particularly good design because Mesh is a public class - it's a user class. As a user I don't know what "autoDispose" means, and I probably wouldn't want it initialized to true all the time. Java is GCed, so everything is already disposed of automatically (technically), so I didn't get what "autoDispose" did given its name.

I know Scene is trying to do some memory management for the sake of optimization, but I think that should be left to the user. If the user wants to optimize their memory usage, let _them_ do it. The biggest problem with this is the expectation - I expect Mesh to be valid everywhere until I explicitly kill it or it doesn't have any more references.

Anyways, this came up because I'm trying to do my own memory management and this "autoDispose" thing gets in the way, especially since it's initially set to true. I have the source so I can make it initially false, so not a big deal haha

Any thoughts on this? Why was this manual dispose added anyways? Have you guys profiled the memory usage before and after? Just curious.

Thanks!

**Comment by SolarLune** [comment]
Yo.

> So I noticed that in Scene.java, when a Scene is "disposed" of, it calls Dispose on a lot of the items that are not necessarily owned by the Scene.

I'm not certain what you mean - Scene.dispose() only calls dispose on things that are owned by the Scene. Meshes are owned by the Scene - even if two Scenes share a mesh in Blender, they each get a copy of the mesh in BDX. This could be improved upon, I think - it would be nice to share meshes to minimize the loading process. When a Scene goes to load a Mesh, it could see that it's the same one as another Scene's, and instead just point to that one, instead. But, that's beside the point. 

Also, you should not share Meshes across Scenes or place Meshes from other Scenes into a scene's meshes HashMap. Meshes contain references to Scenes, so it's best to leave them in whatever Scene they reside in.

> Java is GCed, so everything is already disposed of automatically (technically), so I didn't get what "autoDispose" did given its name.

That's not the case all of the time - there are some LibGDX classes that use manual memory allocation, like Models. You can find a link to a partial list of some of them [here](https://github.com/libgdx/libgdx/wiki/Memory-management), but basically, if a LibGDX class has a dispose() method, it needs to be called to clean up the memory. We tried putting the Mesh's disposal function in a `finalize()` method, but I did observe Meshes sticking around in memory between GC runs prior to the automatic disposal change. It seems that [we shouldn't rely on Java to eventually finalize an object](http://www.badlogicgames.com/forum/viewtopic.php?p=497#p497) to dispose of related memory as [this function may or may not ever be called](https://stackoverflow.com/questions/2506488/when-is-the-finalize-method-called-in-java).

For Meshes stored in the scene's meshes HashMap, they are never disposed of until the Scene is disposed of (as autoDispose is off for these Meshes). For copied Meshes, which default to having autoDispose on, they're only disposed of automatically if no GameObjects are using the Mesh (to be specific, when the last GameObject using the Mesh is ended).

So, either we take away auto disposal and the user would need to remember to dispose of copied Meshes when necessary (which doesn't seem like a satisfactory solution, considering how many GameObjects can have automatically copied Meshes, like from SpriteAnim components), or leave it the way it is. If we leave in auto disposal but turn it off by default, that's not really good either, since the user now needs to remember to turn it on on all copied Meshes.

> Why was this manual dispose added anyways? Have you guys profiled the memory usage before and after?

This approach to memory management was done to reduce memory leaks. However, it's possible the other recent memory fix commit I made is the one that actually fixed the Mesh leaks I was observing, and automatic mesh disposal is unnecessary. The fact remains, though, that we shouldn't use `finalize()`, and we need some method to automatically dispose of Meshes when their scene ends or, ideally, when they outlive their usefulness (if I may sound like a final boss, haha), which autoDispose does.

**Comment by Lucrecious** [comment]
> Also, you should not share Meshes across Scenes or place Meshes from other Scenes into a scene's meshes HashMap. Meshes contain references to Scenes, so it's best to leave them in whatever Scene they reside in.

I'm not sharing Meshes between Scenes, so I would have thought my code would work fine. The problem is that I don't know _where_ dispose is called. If it is owned by the Scene then it should only be called when the Scene is disposed of, but it's not. `removeObjects` gets called in two places, the `dispose` method in Scene and at the end of `runObjectLogic`. So which one is it? Is Mesh owned by Scene or by GameObject?

Because these lines suggest the latter.
```
if (g.mesh().instances.size() == 0 && g.mesh().autoDispose)
	g.mesh().dispose();
```

Also, another problem with the autoDispose is that it doesn't take into account multiple GameObjects having references to the same Mesh (which I do often to save memory). In my opinion, if autoDispose is kept then have an entire list of all the Meshes owned by Scene and only dispose of them when Scene is disposed of. Doing it the way it is now means that the same Meshes can be disposed of twice (which causes a exception due to scene == null) and also when I don't want them to be disposed of. That, or you need count the GameObjects that still hold references to Mesh before you dispose of them.


>  That's not the case all of the time - there are some LibGDX classes that use manual memory allocation, like Models. You can find a link to a partial list of some of them here, but basically, if a LibGDX class has a dispose() method, it needs to be called to clean up the memory.

Fair. However, to be clear, all these objects get GCed, the dispose method is for their _outside_ resources (like opening a file from HDD).

> The fact remains, though, that we shouldn't use finalize(), and we need some method to automatically dispose of Meshes when their scene ends or, ideally, when they outlive their usefulness (if I may sound like a final boss, haha), which autoDispose does.
haha, we can agree on this, finalize is out of the question

**Comment by SolarLune** [comment]
OK, now I'm able to comment on the rest of this.

> If it is owned by the Scene then it should only be called when the Scene is disposed of, but it's not. removeObjects gets called in two places, the dispose method in Scene and at the end of runObjectLogic. So which one is it?

When you say "owned by the Scene", it doesn't really matter in *practice* what entity owns the meshes - I was just referring to the object that holds mesh references apart from copies. GameObjects use Meshes, but in practice, meshes are removed as I mentioned - when the Scene is disposed of, or if autoDispose is on on the Mesh and all using GameObjects are ended (specifically, at the end on the game frame). [I documented this behavior in the wiki.](https://github.com/GoranM/bdx/wiki/API-Mesh#autoDispose)

> Also, another problem with the autoDispose is that it doesn't take into account multiple GameObjects having pointers to the same Mesh (which I do often to save memory).

It does take into account multiple GameObjects using the same Mesh. Like I mentioned, BDX should only dispose of a Mesh in the middle of a Scene if the last using GameObject is ended, or the Scene is disposed of.

> i.e. this is the type of code that breaks:

There's nothing wrong with the code you posted - an issue only arises if the last owning GameObject is ended for a disposed mesh. So basically, this is your issue:

```java
GameObject g1 = scene.objects.get("An Object");

// g1 is now the only user of an auto-disposed mesh.
g1.mesh(g1.mesh().copy());  

// Say you now call end() on g1. Since no other objects are 
// using the mesh, and auto-disposal is on, at the end of
// the game frame, the mesh will be disposed of.
g1.end(); 

// And then in another later game frame,

scene.objects.get("Another").mesh(g1.mesh());  
// You try to use g2's invalid mesh. This'll throw an error.
```

**Comment by Lucrecious** [comment]
> When you say "owned by the Scene", it doesn't really matter in practice what entity owns the meshes

It does matter in practice because it determines what object gets to end the `Mesh`, and if the user should call `dispose` on them. This also might be a little bit of miscommunication: when I use the term "owner" I mean it [in a very specific CS sense](https://codewithoutrules.com/2017/01/26/object-ownership/). This is what was confusing me when you said `Scene` owned `Mesh`. Regardless, I understand this more now lol Would you be open to making it so if a `Mesh` is disposed of already, calling `dispose` does nothing? (right now there's a null exception error because `scene = null`) Do that or throw a proper exception to make sure the user knows a `Mesh` is trying to be disposed of twice?

> There's nothing wrong with the code you posted - an issue only arises if the last owning GameObject is ended for a disposed mesh. So basically, this is your issue:

What you're telling me here is that if I give a valid `Mesh` to another `GameObject`, that `Mesh` should _not_ be disposed of until both those `GameObject`s end. Well, I don't have issues with sharing meshes - I have issues with meshes being disposed of _twice_ and when I don't want them to be disposed of (objects still need them!), which means something is wrong in the _product_ code. No?

All I'm doing is `g1.mesh(g2.mesh())` a bunch of times - I don't call dispose on any of them, I only end GameObjects, and no errors are raised when doing this.

I'll put up some of my actual code if need be, but I'd prefer we investigate this first to make sure it's not a problem here.

------

I've looked more thoroughly at the code, and I can't really find a problem with it. [This line looks a little suspicious though.](https://github.com/GoranM/bdx/blob/c7158e3e51744f0b735b71397ed079217c354133/src/com/nilunder/bdx/GameObject.java#L792) Any idea why we are trying to remove a `GameObject` from a `ModelInstance` array? I'm not sure if this would cause my problem above, but I thought I'd mention it.

My other suspicion is with the `join` function, maybe meshes aren't handled properly there? (I'm using `join` to put together a lot of like-objects.

The code I'm using is the same before my transition from old BDX to new BDX, so that's why I'm thinking it's something in product code (granted, autoDispose didn't exist back then)...

------

Also, a little off topic, but what do these lines do? Why is scene being moved to the front of the scene list?

And why do we need to search through the scene list to find where the mesh is? Isn't it in the same scene as the object?

(This seems like a minor optimization, like some ["move to front"](https://rosettacode.org/wiki/Move-to-front_algorithm) stuff, but I'm not sure since I thought object's scene held the mesh).

```
if (sceneList.indexOf(scene) >= 0)
	Collections.swap(sceneList, sceneList.indexOf(scene), 0);
else
	sceneList.add(0, scene);

for (Scene sce : sceneList) {
	if (sce.meshes.containsKey(meshName)){
		mOrigin = sce.json.get("origins").get(meshName);
		mDimNoScale = sce.json.get("dimensions").get(meshName);
		break;
	}
}
```

Thanks Solar!

**Comment by SolarLune** [comment]
> Would you be open to making it so if a Mesh is disposed of already, calling dispose does nothing? (right now there's a null exception error because scene = null) Do that or throw a proper exception to make sure the user knows a Mesh is trying to be disposed of twice?

Sure, that sounds fine with me. I'll submit a PR for a fix.

> I've looked more thoroughly at the code, and I can't really find a problem with it. This line looks a little suspicious though. Any idea why we are trying to remove a GameObject from a ModelInstance array? I'm not sure if this would cause my problem above, but I thought I'd mention it.

Thanks, that isn't correct. I'm surprised that'd compile, since Java knows what the list contains and what type a GameObject is, so it shouldn't be in there. I'll fix it in the PR.

> My other suspicion is with the join function, maybe meshes aren't handled properly there? (I'm using join to put together a lot of like-objects.

I don't see any issues there, and I don't see any issues in Gearend when I'm also using join().

> Also, a little off topic, but what do these lines do? Why is scene being moved to the front of the scene list?
And why do we need to search through the scene list to find where the mesh is? Isn't it in the same scene as the object?

This is old code, before we added auto disposal. It searched other scenes` `meshes` maps for the desired mesh, but this isn't really necessary now, as meshes are disposed of when scenes are disposed of. So meshes, again, shouldn't be shared across scenes, and this code is unsafe. I'll fix it in the PR.

_________

> The code I'm using is the same before my transition from old BDX to new BDX, so that's why I'm thinking it's something in product code (granted, autoDispose didn't exist back then)...

> I'll put up some of my actual code if need be, but I'd prefer we investigate this first to make sure it's not a problem here.

I understand, but I don't think the correct way around this is to examine the engine for potential problems when you know you're manually handling and disposing of meshes, which is what autoDispose is supposed to keep people from needing to do.

If you need meshes that you create (i.e. not that automatically populate the scene.meshes map) to stick around when they do not have any users, or if you want to manually handle automatic mesh disposal, turn off autoDispose on the targeted meshes. Is that not satisfactory? If not, why not?

**Comment by Lucrecious** [comment]
> I understand, but I don't think the correct way around this is to examine the engine for potential problems when you know you're manually handling and disposing of meshes, which is what autoDispose is supposed to keep people from needing to do.

This is the problem: I'm not handling the disposing of meshes - I'm not calling `dispose` myself _at all_. All I'm doing is sharing meshes with`GameObject::mesh(Mesh mesh)`, and I get null exception errors from the `dispose` method. But from what you're saying, what I'm doing should work fine. Clearly there's a problem somewhere. The code where all the meshes are being shared is isolated from everything else, and I'm not doing anything weird at all.

----

I'll let you take a look at my code (if you want) so you can verify if I'm doing anything fishy lol It's fairly short.

For context, the following code gets called after a thread loads a bunch of assets and makes these `Alien` objects that hold GameObject information.

The first piece of code is the contents of an uber method to create the "world", join GameObjects, and create meshes.

The `mapTexture` method at the bottom is where the mesh sharing happens.

The Alien class, again, is just a container with convenience methods (it holds, scale, position, ghost and then when immigrate is called, it creates an object with all those things applied to it).

The TexturePool does the bulk of the sharing work. The method of interest is `setTexture`.

Keep in mind, that I only get the exception the frame _after_ all this code runs with no problems at all. This code is basically isolated from everything else in the game, I have not implemented level de-loading yet. So I'm not ending any of these added objects yet manually. The only `GameObject::end()`s are happening through BDX in the `join` method.

[Here's the code adding in objects and merging them](http://pasteall.org/518505/java)
[The Alien class](http://pasteall.org/518507/java)
[The TexturePool class](http://pasteall.org/518509/java) (changing the name to MeshPool since that makes more sense now)

I left a few notes here and there as well. I'm not really looking for you to find a bug, but just whether or not there's a suspicious statement in there that might cause the issue I'm having.

----

Side note, I've also verified that the meshes being disposed of are meshes that I don't need, so autoDispose is doing its job :). (It's still disposing same meshes twice though).

**Comment by GoranM** [comment]
> I'll let you take a look at my code (if you want) so you can verify if I'm doing anything fishy lol It's fairly short.

If you think there's a bug, you need to narrow it down to the point where you can make a minimal example, as per instructions on the wiki: https://github.com/GoranM/bdx/wiki/Reporting-Bugs

Asking people to search your code-base for "anything fishy" is a little too broad.

**Comment by Lucrecious** [comment]
Alright, I figured it out - it was an issue of base case: What happens when more than one object have zero instances of the same mesh?

So when you first add an object, the `Mesh` for that object already contains an instance of the same `Mesh`.

So for example, in a new project with Cube in a different layer,
```
GameObject g1 = scene.add("Cube");
```
`g1.mesh().instances.size() == 2` because it's using the same `Mesh` the template uses.

So something like this, is fine:
```
GameObject g1 = scene.add("Cube");
GameObject g2 = scene.add("Cube");
g2.mesh(g1.mesh());

g1.end();
g2.end();
```

Because once both `g1` and `g2` end, there is still one a third instance of the `Mesh` they are both using, so `Scene` doesn't call `dispose` on their `Mesh`.

However, this breaks:
```
GameObject g1 = scene.add("Cube");
g1.mesh(g1.mesh().copy());
GameObject g2 = scene.add("Cube");
g2.mesh(g1.mesh());

g1.end();
g2.end();
```
Because now, `g1`'s `Mesh` is being used exactly once, i.e. `g1.mesh().instances.size() == 1` when it's first created and I give it a copy of its own `Mesh`.

So when I give its `Mesh` to `g2`, now there's exactly the same number of `GameObject`instances using the same `Mesh` instance.

Call `g1.end()`, call `g2.end()`, both get put into `Scene`'s `toBeRemoved` list. `dispose` is then called on the same `Mesh` twice because `g1.mesh().instances.size() == g2.mesh().instances.size() == 0`. Hence, null exception in `Mesh::dispose()`,

So adding
```
if (!valid()) {
    return;
}
```
At the beginning of `Mesh::dispose` should fix it... Or checking if a `Mesh` is valid during `removeObjects`, but I like the `dispose` solution better because it's consistent with the `GameObject::end()` solution to calling `end` on the same object.


Weird how this bug wasn't found earlier, seems like something that could happen? At least I know now that adding the lines above actually solves my issues and doesn't cause regression.

**Comment by Lucrecious** [comment]
Decided to leave this open until it's fixed... Just as a reminder.

**Comment by Lucrecious** [comment]
Just noticed the fix on the dispose! https://github.com/GoranM/bdx/pull/962 Closed.
