### ISSUE TITLE
Building BDX with Ant revisited

### ISSUE THREAD

**Issue by rafcolson** [GoranM/bdx#97]
I'm having another problem building BDX with Ant.

I don't understand why it searches for ```C:\Users\Acer\.gradle\caches
\modules-2\files-2.1\com.badlogicgames.gdx```.

Any ideas?
```
Buildfile: D:\BLENDER\BDX\development\GitHub\bdx\build.xml

build:
    [javac] Compiling 26 source files to D:\BLENDER\BDX\development\GitHub\bdx\b
uild

BUILD FAILED
D:\BLENDER\BDX\development\GitHub\bdx\build.xml:32: C:\Users\Acer\.gradle\caches
\modules-2\files-2.1\com.badlogicgames.gdx does not exist.

Total time: 0 seconds

D:\BLENDER\BDX\development\GitHub\bdx>
```

**Comment by GoranM** [comment]
The project depends on LibGDX, so the compilation process needs to access relevant LibGDX jars in order to build. Those jars don't ship with BDX; they are expected to be in the gradle cache.

If you're on a new machine, and you didn't install/try BDX on it before, you won't be able to build it from source, because it's the initial install and run process that gets gradle, and all the other libgdx dependencies required to build BDX.

So, for now, you need to try the official distribution, to get the dependencies, before you can build your own from source.

**Comment by rafcolson** [comment]
Yes, I re-installed my PC, so I thought it had something to do with it. I'm glad the solution is so easy. Thanks!
