### ISSUE TITLE
Font Gen: Can't find required gdx jars

### ISSUE THREAD

**Issue by Lucrecious** [GoranM/bdx#973]
So I've updated into newest BDX for my project (properly this time), and everything except for the Text is working fine.

To update to the new BDX, I started a new project, moved my code sources, symlinked my version's BDX .jars (which are updated to the latest BDX), I use maven to use my own version of LibGDX, I appended all my scenes into the new .blend and then I moved all assets from the previous project to the new project.

Before I did this, the Profilier was not working, now it's working (yay, small win)! But I get `Font Gen: Can't find required gdx jars` when exporting. What am I missing? I tried using text objects normally without transferring my project over, and everything worked just fine, so I'm not sure why now that I transferred everything I'm getting this exporting error.

Any ideas?

Here's the full traceback:
http://pasteall.org/558796

Thanks

**Comment by Lucrecious** [comment]
Yo, so I kind of figured it out... Still don't really know what went wrong though.

So first, since I was using my own version of LibGDX, I decided to give it a different version number so-to not to mix up with the actual version. So in the exporter, my version of all the .jars (1.9.6-LUCRECIOUS) were not found in the gradle cache, only 1.9.6 (I don't know why, gradle should have put them there after a clean build). 

So I switched my LibGDX version to 1.9.6, and then it still didn't work (it found all the .jars except for the tools one). No matter how I tried to get gradle to download the tools gdx jar into its cache, I wasn't able to get it to work. I didn't really know how to fix this, so I created completely new project, switched the version from 1.9.2 to 1.9.6, and it downloaded the jars that I needed into the gradle cache (including the tools gdx jar).

Now, finally, everything works fine.

Any ideas why this happened? I'm assuming it was a mistake on my part, but I can't figure out why. I thought gradle was supposed to automatically keep things up-to-date for me lol

**Comment by GoranM** [comment]
> switched the version from 1.9.2 to 1.9.6

I assume you meant to say from 1.9.6 to 1.9.2 ... ?

If the relevant jar couldn't be found, it might not be where it's supposed to be, or BDX is looking for it in the wrong place.

Or, maybe gradle didn't have an opportunity to actually download it, because the project you're using depends on the ouput of fontwriter, but fontwriter won't have the necessary libraries until your project is actually built by running gradlew (because it's at that time that gradle actually downloads all the required jars).

It might be possible to avoid these issues if we generate fonts after running gradlew, because, at that time, all the relevant libraries should be in the cache.

**Comment by Lucrecious** [comment]
I mean 1.9.2 to 1.9.6, which is version I got when I cloned BDX.

> It might be possible to avoid these issues if we generate fonts after running gradlew, because, at that time, all the relevant libraries should be in the cache.

Possibly!

On another note, I still don't understand why we can't have zero discrepancy between Blender Text and LibGDX text.

We have access to the dimensions and location of the Text in Blender, and we have access to the location and dimensions of the Text in LibGDX (don't we? otherwise how is text being drawn?). So when writing text in LibGDX wouldn't it be enough to offset and scale to match the text we see in Blender? I mean, even if the dimensions + location of the Text in LibGDX is only available after it's drawn, we would only need to make the adjustment once (at initialization), and then the text is good to go for the rest of the game.

**Comment by GoranM** [comment]
Is there a reason why you need to use 1.9.6, instead of the BDX default 1.9.2?

> I still don't understand why we can't have zero discrepancy between Blender Text and LibGDX text.

If I recall correctly, this was already discussed in a previous issue, but to summarize: Blender's text system seems to interpret/apply font metrics (or some other piece of font data) somewhat differently than our BDX/fontwriter system, so even if you could find the perfect position/scale offset to correct things for one particular font, those offsets wouldn't work for other fonts (or, at least, that was my experience when I tried to resolve this).

You would need to find the core piece of font data that relates to the discrepancy, so that we can use it to calculate the correct offsets for any given font.

> Also, is there way a to directly set the resolution? I can't seem to figure this one out. Do you use the font size?

Yes, as stated in the wiki: "The font size option in the panel indicates how large the text will appear on the texture, which is tied to how high-resolution the font will appear in-game."

**Comment by Lucrecious** [comment]
>You would need to find the core piece of font data that relates to the discrepancy, so that we can use it to calculate the correct offsets for any given font.

But don't we have the final dimensions/location in both BDX and Blender viewer? So, in code, couldn't we just adjust the dimensions/location in BDX to match that of the Blender viewer?

**Comment by GoranM** [comment]
Assuming that the discrepancy is limited to a constant offset that applies equally to each character in the text, yes, that could work. However, if that's not the case, you would have circumstances in which BDX text would be slightly shorter or longer (depending on the discrepancy).

I think I tried that before, and hit the second issue, but I'm not completely sure at this point (it's been years).

**Comment by Lucrecious** [comment]
> However, if that's not the case, you would have circumstances in which BDX text would be slightly shorter or longer (depending on the discrepancy).

That's what I was thinking, but at least with the latter issue position and height could be aligned, instead of everything being unaligned.

In any case, I thought it'd be worth a shot, but I don't understand how text is being drawn. It looks like a texture is generated and BDX manually places the UV coordinates for the letters it needs?

**Comment by GoranM** [comment]
Yes, fontwriter renders all the characters to a texture, and saves that to a png. It also creates an accompanying file that contains all the necessary information required to create quads for each character, with correct uv coords.

**Comment by Lucrecious** [comment]
It would be pretty cool if we could hijack whatever BGE uses to generate these textures. Even if we had to do something similar to what we already do (i.e. start up BGE first to let it generate the textures and information file, and save them somewhere).

Although that would require editing BGE source code.

However, if the texture generation stuff is decoupled enough from BGE, we could even "copy/paste" the code that does the exporting and make our own command line program to pass fonts through.

**Comment by GoranM** [comment]
From what I remember, there are similar issues with text in the BGE.
