### ISSUE TITLE
D-pad and Analog Input for InputMaps

### ISSUE THREAD

**Issue by SolarLune** [GoranM/bdx#977]
Hey, there. I submitted a PR a few days ago regarding this, but it didn't get in, and I thought I didn't need it. Now I'm thinking about it again, and it's still kind of awkward. Here's my problem:

In Gearend, I allow the player to rebind his inputs. That means that on any action, their inputs can be any gamepad or keyboard input, including the left analog stick and d-pad on the gamepad. I'd like to have the left analog stick and the d-pad control the same action, and to do this relatively seamlessly without adding the "missing binding" (either the analog stick's input, or the d-pad's input) later. 

Since I think most 2D games would want to have the same inputs on the d-pad as on the left analog stick, I'm thinking of a solution to add into BDX directly. I propose moving the current dpad directional inputs on the gamepad over to "dpad-left", "dpad-right", "dpad-up", and "dpad-down", and have new directional strings that refer to _both_ the d-pad and the analog stick's inputs.

**Comment by GoranM** [comment]
> I'd like to have the left analog stick and the d-pad control the same action

You can do that like this:

```java
imaps.put("action", g_ls_dir, g_dir);
```

> and to do this relatively seamlessly without adding the "missing binding" (either the analog stick's input, or the d-pad's input) later.

I don't understand why you would need to add "missing binding" to anything.

> I think most 2D games would want to have the same inputs on the d-pad as on the left analog stick

I think most would want to have those mappings set initally, but I don't think most would want to have that as a locked default, because it doesn't make sense to needlessly restrict player options in that way.

**Comment by SolarLune** [comment]
> I don't understand why you would need to add "missing binding" to anything.

Because I'm detecting the player's input binding, and they're binding either the left stick or the d-pad to the various actions in-game. When they bind an action to an input on the gamepad, I have to check to see if it's the stick or the pad, and then add in the missing binding if so. 

I have things set up to have one customize-able binding for keyboard, and one for gamepad, with another non-customize-able one being for the d-pad mimicking the left analog stick.

> I think most would want to have those mappings set initally, but I don't think most would want to have that as a locked default, because it doesn't make sense to needlessly restrict player options in that way.

I agree, but it'd still be nice to just have it as an option in BDX to make things simpler on my end for people who want the d-pad to mimic the left analog stick (which does make sense for a default).

**Comment by rafcolson** [comment]
>but it'd still be nice to just have it as an option in BDX to make things simpler on my end for people who want the d-pad to mimic the left analog stick (which does make sense for a default).

I agree that this would make sense for a default, if it's optional.

**Comment by GoranM** [comment]
> When they bind an action to an input on the gamepad, I have to check to see if it's the stick or the pad, and then add in the missing binding if so.

I don't really see why it would be treated as "missing". I mean, given some action, it can have a set of default inputs, and then the player can choose to add more or remove some. That seems like the basic principle of how you would expect control settings to work, and what most games would want to offer.

If you want to do something extra, where setting a d-pad input for something will also automatically set the corresponding stick input, or vice-versa, that sounds like something that would be fairly specific to your game, rather than being a general need that justifies engine level support.

**Comment by SolarLune** [comment]
Yo! I completely forgot that I added input forcing to InputMaps - with that, having the d-pad copy the analog stick should be relatively straightforward. Thanks.
